### ISSUE TITLE
Handle theme packages

### ISSUE THREAD

**Issue by rycee** [rycee/home-manager#1]
For example when configuring GTK. I should be able to give the configuration a theme package and not bother with theme names and such:

```nix
{
  gtk2.theme = pkgs.foo;
  gtk3.theme = pkgs.bar;
}
```

**Comment by t184256** [comment]
How would one select 'Arc Darker' from the package arc-theme with this syntax?

**Comment by rycee** [comment]
Yeah, that is unknown. I'm suspecting something like
```nix
{
  gtk2.theme = { package = pkgs.foo; name = "Theme Name 1"; };
  gtk3.theme = { package = pkgs.bar; name = "Theme Name 2"; };
}
```
would be necessary.

**Comment by rycee** [comment]
I've marked this as fixed with the above commit. It is not perfect but does allow specification of a theme (or font) package and the name of the theme (or font) to use.
