### ISSUE TITLE
"Existing file is in the way" error should return non-zero status

### ISSUE THREAD

**Issue by league** [rycee/home-manager#10]
I was deceived that my `home-manager switch` was working because it returned a zero exit status, even though it gave the "existing file" error message:

```
⋮
Starting home manager activation
Activating checkLinkTargets
Existing file '/home/league/.synergy.conf' is in the way
Please move the above files and try again

Compilation finished at Sat May 13 19:00:03
exit [0]
```

Should it return non-zero so the failure is more obvious in certain contexts?

**Comment by rycee** [comment]
Thanks for the report and yeah I agree completely. I did initially attempt to make it return a non-zero error code but this attempt didn't immediately succeed so I gave up ☺

I will try to do a more vigorous attempt tomorrow.
