### ISSUE TITLE
mouse is to small:

### ISSUE THREAD

**Issue by zeta-00** [rycee/home-manager#1003]
Hello there, I am currently using xmonad in nixos. One problem that I am having is that the mouse size is just to small, I can barely see it. So is there a home-manager option that I can set in home.nix to change the mouse size? Also, is there any other options that I can use to configure some mouse settings, like for example how it looks, I like the mouse that looks like a hand pointing. If you can help me fix these issues, thanks

**Comment by rycee** [comment]
Check the [xsession.pointerCursor](https://rycee.gitlab.io/home-manager/options.html#opt-xsession.pointerCursor) option.
