### ISSUE TITLE
Timers are not started automatically

### ISSUE THREAD

**Issue by danbst** [rycee/home-manager#1019]
I have `systemd.user.startServices = true;` and a user timer defined. However, after switch my timer is not listed as active:
```
# systemctl --user list-timers --all
NEXT LEFT LAST PASSED UNIT                      ACTIVATES
n/a  n/a  n/a  n/a    nix-collect-garbage.timer nix-collect-garbage.service
```
I have to do `systemctl --user restart timers.target` manually, then timers are activated
```
# systemctl --user list-timers --all
NEXT                         LEFT     LAST PASSED UNIT                      ACTIVATES
Thu 2020-02-06 09:00:00 UTC  10h left n/a  n/a    nix-collect-garbage.timer nix-collect-garbage.service
```
Would be great to start timers alongside with services.

**Comment by rycee** [comment]
Should be sorted now. Thanks for the suggestion!
