### ISSUE TITLE
nixpkgs.config.allowUnfree not applied to imports

### ISSUE THREAD

**Issue by codygman** [rycee/home-manager#1022]
This works:

```nix
# home.nix
{ config, pkgs, home, ... }:
with import <nixpkgs> {};
with lib;
{
  nixpkgs.config.allowUnfree = true;
  programs = {home-manager.enable = true;};
  home = {packages = with pkgs; [teams];};
}
```

Trying to import a module that installs an unfree package appears not to respect the `nixpkgs.config.allowUnfree = true;` in home.nix:

```nix
# home.nix
{ config, pkgs, home, ... }:
with import <nixpkgs> {};
with lib;
{
  nixpkgs.config.allowUnfree = true;
  imports = [ ~/Sync/nix-home-manager-config/work.nix ];
  programs = {home-manager.enable = true;};
  home = {packages = with pkgs; [];};
}
```

```nix
# ~/Sync/nix-home-manager-config/work.nix
{ config, pkgs, home, ... }:
with import <nixpkgs> {};
with lib;
{
  home = {packages = with pkgs; [teams];};
}

```

Output:

```shell
[cody@nixos:~/.config/doom/nixpkgs]$ home-manager switch --show-trace
error: while evaluating the attribute 'buildCommand' of the derivation 'home-manager-generation' at /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'text' of the derivation 'activation-script' at /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating 'mkCmd' at /home/cody/.nix-defexpr/channels/home-manager/modules/home-environment.nix:395:17, called from undefined position:
while evaluating the attribute 'data' at /home/cody/.nix-defexpr/channels/home-manager/modules/lib/dag.nix:96:41:
while evaluating the attribute 'data' at /home/cody/.nix-defexpr/channels/home-manager/modules/lib/dag.nix:89:11:
while evaluating the attribute 'data' at undefined position:
while evaluating anonymous function at /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/lib/modules.nix:84:45, called from undefined position:
while evaluating the attribute 'value' at /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/lib/modules.nix:379:9:
while evaluating the option `home.activation.installPackages.data':
while evaluating the attribute 'mergedValue' at /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/lib/modules.nix:411:5:
while evaluating the attribute 'values' at /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/lib/modules.nix:405:9:
while evaluating the attribute 'values' at /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/lib/modules.nix:505:7:
while evaluating anonymous function at /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/lib/modules.nix:391:28, called from /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/lib/modules.nix:391:17:
while evaluating 'dischargeProperties' at /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/lib/modules.nix:464:25, called from /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/lib/modules.nix:392:62:
while evaluating the attribute 'value' at /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/lib/modules.nix:277:44:
while evaluating the attribute 'passAsFile' of the derivation 'home-manager-path' at /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/pkgs/build-support/trivial-builders.nix:7:14:
while evaluating the attribute 'handled' at /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/pkgs/stdenv/generic/check-meta.nix:251:7:
while evaluating 'handleEvalIssue' at /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/pkgs/stdenv/generic/check-meta.nix:147:38, called from /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/pkgs/stdenv/generic/check-meta.nix:252:14:
Package ‘teams-1.3.00.958’ in /nix/store/pglfgajgn6vzbagbsg37c97c34xzizhp-nixos-20.03pre210300.05626cc86b8/nixos/pkgs/applications/networking/instant-messengers/teams/default.nix:56 has an unfree license (‘unfree’), refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.
```

**Comment by rycee** [comment]
Yeah, I can imagine this being a bit confusing 🙂

Firstly, the `import <nixpkgs> {}` attribute set includes an attribute `pkgs` that references the package set for the host system, which will be a self reference unless you are doing cross-compilation. When you do `with import <nixpkgs> {};` you therefore override the `pkgs` variable bound as a function argument on line 2, which will be set up by HM to honor the `nixpkgs.config` options.

Secondly, since you pass `{}` to the `import <nixpkgs>` function it will _impurely_ read the Nixpkgs configuration and overlay files in `~/.config/nixpkgs` and any Nixpkgs configurations and overlays you've set in your HM configuration are therefore ignored. In other words, the `nixpkgs.config.allowUnfree = true` line is not having any effect in these Nix files.

So my guess is that you in the error case simply didn't have a `~/.config/nixpkgs/config.nix` file – or had one but it didn't include `allowUnfree = true` – and in the success case did have a `config.nix` file that included `allowUnfree = true`.

Is there any specific reason why you want to import everything in Nixpkgs into scope? If so then please describe what you want to accomplish and we'll find a safer solution. If not then I would suggest removing the `with import <nixpkgs> {}` lines.

**Comment by codygman** [comment]
> Yeah, I can imagine this being a bit confusing slightly_smiling_face
> 
> Firstly, the `import <nixpkgs> {}` attribute set includes an attribute `pkgs` that references the package set for the host system, which will be a self reference unless you are doing cross-compilation. When you do `with import <nixpkgs> {};` you therefore override the `pkgs` variable bound as a function argument on line 2, which will be set up by HM to honor the `nixpkgs.config` options.
> 
> Secondly, since you pass `{}` to the `import <nixpkgs>` function it will _impurely_ read the Nixpkgs configuration and overlay files in `~/.config/nixpkgs` and any Nixpkgs configurations and overlays you've set in your HM configuration are therefore ignored. In other words, the `nixpkgs.config.allowUnfree = true` line is not having any effect in these Nix files.
> 
> So my guess is that you in the error case simply didn't have a `~/.config/nixpkgs/config.nix` file – or had one but it didn't include `allowUnfree = true` – and in the success case did have a `config.nix` file that included `allowUnfree = true`.
> 
> Is there any specific reason why you want to import everything in Nixpkgs into scope? If so then please describe what you want to accomplish and we'll find a safer solution. If not then I would suggest removing the `with import <nixpkgs> {}` lines.

Oh my... that is quite funny and as you say confusing. It helps me understand nix better though. I thought importing all of nix was necessary which is why I imported it, but I realize now that's what the pkg attribute you pass into the module is for:

```nix
{ config, pkgs, home, ... }:
{
  programs =
    {
      git = {
        userEmail = "cody@workEmail.com";
      };
    };
  home = {
    packages = [ pkgs.teams ];
  };
  services = {
  };
}
```
