### ISSUE TITLE
XDG MIME default application gets overridden

### ISSUE THREAD

**Issue by LouisTakePILLz** [rycee/home-manager#1028]
```nixos
{ config, pkgs, ... }:

{
  # ...

  # Set default programs
  xdg.mimeApps.enable = true;
  xdg.mimeApps.defaultApplications =
    let
      file_browser = [ "ranger.desktop" ];
      web_browser = [ "chromium.desktop" "firefox.desktop" ];
      image = [ "chromium.desktop" ];
      torrent = [ "qbittorrent.desktop" ];
    in
      {
        "inode/directory" = file_browser;
        "text/html" = web_browser;
        "x-scheme-handler/http" = web_browser;
        "x-scheme-handler/https" = web_browser;
        "x-scheme-handler/about" = web_browser;
        "x-scheme-handler/unknown" = web_browser;
        "application/x-bittorrent" = torrent;
        "x-scheme-handler/magnet" = torrent;
        "image/png" = image; # <<<<<<< This gets overridden by wine and gimp
      };

  # ...
}
```

![image](https://user-images.githubusercontent.com/920910/74485931-db014100-4e89-11ea-8b61-072e6920af7f.png)

I've tried:
- adding `image/png=chromium.desktop` to `xdg.mimeApps.associations.added`
- adding `image/png=wine-extension-png.desktop` to `xdg.mimeApps.associations.removed`
- running `update-mime-database ~/.local/share/mime`

I'm aware that this is most likely not an issue specific to NixOS/home-manager, but I was hoping you could shed some light on this issue.

**Comment by rycee** [comment]
Hmm, it's not very elegant but if you install Wine through `home.packages` then you could try adding something like
```
home.extraProfileCommands = ''
  rm $out/share/applications/wine-extension-png.desktop
'';
```
to your configuration.

**Comment by LouisTakePILLz** [comment]
Oof yeah that's one hacky workaround.

I've always had issues with xdg mimes (regardless of distro), not sure if it's just broken and nobody bothered to look at it or what...

**Comment by LouisTakePILLz** [comment]
Turns out the desktop file is called `chromium-browser.desktop`... oops :)
I had wrongfully assumed the name was correct since it seemed to work for some applications.
I realized it wasn't correct when other applications were failing to open URLs.
