### ISSUE TITLE
Emacs mode menus not showing when using extrapackages?

### ISSUE THREAD

**Issue by spacekitteh** [rycee/home-manager#1029]
E.g. when opening a .org file, all the other menus work, but the Org, Tbl and Text menus are empty.

```nix
  programs.emacs = {
    enable = true;
    extraPackages = epkgs: [
        epkgs.org-ref epkgs.org-brain epkgs.helm epkgs.org epkgs.org-plus-contrib
        epkgs.melpaPackages.solarized-theme
      ];
    };

  services.emacs.enable = true;
```

**Comment by rycee** [comment]
This is unlikely to be a Home Manager issue since HM simply pass the `extraPackages` value on to the Nixpkgs Emacs wrapper package.

That said. When you open an org file, is org-mode activated at all? Could you share the bit of your Emacs configuration that sets up org mode?

**Comment by spacekitteh** [comment]
Nevermind; it seems to be a Ubuntu issue: https://www.reddit.com/r/emacs/comments/bgkpaz/emacs_menus_on_ubuntu_not_working/
