### ISSUE TITLE
neomutt: support reverse sorting methods

### ISSUE THREAD

**Issue by evanjs** [rycee/home-manager#1035]
Per the neomutt [documentation](https://neomutt.org/guide/reference.html#3-388-%C2%A0sort):

> You may optionally use the "reverse-" prefix to specify reverse sorting order.
Example:
`set sort=reverse-date-sent`

I figure it's best to not hard-code the reverse sorting options, but maybe map over the existing enum and include `reverse-` options?

Or is this not best practice when it comes to defining type defaults and such?

cc @teto

**Comment by teto** [comment]
you refer to the `set sort = "${cfg.sort}"` I suppose ? 
Apparently we don't describe every possible solution so either we can fix it or leave it freeform.
I believe it's best to not hardcode things but pass is as some structured default that can be overriden. Feel free to send a patch.

**Comment by evanjs** [comment]
Oops yes forgot to link to the [option](https://github.com/rycee/home-manager/blob/115e76ae12a81bce5dcd19714cdeaaa8d5ca3ce8/modules/programs/neomutt.nix#L213).

Sounds good, I'll take a look at some implementations.

**Comment by teto** [comment]
also seems like it would make more sense as an account specific setting. Along with most settings in fact... my bad
