### ISSUE TITLE
User folder in /nix/var/nix/profiles/per-user not created

### ISSUE THREAD

**Issue by NicolasGuilloux** [rycee/home-manager#1050]
Hi there!

I am currently building a custom Live OS and I use the Home Manager to load some files in the home folder. And... it failed :(
After some investigation, I discovered that the service `home-manager-myuser.service` failed to start because of the missing folder `/nix/var/nix/profiles/per-user/myuser`. I had the same bug when I installed NixOS for the first time.

For now, I used a workaround to create the folder before the `home-manager-myuser.service` launches. But I'm not satisfied with this solution. I hope a Nix guru will find a solution because I spent several days on it and I came up with an ugly solution based on Systemd services. Not the best approach :p 

For those of you annoyed by this issue, I paste my workaround. Make sure you changed `myuser` with the appropriate username. Cheers guys!

```
systemd.services."before-home-manager-myuser" = {
    script = "mkdir -p /nix/var/nix/profiles/per-user/myuser";
    path = [ pkgs.coreutils ];
    before = [ "home-manager-myuser.service" ];
    wantedBy = [ "multi-user.target" ];
};
```

**Comment by talyz** [comment]
For reference, this was introduced with https://github.com/NixOS/nixpkgs/commit/4e0d6a5ff8157e6aacb1ef0b948d0b7dca36341f
