### ISSUE TITLE
Backporting programs.fish.plugins

### ISSUE THREAD

**Issue by kosterheld** [rycee/home-manager#1051]
Is there any chance you coud add programs.fish.plugins to release-19.09? I'd greatly appreciate it.

**Comment by rycee** [comment]
I'm reluctant to merge this change into the stable branch since it's quite large and a direct cherry-pick didn't apply cleanly. Do you need it urgently or could you wait until the next stable version coming in a month or so?

**Comment by kosterheld** [comment]
It's not really urgent. I'll probably just switchh to unstable for a few months.
