### ISSUE TITLE
programs.firefox.enableAdobeFlash appears to do nothing

### ISSUE THREAD

**Issue by owm111** [rycee/home-manager#1062]
I have tried setting `programs.firefox.enableAdobeFlash = true` in `home.nix`, however it does not appear to do anything. Checking `about:addons`, and nothing related to flash appears. I tried opening a page with a swf, and it says flash player is not installed.

From my `home.nix`:

```nix
{
  programs.firefox = {
    enabled = true;
    enableAdobeFlash = true;
  };
}
````

From my `config.nix`:

```nix
{
  allowUnfree = true;
  firefox = {
    enableAdobeFlash = true;
  };
}
```

Is there anything else that has to be set?

**Comment by rycee** [comment]
Haven't used flash in a long time so I can't say but perhaps you'll need to enable some option in `about:config` as well? If you have verified that the plugin files get installed then I think this is a Firefox or Nixpkgs issue rather than a HM one.

**Comment by owm111** [comment]
I apologize, that is indeed correct. `MOZ_PLUGIN_PATH` is being set, however it appears that Firefox now ignores it, according to <https://github.com/NixOS/nixpkgs/issues/76943>.

**Comment by bjornfor** [comment]
FYI, adobe flash works as of firefox 80.0, ref https://github.com/NixOS/nixpkgs/issues/76943#issuecomment-699636941.
