### ISSUE TITLE
Why are the contents of ~/Downloads being copied in the Nix store?

### ISSUE THREAD

**Issue by jwiegley** [rycee/home-manager#1089]
Recently I've noticed my /nix volume growing _very_ quickly from day to day. I took a look at the disk space being used there today and saw this:

```
     1.36G       4418  ./cq3ldi97bxvyw37h1sff9910ihjvwh10-ghc-8.8.2/
     1.36G       4418  ./0g7pfzvdd4262b1h2hqk439zirhd5mw5-ghc-8.8.2/
     1.37G       4418  ./vzinwmpck7nq6ar0hx8xvdyd7zmvm64x-ghc-8.8.2/
     1.40G       7907  ./w87nykh9aicp5priwh7v4axhcj9rka5x-ghc-8.6.3-binary/
     9.22G        545  ./h5ivkhrr48w2y195cd99brkwfcm02hv9-hm_Downloads/
     9.32G        549  ./wjib7h52hqsjwa06dds427b94pz89ycc-hm_Downloads/
    16.91G       1240  ./50flirynf39d1jxgixrdhvmgbva7daac-hm_Downloads/
    16.92G       1238  ./d2g20jryfwjqxjl7x6ijzgqq3sqy6nm2-hm_Downloads/
    16.93G       1237  ./8n1bbfggjxbhgy9adxgjx5ip3i751pnf-hm_Downloads/
    16.94G       1242  ./jyb6ks138kf2z4icq5gmacain3z4fax6-hm_Downloads/
    16.95G       1241  ./yckcj68caklba8hr4z8jg7wxcdcyncnr-hm_Downloads/
   181.61G    1523047  ./
```

When I look into these `hm_Downloads` entries, it appears that the entire contents of my `~/Downloads` directory is being flattened and copied into the store, something that I neither asked for nor want. I'm presuming that the `hm` prefix has something to do with home-manager.

A few questions:

- Is this a bug?
- If not a bug, what is the rationale?
- How do I disable it?

Thanks!

**Comment by jwiegley** [comment]
I think this might be due to me, and having this in `home.file`:

```
    file = builtins.listToAttrs (
      map (path: {
             name = path;
             value = {
               source = builtins.toPath("${home_directory}/src/home/${path}");
             };
           })
          [ "Library/Scripts/Applications/Download links to PDF.scpt"
            "Library/Scripts/Applications/Media Pro" ]) // {
        ".cups".source    = "${xdg.configHome}/cups";
        ".dbvis".source   = "${xdg.configHome}/DbVisualizer";
        ".gist".source    = "${xdg.configHome}/gist/account_id";
        ".jira.d".source  = "${xdg.configHome}/jira";
        ".macbeth".source = "${xdg.configHome}/macbeth";
        ".recoll".source  = "${xdg.configHome}/recoll";
        ".slate".source   = "${xdg.configHome}/slate/config";
        ".zekr".source    = "${xdg.configHome}/zekr";

        ".dl".source = "${home_directory}/Downloads";

        ".ledgerrc".text = ''
          --file ${home_directory}/Documents/accounts/main.ledger
          --date-format %Y/%m/%d
        '';

        # ".tmux.conf".text = ''
        #   set-option -g default-command "reattach-to-user-namespace -l ${pkgs.zsh}/bin/zsh"
        # '';

        ".curlrc".text = ''
          capath=${pkgs.cacert}/etc/ssl/certs/
          cacert=${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt
        '';
        ".wgetrc".text = ''
          ca_directory = ${pkgs.cacert}/etc/ssl/certs/
          ca_certificate = ${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt
        '';
      };
```

**Comment by jwiegley** [comment]
In order to manage the symlink pointing `dl` to `Downloads`, it seems to want all of `Downloads` in the store?

I'll close until I determine if this isn't the problem.

**Comment by rycee** [comment]
Ouch! I do believe it is the `home.file.".dl".source = "${home_directory}/Downloads";` entry that would cause this. It is safe to assume that any value in `home.file` will end up in the Nix store one way or another.

If you want to create a symlink then my current recommendation is to do it explicitly in an activation script block like so
```nix
home.activation.linkMyFiles = lib.hm.dag.entryAfter ["writeBoundary"] ''
  ln -s "${home_directory}/Downloads" ~/.dl
'';
```

**Comment by rycee** [comment]
Oh, and just to be clear this would apply to the other entries as well so, for example the
```
".cups".source    = "${xdg.configHome}/cups";
```
line would mean "copy the content of `${xdg.configHome}/cups` to the Nix store and link that to `~/.cups`. In other words if you run `readlink -m ~/.cups` it'll print some path inside the Nix store, not `~/.config/cups`.

There have occasionally been discussions about adding `home.symlink."blah blah".source = …`, which would explicitly establish a symbolic link and make an effort to prevent the source from ending up in the Nix store.

**Comment by jwiegley** [comment]
Thanks, @rycee, I just disabled all of those lines and for the moment and managing these types of symlinks by hand.
