### ISSUE TITLE
programs.firefox.extensions not working

### ISSUE THREAD

**Issue by dR3b** [rycee/home-manager#1096]
Hi, 
```bash
  programs.firefox = {
    enable = true;
    extensions = lib.mkIf config.programs.firefox.enable (
      with pkgs.nur.repos.rycee.firefox-addons; [
        decentraleyes
        gesturefy
        ublock-origin
        vimium
    ]
  );
```
This code no longer works with Firefox 74. Can anyone confirm that?
Thanks!

**Comment by rycee** [comment]
I'm guessing you are using the 19.09 branch of Home Manager? If so then I would suggest switching to the `firefox-esr` package. Unfortunately the `firefox` package in Nixpkgs 19.09 got updated to 74 which is not compatible with the way extensions are installed in the `release-19.09` branch. It is unlikely that I will find the time to backport the changes necessary to make it compatible.

If you or anybody else would like to backport and test that is fine, it should mainly be a matter of cherry-picking relevant commits and fixing merge issues.

**Comment by rycee** [comment]
Should work now. Please reopen if it's not.
