### ISSUE TITLE
Add the possibility for custom activation logic

### ISSUE THREAD

**Issue by Gerschtli** [rycee/home-manager#1102]
Hey,

this issue is a reminder for @rycee for your comment in https://github.com/rycee/home-manager/pull/779. I wanted to add a new activationScript section but you wanted to refactor the whole `home.activation` thing to provide a better interface for the user.

What is the state of this? How should it work? Can I help (or somebody else)?
I need this feature and still looking forward to see this implemented.

**Comment by rycee** [comment]
Yeah, the `home.activation` option is now public and it performs type checking. I even wrote a description for it: https://rycee.gitlab.io/home-manager/options.html#opt-home.activation 🙂

There are improvements to be had in the documentation area but I'm pretty happy with the code so far.

**Comment by Gerschtli** [comment]
Oh I'm sorry, I completely missed that this api is already public! I will check it out, thank you!
