### ISSUE TITLE
Example how to use newer version of a package configured by home-manager

### ISSUE THREAD

**Issue by nh2** [rycee/home-manager#1107]
Commit a93d01fb4d66addd20afb3c8eba982ee80fdc9a8 added an example of how to use a nixpkgs-`unstable` version of a package for `home.packages` (the equivalent of NixOS's `systemPackages`).

But could we also have an example to override a tool that `home-manager` provides own configuration for?

For example, I would like to use `skim` `0.8.0`, a newer version than the one that `programs.skim` configures.

In NixOS, this is configurable for many services using `.package`, e.g `services.nginx.package` for Nginx.

How can we do the same with `home-manager`?

It would be a great to have an official example in the FAQ.

**Comment by nh2** [comment]
Is using an overlay recommended? E.g. using:

```nix
{ config, pkgs, ... }:

let
  pkgsUnstable = import <unstable> {};
in

{
  nixpkgs.overlays = [
    (final: previous: {
      skim = pkgsUnstable.skim;
    })
  ];

  programs.home-manager.enable = true;
  programs.skim.enable = true;
}
```

**Comment by rycee** [comment]
Yes, in this case an overlay is the recommended option. I will add this example to the FAQ. Thanks for opening the issue :-)

**Comment by nh2** [comment]
Thanks!
