### ISSUE TITLE
How to add to config by default.nix ?

### ISSUE THREAD

**Issue by 573** [rycee/home-manager#1112]
Let's say I want to use a software from github that already has a nix-build'able default.nix but doesn't seem to exist in the nix channels somewhere yet.

How would I integrate that in my hm config ?

I tried and tested (snippet from ~/.config/nixpkgs/user/me.nix imported in home.nix):

```
{ config, pkgs, ... }:
with import <nixpkgs> {};
with builtins;
with lib;
let
  neuron = stdenv.mkDerivation {
   name = "neuron";
   src = fetchFromGitHub {
     owner = "srid";
     repo = "neuron";
     rev = "dd900dd249742aabfb1dba89f498b6afdb7f4531";
     sha256 = "1zcgd46hjjhsj1g2sifx0hp1cvmd3nssn3nvw48vb5k40sfslkdq";
   };
   phases = [ "installPhase" ];
   buildInputs = [ makeWrapper ];
   installPhase = ''
     mkdir -p $out/bin
     makeWrapper $out/neuron $out/bin/neuron
   '';
};
in
{
  home.packages = with pkgs; [
    neuron
  ];
}
```

but that doesn't work:

>  these derivations will be built:
    /nix/store/flz6zqa1hjpjqmhgiba7z7l6jp0d1ygx-neuron.drv
    /nix/store/rdqc7dzmm230w0bxcn7ylds756s6qjrq-home-manager-path.drv
    /nix/store/2pww4m99hmh5bmjk0xlall9n91l7wd5m-activation-script.drv
    /nix/store/idjl4rvj15s0fa2fcyi6hngzrdixmx4i-hm_fontconfigconf.d10hmfonts.conf.drv
    /nix/store/s32pcgy9xp21x9pakhimlcxgr078m6hm-home-manager-files.drv
    /nix/store/yhmxwcq4vihrkclr9v53qfcb7rnf6yi7-home-manager-generation.drv
    building ‘/nix/store/flz6zqa1hjpjqmhgiba7z7l6jp0d1ygx-neuron.drv’…
    installing
>
> Builder called die: Cannot wrap ‘/nix/store/3ca7lxvvd50sgs4l6743fhx1a0fnyqf4-neuron/neuron’ because it is not an executable file
    Backtrace:
    7 assertExecutable /nix/store/06nq4z17fh43wrbn6hl1yq7bzs99lpr1-hook/nix-support/setup-hook
    39 makeWrapper /nix/store/06nq4z17fh43wrbn6hl1yq7bzs99lpr1-hook/nix-support/setup-hook
    1326 genericBuild /nix/store/qghrkvk86f9llfkcr1bxsypqbw1a4qmw-stdenv-linux/setup
    2 main /nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh

**Comment by 573** [comment]
Tracking this as a reference [here](https://github.com/srid/neuron/issues/21)

**Comment by rycee** [comment]
Seems like a problem in the package. But you are absolutely going to want to replace
```
with import <nixpkgs> {};
with builtins;
with lib;
let
  neuron = stdenv.mkDerivation {
   name = "neuron";
   src = fetchFromGitHub {
```
by something like
```
let
  neuron = pkgs.stdenv.mkDerivation {
   name = "neuron";
   src = pkgs.fetchFromGitHub {
```
unless you have a very good reason to do it the first way.
