### ISSUE TITLE
nextcloud-client only able to start in foreground

### ISSUE THREAD

**Issue by MaxSchlueter** [rycee/home-manager#1121]
Is there an easy way to start the nextcloud client in the background, i.e. by supplying the `--background` flag to the executable that is started by the service? Or should I write my own nextcloud client service in this case? My desktop environment doesn't have system tray support and the client pops up with a window after every login.

**Comment by rycee** [comment]
I think you should be able to force the use of `--background` by adding
```
systemd.user.services.nextcloud-client.Service.ExecStart =
   lib.mkForce "${pkgs.nextcloud-client}/bin/nextcloud --background"
```
to your configuration.

If this option is generally useful then feel free to create a PR that adds an option for it in the module.

**Comment by MaxSchlueter** [comment]
Thank you, that solved it for me :)
I guess most users that use Nextcloud would want the icon to be displayed.. Will create a PR though when I find the time.
