### ISSUE TITLE
Do not hardcode `-detectsleep` in `services.screen-locker` xautolock

### ISSUE THREAD

**Issue by JustinLovinger** [rycee/home-manager#1125]
I want `services.screen-locker` to lock if my system has been asleep and inactive for the timeout period. I do not want my system to lock if it has been asleep for less than the timeout period. To achieve this, I cannot have the `-detectsleep` option. However, `services.screen-locker` hard codes this option, and cannot disable it.

**Comment by rycee** [comment]
Assuming you are using the master branch, try updating and adding `services.screen-locker.enableDetectSleep = false` to your configuration.
