### ISSUE TITLE
neovim module

### ISSUE THREAD

**Issue by teto** [rycee/home-manager#114]
I needed to experiment a bit with neovim and language server protocols so I've started a neovim module. Just let you know to prevent duplicate work.

**Comment by rycee** [comment]
Nice! It was a long time ago I used vim so I cannot tell how much overlap there would be between a neovim module and the current vim module.

In any case if you run into issues then let us know. You can always open a PR marked with [WIP] with half-finished work and ask for comments there.

**Comment by teto** [comment]
I pushed a first version here https://github.com/rycee/home-manager/pull/124

**Comment by teto** [comment]
merged
