### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by BjornMelgaard** [rycee/home-manager#116]
`error: creating symlink from ‘/etc/nixos/result.tmp-27440-1730106898’ to ‘/nix/store/ci9j6ms78lyklicjq8b6i5n3z4xh85ll-home-manager-generation’: Permission denied
`
user groups - `users wheel disk audio networkmanager`

it's blocking issue since

```
$ sudo home-manager build
No configuration file found. Please create one at /root/.config/nixpkgs/home.nix
```

**Comment by BjornMelgaard** [comment]
Resolved by adding myself to 

`nix.trustedUsers = [ "root" "@wheel" ];`

**Comment by rycee** [comment]
I think this was mainly a case of poor error reporting. The fix I made changes

```console
rycee@beta:/$ hm build
error: creating symlink from ‘/result.tmp-508-1612533748’ to ‘/nix/store/yp4phas300vg989lfcix0a5rhpjgrknq-home-manager-generation’: Permission denied
```

to

```console
rycee@beta:/$ hm build
Cannot run build in read-only directory
```

which hopefully better indicates the problem. Thanks for reporting!

**Comment by BjornMelgaard** [comment]
Thank you

**Comment by novenix** [comment]
@rycee
That was pretty accurate, thank you.
If you have sudo, you can chmod 777 /path/of/your/repo/to/build, that was my solution.
Thanks to @rycee
