### ISSUE TITLE
Firefox doesn't build anymore

### ISSUE THREAD

**Issue by luc65r** [rycee/home-manager#1166]
Since [this commit](https://github.com/NixOS/nixpkgs/commit/c51b0afd54339049db05d7854a188c1754bd9de5) in Nixpkgs, Firefox doesn't build:
```
error: Your configuration mentions firefox.icedtea, firefox.enableGoogleTalkPlugin. All plugin related options, except for the adobe flash player, have been removed, since Firefox from version 52 onwards no longer supports npapi plugins (see https://support.mozilla.org/en-US/kb/npapi-plugins).
```
The Firefox module should be updated to not set `enableGoogleTalkPlugin` and `icedtea`.

**Comment by rycee** [comment]
Thanks for the heads up! Hopefully it is sorted now.
