### ISSUE TITLE
How do I access options.json?

### ISSUE THREAD

**Issue by pmiddend** [rycee/home-manager#1173]
I realize this might be a stupid question. That being said: I've enabled the generation of `options.json` via `manual.json.enable = true;`. Where does this `options.json` reside? Can I easily, programmatically the path to this file for the current generation?

**Comment by rycee** [comment]
The file is placed at `share/doc/home-manager/options.json` inside your profile directory, e.g., `~/.nix-profile/share/doc/home-manager/options.json`. So if you mean programmatically in the sense that you want to access it from a shell script or something then that would be the place to go.

On the other hand, if you mean programmatically in the sense of accessing the file from inside your configuration then
```
"${config.home.path}/share/doc/home-manager/options.json"
```
is probably the safest way to access it.

Hope one of these methods will work for you 🙂

**Comment by pmiddend** [comment]
Excellent, thanks @rycee. How did I not detect it below `.nix-profile`. That'll work. :)
