### ISSUE TITLE
root permissions requirement needed ?

### ISSUE THREAD

**Issue by 573** [rycee/home-manager#1187]
When switching my hm environment to release-20.03 I am getting:

```
nix log /nix/store/471m63sskgg70wws9b4c8889wx9c0rm7-home-manager-path.drv
```
> created 671 symlinks in user environment
I/O error : Permission denied
I/O error : Permission denied
Failed to write XML file; For permission problems, try rerunning as root

on `hm switch`. The new generation is not built.

Is that intended ?

Full command:

```
home-manager switch -I nixpkgs=channel:nixos-20.03 -I home-manager=https://github.com/rycee/home-manager/archive/release-20.03.tar.gz --keep-failed --show-trace
```

**Comment by rycee** [comment]
Hmm, I've never seen an error like that before. When did you get the error? During activation or while building a derivation? If its during a build, which package was it that failed?

**Comment by 573** [comment]
I have edited my issue to show the log of the failing (build i guess).
@rycee I would love to investigate this further, are there diagnostics I may use ?
For now I can just tell that the config builds with release-19.09 and directly after that based on that derivation I run hm switch one more time just then with the release-20.03 channel plus hm archive as in the command above.

Maybe that is a kind of in-place update of hm not supported ?

**Comment by 573** [comment]
Closing this for now as my hm config certainly needs some overhaul.
