### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Gerschtli** [rycee/home-manager#1192]
I would like to reopen https://github.com/rycee/home-manager/issues/1187.

On my windows WSL after upgrading to 20.03 I get the following error:

```
$ home-manager build --keep-going --show-trace
these derivations will be built:
  /nix/store/az81r56xg8aqwxyp8gkr8dbxxwq54ysl-home-manager-path.drv
  /nix/store/xlaydkk3py8dalb22vhkkg3p461gdqwl-activation-script.drv
  /nix/store/kdf8wvnlzvnlx2lhh9cr157xc3zdwkvk-home-manager-generation.drv
building '/nix/store/az81r56xg8aqwxyp8gkr8dbxxwq54ysl-home-manager-path.drv'...
created 1395 symlinks in user environment
I/O error : Permission denied
I/O error : Permission denied
Failed to write XML file; For permission problems, try rerunning as root
builder for '/nix/store/az81r56xg8aqwxyp8gkr8dbxxwq54ysl-home-manager-path.drv' failed with exit code 1
cannot build derivation '/nix/store/xlaydkk3py8dalb22vhkkg3p461gdqwl-activation-script.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/kdf8wvnlzvnlx2lhh9cr157xc3zdwkvk-home-manager-generation.drv': 2 dependencies couldn't be built
error: build of '/nix/store/kdf8wvnlzvnlx2lhh9cr157xc3zdwkvk-home-manager-generation.drv' failed
```

I don't know where to start debugging this error.. Does anyone have an idea?

My system:
 - system: `"x86_64-linux"`
 - host os: `Linux 4.4.0-18362-Microsoft, Ubuntu, 16.04.6 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.3`
 - channels(tobias): `"home-manager-20.03, nixpkgs-20.03.1445.95b9c99f6d0, nur-gerschtli, unstable-20.09pre222244.22a3bf9fb9e"`
 - nixpkgs: `/home/tobias/.nix-defexpr/channels/nixpkgs`

**Comment by Gerschtli** [comment]
It seems to be caused by `home.extraProfileCommands` in `xdg.mime.enable` (https://github.com/rycee/home-manager/blob/master/modules/misc/xdg-mime.nix#L32)

**Comment by rycee** [comment]
Yeah, had a quick look at this the other day and also found that the error is likely to come from [`update-mime-database`](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/blob/d23e9fa537b84950cdb518f87e3bf1f3f2577523/src/update-mime-database.c#L844-849). You could try removing the `> /dev/null` and see what `update-mime-database` says. It might be trying to write its output to some entirely different directory from the one its told to use.

**Comment by Gerschtli** [comment]
I don't get any more output.. Exit code is 1.

**Comment by rycee** [comment]
Hmm, that's odd. Then the error message must come from some other program, the `update-mime-database` program performs some unconditionally prints before emitting that error message. E.g., https://gitlab.freedesktop.org/xdg/shared-mime-info/-/blob/d23e9fa537b84950cdb518f87e3bf1f3f2577523/src/update-mime-database.c#L3707

**Comment by carterworks** [comment]
I've also seen this error, when trying to install home manager on a clean copy of Debian on WSL1 with a new installation of `nix`. Nothing is installed on the system except the defaults, `curl`, `xz-utils`, and `nix`. 

Here's `/etc/nix/nix.conf`
```
use-sqlite-wal = false
sandbox = false
```

**Comment by orcasauce** [comment]
It seems like it's trying to write $out/share/mime/<media>/<subtype>.xml.new where `media` and `subtype` are derived from <mime-type type="media/subtype" ...> (e.g. application/xml). However, those directories are readonly:

```
$ ls -l /nix/store/f616ndhcsizhjh2rrkvjh37z4gclmf5g-home-manager-path/share/mime/x-epoc
total 4
-r--r--r-- 1 user group 2878 Dec 31  1969 x-sisx-app.xml
$ touch /nix/store/f616ndhcsizhjh2rrkvjh37z4gclmf5g-home-manager-path/share/mime/x-epoc/x-epoc.xml.new
touch: cannot touch '/nix/store/f616ndhcsizhjh2rrkvjh37z4gclmf5g-home-manager-path/share/mime/x-epoc/x-epoc.xml.new': Permission denied
```

**Comment by evanjs** [comment]
This seems to work fine on WSL 2.
Can somebody else confirm?

Happy to provide any additional info.

`Linux DOSBOOK 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 GNU/Linux`

 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.84-microsoft-standard, Kali GNU/Linux, 2020.2`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(evanjs): `"home-manager, nixpkgs-20.09pre226388.a0d7927a8c7"`
 - nixpkgs: `/home/evanjs/.nix-defexpr/channels/nixpkgs`

<details>
<summary>home-manager switch -n -v</summary>

```
/nix/store/i4fj8glr31ipdmfc5nql5in06ln3sxsf-home-manager-generation
Starting home manager activation
Sanity checking oldGenNum and oldGenPath
This is a dry run
Using Nix version: nix-env (Nix) 2.3.4
Activation variables:
  oldGenNum=5
  oldGenPath=/nix/store/i4fj8glr31ipdmfc5nql5in06ln3sxsf-home-manager-generation
  newGenPath=/nix/store/i4fj8glr31ipdmfc5nql5in06ln3sxsf-home-manager-generation
  newGenNum=6
  newGenGcPath=/nix/var/nix/gcroots/per-user/evanjs/current-home
  genProfilePath=/nix/var/nix/profiles/per-user/evanjs/home-manager
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
nix-env -i /nix/store/nja36r1i885l9x2amwlqarqis9h7wsq5-home-manager-path
Activating linkGeneration
Cleaning up orphan links from /home/evanjs
Checking /home/evanjs/.cache/.keep: exists
Checking /home/evanjs/.zshrc: exists
No change so reusing latest profile generation 5
Creating home file links in /home/evanjs
mkdir -p --verbose /home/evanjs/.cache
ln -nsf --verbose /nix/store/rrwhnpbfysr84yj5dm2h1n7jbv0al42z-home-manager-files/.cache/.keep /home/evanjs/.cache/.keep
mkdir -p --verbose /home/evanjs
ln -nsf --verbose /nix/store/rrwhnpbfysr84yj5dm2h1n7jbv0al42z-home-manager-files/.zshrc /home/evanjs/.zshrc
Activating onFilesChange
Activating reloadSystemD
User systemd daemon not running. Skipping reload.

There are 116 unread and relevant news items.
Read them by running the command 'home-manager news'.
```

</details>

Note that WSL 2 is _drastically_ different from WSL 1.
A detailed comparison between the two can be found [here](https://docs.microsoft.com/en-us/windows/wsl/compare-versions).

**Comment by rycee** [comment]
I still don't understand what is trying to write these files if it's not `update-mime-database`. Anybody know?

**Comment by GotFlojo** [comment]
So I figure it is `update-mime-database` that's having issues
I had a look at the sources and [this](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/blob/d23e9fa537b84950cdb518f87e3bf1f3f2577523/src/update-mime-database.c#L847) is the exact error message we see.

**Comment by Gerschtli** [comment]
As a quick fix, try adding `xdg.mime.enable = false;`.

**Comment by rycee** [comment]
I made a commit that adds the `-w $out/share/mime/packages` check suggested by @orcasauce. Hopefully that will resolve the problem.
