### ISSUE TITLE
fontconfig didn't create the folder

### ISSUE THREAD

**Issue by seqizz** [rycee/home-manager#1203]
Hi again,

Yesterday I've made a horrible mistake of corrupting my filesystem and had to re-install with using same configurations.

One thing I've realized with my user, after switching the new home-manager generation, didn't have `.config/fontconfig` folder, so I've copied over my backup. But later realized next generations are touching files under it:
```
lrwxrwxrwx 1 gurkan gurkan 105 Apr 29 08:42 .config/fontconfig/conf.d/10-hm-fonts.conf -> /nix/store/z0lzl9cf4lzv2h4zj23120l7ll0i7ws5-home-manager-files/.config/fontconfig/conf.d/10-hm-fonts.conf
```

After checking saw the file is defined here and wanted to ask if this is expected or not.
https://github.com/rycee/home-manager/blob/master/modules/misc/fontconfig.nix#L85

P.s. thanks for home-manager again, my whole desktop was basically ready after re-installation :smile:

**Comment by seqizz** [comment]
Forgot to mention, I have following line in the HM config:
```
fonts.fontconfig.enable = true;
```

**Comment by rycee** [comment]
Sorry to hear about the corrupted file system and glad to hear you like Home Manager 🙂

If I understand the issue correctly you have `fonts.fontconfig.enable = true` in your configuration but `home-manager switch` did not create `~/.config/fontconfig/conf.d/10-hm-fonts.conf`? Could you run `home-manager -v switch` and check if `10-hm-fonts.conf` shows up in the output?

**Comment by seqizz** [comment]
Hmm, yeah it actually shows up and whatever I delete (file or parent folder) it replaces.
Closing this one, I'll re-open if I can see something reliably failing :thinking: Sorry for the confusion.
