### ISSUE TITLE
dunst: icon_folders deprecated, use icon_path

### ISSUE THREAD

**Issue by BjornMelgaard** [rycee/home-manager#121]
https://github.com/NixOS/nixpkgs/issues/31313#issuecomment-342661682

**Comment by rycee** [comment]
Umm, from what I can see the deprecation [happened after](https://github.com/dunst-project/dunst/compare/v1.2.0...master) the current release. I'm not sure 1.2.0 (which is in both Nixpkgs unstable and 17.09) even supports `icon_path`. Maybe I'm missing something?

**Comment by BjornMelgaard** [comment]
@rycee I'm not competent in this question, you can address it to @flokli better :smile:

**Comment by flokli** [comment]
Huh, I thought this was already included in a release, which apparently isn't the case.

So this can be closed. Sorry for the noise :-)
