### ISSUE TITLE
dunst process is not picked up => two dunst processes

### ISSUE THREAD

**Issue by dermetfan** [rycee/home-manager#122]
I had changed my dunst settings but they were not picked up after `home-manager switch`. I noticed there were many dunst instances running.

After `killall dunst` and `systemctl --user start dunst`:

![2017-11-08t17 45 15 481182268 01 00](https://user-images.githubusercontent.com/4956158/32561850-8e106afa-c4ad-11e7-8b5e-59696f12d755.png)

After subsequent `home-manager switch` (which calls `notify-send` to display unread news):

![2017-11-08t17 45 35 172826192 01 00](https://user-images.githubusercontent.com/4956158/32561900-a883366a-c4ad-11e7-9d1c-a49ba5357d29.png)

As you can see, the systemd service process was not picked up and new instance was started instead.

It's not a big problem in practise but you'll have to kill the second dunst process before every `home-manager switch` to get your changes into effect. If you don't mind running two instances...

**Comment by rycee** [comment]
Yeah, this has been a thorn in my side for quite a while 🙂

Basically the session dbus in NixOS is a bit broken, at least the systemd integration part. I [investigated](https://github.com/NixOS/nixpkgs/issues/17943#issuecomment-341860410) it a while ago and as far as I can tell we cannot completely solve the problem within Home Manager. We can sort of solve it half way but unfortunately the half way solution leads to an almost unusable system. In any case, I'm aware of the issue and will see what I can do to help get it solved.

On non-NixOS systems I think it also might be broken and will try to investigate that when time permits.

**Comment by flokli** [comment]
@dermetfan there's a PR in the making to restart dunst automatically on configuration changes (currently by killing it, due to the described dbus issues):

**Comment by rycee** [comment]
I merged #533 with an alternative method of restarting (actually just killing) Dunst on configuration change.

Please give it a try and see if it works as expected now. I.e., changing the dunst configuration and doing a HM switch should cause the next notification to incorporate the updated configuration.

**Comment by flokli** [comment]
#533 fixed restarting dunst on configuration changes for me. Thanks!

**Comment by rycee** [comment]
@flokli Great, thanks! I'll close this issue for now.

@dermetfan If you still run into issues with this then please reopen.
