### ISSUE TITLE
Issue with managing files with whitespace and curly brackets

### ISSUE THREAD

**Issue by Istvan91** [rycee/home-manager#1232]
This may be some general problem with my understanding of nix (the language), but I'm unable to make this work:

```
...
home.file.".pi_templates/ats-makefile/src/{{ project }}.dats".source = "./pi-ats-makefile/src/{{ project }}.dats";
...
```

The above entry in `~/.config/nixpgs/home.nix` leads to this error:
```console
error: The option value `home.file..pi_templates/ats-makefile/src/{{ project }}.dats.source' in `/home/username/.config/nixpkgs/home.nix' is not of type `path'.
```

Basically I'm trying to manage a file with home-manager which name is literally `{{ project }}.dats`. Is there some special kind of escaping necessary, or does this just not work?

**Comment by rycee** [comment]
You'll need an absolute path. Something like
```
home.file.".pi_templates/ats-makefile/src/{{ project }}.dats".source =
  ./. + "/pi-ats-makefile/src/{{ project }}.dats";
```
might work.

**Comment by Istvan91** [comment]
Ok, I was thinking the problem was on the left side..., I did not manage to get it work with your example, but this did it for me:
```
home.file.".pi_templates/ats-makefile/src/{{ project }}.dats".source =./pi-ats-makefile/src/project.dats;
```
