### ISSUE TITLE
Recommended way to install .desktop files

### ISSUE THREAD

**Issue by piegamesde** [rycee/home-manager#1233]
What is the recommended way to put all the desktop files generated by home-manager to a place where the OS can find them? My first idea was to symlink `.local/share/applications/nix-apps` to  `.nix-profile/share/applications`. Sadly, this didn't really work because putting the files into a sub-directory causes troubles (at least with Gnome).

My second idea was to completely replace `.local/share/applications` with that symlink. This has the flaw that home-manager cannot edit anything in that folder anymore – but which it will try do, to place the `mimeapps.list` in there: `ln: failed to create symbolic link '~/.local/share/applications/mimeapps.list': Permission denied`.

Maybe the best way would be to symlink all the files in `.nix-profile/share/applications` to `.local/share/applications` one by one, so that the directory is still owned by the user. But I don't know how to do this or if it would even work.

**Comment by rycee** [comment]
I suspect you are not using NixOS and your `XDG_DATA_DIRS` environment variable isn't including `$HOME/.nix-profile/share`. If so you can try adding `targets.genericLinux.enable = true;` to your configuration and relog.

**Comment by piegamesde** [comment]
Hm, am I doing something wrong? `error: The option 'targets' defined in '~/.config/nixpkgs/home.nix' does not exist.`

Setting `XDG_DATA_DIRS` is a great idea I should have had earlier! Is there a built-in option I am missing or should I set this using session variables?

**Comment by piegamesde** [comment]
Okay, I found it, had to update home-manager first. Executing `export XDG_DATA_DIRS="$HOME/.nix-profile/share:$XDG_DATA_DIRS"` manually works fine.

However setting `targets.genericLinux.enable` and then adding `source ~/.nix-profile/etc/profile.d/hm-session-vars.sh` to `/etc/profile.d/nix.sh` does not work: it seems like it simply isn't executed.

**Comment by piegamesde** [comment]
By the magic of system initialization, shell bootstrapping and reboots, it works now.
