### ISSUE TITLE
bash.historyControl can't have multiple values

### ISSUE THREAD

**Issue by davidak** [rycee/home-manager#1243]
`programs.bash.historyControl = [ ignoredups ignorespace ];` don't work, but would be valid bash config

>A colon-separated list of values controlling how commands are saved on the history list. If the list of values includes ‘ignorespace’, lines which begin with a space character are not saved in the history list. A value of ‘ignoredups’ causes lines which match the previous history entry to not be saved. A value of ‘ignoreboth’ is shorthand for ‘ignorespace’ and ‘ignoredups’. A value of ‘erasedups’ causes all previous lines matching the current line to be removed from the history list before that line is saved. Any value not in the above list is ignored. If HISTCONTROL is unset, or does not include a valid value, all lines read by the shell parser are saved on the history list, subject to the value of HISTIGNORE. The second and subsequent lines of a multi-line compound command are not tested, and are added to the history regardless of the value of HISTCONTROL.

Source: https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html

also implement other valid options described above

**Comment by rycee** [comment]
The values must be strings, try
```
programs.bash.historyControl = [ "ignoredups" "ignorespace" ];
```

**Comment by davidak** [comment]
That works.

The manual says:

>Type: list of one of "erasedups", "ignoredups", "ignorespace"s

so i interpreted that it has to be a list with just one item

Thanks for the fast response!
