### ISSUE TITLE
How to remove previous generations?

### ISSUE THREAD

**Issue by jokogr** [rycee/home-manager#125]
`home-manager` shows the available generations, e.g.:

```
Nov  7 16:21 home-manager-8-link -> /nix/store/ikvaxmyvld9njc23zhkimxpigxji14ll-home-manager-generation
Nov  6 21:43 home-manager-7-link -> /nix/store/n0fv59zhgdbhixch7s45lg0y5n67sh5r-home-manager-generation
Nov  6 21:38 home-manager-6-link -> /nix/store/f088kkan6ij42gva9lfkv7pw55jxnzpv-home-manager-generation
Nov  6 10:54 home-manager-5-link -> /nix/store/ddiiklqlmy5mn4vqcsfamvgqqyqpcl4y-home-manager-generation
Nov  4 18:40 home-manager-4-link -> /nix/store/7cd90r45d2jrd0yki9npz0wjx3k5fzn7-home-manager-generation
Nov  4 18:19 home-manager-3-link -> /nix/store/1k6fv7vyki88l3afidpf29r98h174il1-home-manager-generation
Nov  4 18:10 home-manager-2-link -> /nix/store/13md526sfs3h2i6brlysywqi2m2gfz8y-home-manager-generation
Nov  4 18:02 home-manager-1-link -> /nix/store/s3qcfgp2zwsqc6p7zgsr98ka69ni46mi-home-manager-generation
```

Is there a command to erase some of them?

**Comment by rycee** [comment]
Unfortunately the home-manager tool doesn't yet have a command that deletes specific generations. It should be easy to implement so I might do that shortly. Personally, however, I've never felt a need for such a command since old Home Manager generations will be collected by `nix-collect-garbage`:

```console
$ home-manager generations | tail
Oct  4 20:25 home-manager-439-link -> /nix/store/55xgp265g4238nb4ydrqfndkzpp18500-home-manager-generation
Oct  4 20:24 home-manager-438-link -> /nix/store/c803732r9fxkikir5cabc0s2qmxgq2cz-home-manager-generation
Oct  4 20:19 home-manager-437-link -> /nix/store/wd38hiqvn7lkqz9jlh2n669k5byirgf8-home-manager-generation
Oct  4 20:17 home-manager-436-link -> /nix/store/5zl8l0xcm05f0049rldn8sw2mydvnrl6-home-manager-generation
Oct  4 18:52 home-manager-435-link -> /nix/store/iaz0lbhkcb2n4hbpvjvas8czs5yfphpy-home-manager-generation
Oct  4 18:50 home-manager-434-link -> /nix/store/w6l4d41fvxsdwh9b52d1m9ngnb6qhvrw-home-manager-generation
Oct  4 14:28 home-manager-433-link -> /nix/store/h4z9vma27pa07pi3hqa5nabij1lpj4jw-home-manager-generation
Oct  4 12:37 home-manager-432-link -> /nix/store/dnkvcrggwfrkaamv2ip9ringnylv7x9z-home-manager-generation
Oct  4 12:05 home-manager-431-link -> /nix/store/8igwvzikmv3ri98ky4y5pl47bcbpy4wq-home-manager-generation
Oct  3 01:14 home-manager-430-link -> /nix/store/i6sx8bglkr3rl8cgw1fh46nv5h5f4av8-home-manager-generation
```

In any case, if you want to immediately remove a specific generation then, for now, you have to manually delete the symlink `/nix/var/nix/profiles/per-user/$USER/home-manager-XYZ-link` where `XYZ` is the generation number. Just remember to _never_ delete the latest generation!

**Comment by rycee** [comment]
The latest home-manager now has a `remove-generations` command. See `home-manager -h` for usage.

Thanks for reporting and feel free to reopen the issue if the command doesn't work as you expect!

**Comment by Narice** [comment]
nix-collect-garbage doesn't collect anymore old home-manager generations.
Would it be possible to add an option to the remove generations command to delete all old generations ?
something like:
`home-manager remove-generations old` or `home-manager remove-generations +1`
that would be really good as old generations are taking a bunch of space
I know that it is possible to do `expire-generations "-1 days"` or something but if I know that my system is stable after an upgrade, I would like to have an easy way to create some space ;)

**Comment by Narice** [comment]
oh, woops, you can do `home-manager expire-generations "now"`
This might be a bit hacky, but it works! :D
