### ISSUE TITLE
Seems that lorri service hasn't been properly created 

### ISSUE THREAD

**Issue by nodew** [rycee/home-manager#1253]
try to enable lorri by followed config
```
services.lorri.enable = true
```
after build
```shell
systemctl list-unit-files | grep lorri
```
I don't find any `lorri.service` in my system.
Here is the my config, [https://github.com/nodew/nix-home](https://github.com/nodew/nix-home)

**Comment by peterhoeg** [comment]
>   commond systemctl list-unit-files | grep lorri.

systemctl --user list-unit-files | grep lorri

**Comment by nodew** [comment]
```shell
$ systemctl --user list-unit-files | grep lorri
lorri.service                  linked
lorri.socket                   enabled
```
Thanks @peterhoeg
