### ISSUE TITLE
openDefaultPorts no longer valid for syncthing service

### ISSUE THREAD

**Issue by codygman** [rycee/home-manager#1266]
Re-enabling syncthing on a machine I got:

```shell
error: The option `services.syncthing.openDefaultPorts' defined in `/home/cody/hci/nixpkgs/home.nix' does not exist.
(use '--show-trace' to show detailed location information)
```

I recall a discussion or explanation of this somewhere, but [couldn't seem to find it in the issues](https://github.com/rycee/home-manager/search?q=openDefaultPorts&type=Issues). I think this is something that we should now set at the system level?

Maybe this was never a valid home-manager option and I just had incorrect commented code.

**Comment by rycee** [comment]
I think you have it confused with NixOS, which does have [`services.syncthing.openDefaultPorts`](https://nixos.org/nixos/manual/options.html#opt-services.syncthing.openDefaultPorts). As far as I recall there has never been such an option in Home Manager.
