### ISSUE TITLE
'home-manager/home-manager/home-manager.nix' was not found

### ISSUE THREAD

**Issue by thraxil** [rycee/home-manager#1267]
I've installed home-manager on a NixOS (20.03) machine. Created `~/.config/nixpkgs/home.nix` with:

```
{ pkgs, ... }:
  {
    home.packages = [
      pkgs.zsh
    ];
    programs.home-manager = {
      enable = true;
    };
  }
```

When I run `home-manager switch`, I get:

```
error: file 'home-manager/home-manager/home-manager.nix' was not found in the Nix search path (add it using $NIX_PATH or -I)
error: file 'home-manager/home-manager/home-manager.nix' was not found in the Nix search path (add it using $NIX_PATH or -I)
/home/thraxil/.nix-profile/bin/home-manager: line 115: /tmp/home-manager-build.g5ojUtbBWB/news-info.sh: No such file or directory
```

There is one generation:

```
$ home-manager generations
2020-05-24 11:43 : id 1 -> /nix/store/nny0wvx0sc4d1h79n6y28px9p7icfgrr-home-manager-generation
```

I can't uninstall either:

```
$ home-manager uninstall
This will remove Home Manager from your system.
Really uninstall Home Manager? [y/n] y
Switching to empty Home Manager configuration...
error: file 'home-manager/home-manager/home-manager.nix' was not found in the Nix search path (add it using $NIX_PATH or -I)
error: file 'home-manager/home-manager/home-manager.nix' was not found in the Nix search path (add it using $NIX_PATH or -I)
/home/thraxil/.nix-profile/bin/home-manager: line 115: /tmp/home-manager-build.CmjOsZgBIy/news-info.sh: No such file or directory
```

Any idea on what's wrong and what I can do to fix it? I'm pretty new to Nix

**Comment by rycee** [comment]
How did you install it? Do you have a `home-manager` channel?

**Comment by thraxil** [comment]
I just added `home-manager` to my package list in `/etc/nixos/configuration.nix` and did `nixos-rebuild switch`. I haven't modified anything with channels yet.

**Comment by thraxil** [comment]
OK, I did the `export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH` as mentioned in the docs (I skipped because it says "On non-NixOS you may have to add ..." and I *am* on NixOS).

That seems to have fixed it.

**Comment by rycee** [comment]
I guess on NixOS you still need that if you use a shell that does not source `/etc/profile` because that should source the set-environment file which adds the user channels:
```console
$ cat /etc/set-environment | grep nix-defexpr
if [ -e "$HOME/.nix-defexpr/channels" ]; then
  export NIX_PATH="$HOME/.nix-defexpr/channels${NIX_PATH:+:$NIX_PATH}"
```

**Comment by thmzlt** [comment]
Just another data point that my (previously working) installation of home-manager stopped working on NixOS with this error.

**Comment by datakurre** [comment]
I followed the README on fresh macOS Catalina installation and also got this
```
atsoukka@myjyu-mbp ~ % nix-shell '<home-manager>' -A install

Creating initial Home Manager generation...

error: value is a function while a set was expected, at /nix/store/gnkd9i59pswalkflb647fnjjnxgyl1n9-nixpkgs-20.09pre228453.dcb64ea42e6/nixpkgs/lib/modules.nix:199:27
(use '--show-trace' to show detailed location information)
error: value is a function while a set was expected, at /nix/store/gnkd9i59pswalkflb647fnjjnxgyl1n9-nixpkgs-20.09pre228453.dcb64ea42e6/nixpkgs/lib/modules.nix:199:27
(use '--show-trace' to show detailed location information)
/nix/store/ix8qg0ci02863sj9lhdpw7ldffasj7ky-home-manager/bin/home-manager: line 127: /var/folders/w3/qzfyf9n50_z456zrdp82zkb00000gn/T/home-manager-build.Q4srLhRlJn/news-info.sh: No such file or directory

Uh oh, the installation failed! Please create an issue at

    https://github.com/rycee/home-manager/issues

if the error seems to be the fault of Home Manager.
atsoukka@myjyu-mbp ~ % nix-channel --list
home-manager https://github.com/rycee/home-manager/archive/master.tar.gz
nixpkgs https://nixos.org/channels/nixpkgs-unstable
atsoukka@myjyu-mbp ~ % echo $NIX_PATH
/Users/atsoukka/.nix-defexpr/channels
```

**Comment by 573** [comment]
@rycee could you reopen ?

I am on non-NixOS and I am trying to just have my hm config checked using suggested

```
$ [ -e "$HOME/.nix-defexpr/channels" ] &&  export NIX_PATH="$HOME/.nix-defexpr/channels${NIX_PATH:+:$NIX_PATH}"
$ nix-instantiate --eval -E "<home-manager/home-manager/home-manager.nix>" --argstr confPath ~/.config/nixpkgs/home.nix --argstr confAttr "" -A activationPackage.outPath
```

instead what I am getting is:

>error: file 'home-manager/home-manager/home-manager.nix' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:1

**Comment by 573** [comment]
To answer myself

```
$ nix-instantiate --eval -E "<home-manager/home-manager/home-manager.nix>" --argstr confPath ~/.config/nixpkgs/home.nix --argstr confAttr "" -A activationPackage.outPath -I home-manager=https://github.com/rycee/home-manager/archive/release-20.03.tar.gz; 
```

(pointers [here](https://github.com/rycee/home-manager/issues/263#issuecomment-388497219) and [there](https://github.com/rycee/home-manager#installation)). I am using [this approach](https://discourse.nixos.org/t/home-manager-installation-questions/7204/5) to install hm.

**Comment by jonascarpay** [comment]
I also had this issue on NixOS.
I solved it by adding a `home-manager` channel instead of relying on the `programs.home-manager.path` variable or `HM_PATH` environment variable.

**Comment by iharh** [comment]
I have the same issue using home-manager with flakes (https://github.com/iharh/nixcfg).
When I rebuild my system with "nixos-rebuild --flake ." - everyting is fine.
When I try to do "HOME_MANAGER_CONFIG=./hm/iharh.nix home-manager build" - I get this error.
Please, suggest how to fix this for my case (of using home-manager via flakes)
