### ISSUE TITLE
home-manager + zfs rollbacks

### ISSUE THREAD

**Issue by shadowrylander** [rycee/home-manager#1276]
### Issue description

Not an issue persay, but just asking for advice: would using this for home directory management and zfs for [proper] rollback capabilities work, and are there any caveats to said setup I should know about? I'm planning to write my own python script integrating the two, and was wondering whether it would be feasible.

**Comment by Kloenk** [comment]
`home-manager` is just creating the links. If you recreate the links with a ZFS-snapshot, you may run into trouble if the garbage collector of nix has run.

**Comment by shadowrylander** [comment]
Fair enough; but then two questions:
1. Will the garbage collector delete the links in the snapshots?
2. Is recreating the links a bad idea because source files may have disappeared in the meantime?

**Comment by Kloenk** [comment]
I never used zfs. So take my answer with care.

1. The link itself should stay in the snapshot, but
2. the source file under /nix/store would be removed, if you don't include that in your snapshot (I don't think that a snapshot of /nix/store is a good idea)

**Comment by shadowrylander** [comment]
Ah, so files managed by home-manager are stored in the nix store... Probably should've seen that coming. Is there a particular directory under the nix store I could possibly snapshot, used for the home-manager storage?

**Comment by Kloenk** [comment]
There are 2 symlinkFarm folders per generation. But the still only contain symlinks, and the path changes per generation

**Comment by shadowrylander** [comment]
Ah well. Might stick to `YADM`, then, for the moment. Thanks anyway, though! Closing now!
