### ISSUE TITLE
dircolors module does not work with oh-my-zsh module

### ISSUE THREAD

**Issue by caleb** [rycee/home-manager#1279]
### Issue description

The `dircolors` module does not play well with the `oh-my-zsh` module.

The `dircolors` module uses `initExtra` to inject its `$HOME/.zshrc` code, but this code is injected after loading `oh-my-zsh`. The issue is that `oh-my-zsh` requires the `LS_COLORS` environment variable to be present before setting up the shell aliases that enable colors by default.

A working solution is to use the `initExtraBeforeCompInit` setting of `zsh` instead of `initExtra` to inject the `dircolors` code as early as possible.

I just started using home-manager a couple days ago, so I though I would open a bug report before trying to submit a PR.

#### Maintainer CC

@JustinLovinger 

#### Technical details

```
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.4.0, macOS 10.15.4`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.4`
 - channels(caleb): `"home-manager, nixpkgs-20.09pre226586.571212eb839"`
 - nixpkgs: `/Users/caleb/.nix-defexpr/channels/nixpkgs`
```

**Comment by JustinLovinger** [comment]
@caleb Makes sense. I don't see any reason `dircolors` shouldn't be run before `compinit`. I'll make a pull request with the changes.

In the meantime, you can disable`dircolors.enableZshIntegration` and source it yourself.

**Comment by JustinLovinger** [comment]
This issue should be fixed and safe to close.

**Comment by caleb** [comment]
Thanks! It works over here.
