### ISSUE TITLE
i3: generate an alternate file

### ISSUE THREAD

**Issue by teto** [rycee/home-manager#128]
my i3 config is kinda big, I have a script to generate it. While I can see the appeal of having HM generates parts of it, I would rather keep most of my current config and include a little part generated by HM. It also makes incremental switching easier (extraConfig is nice for small files but once it gets bigger, as you lose syntax coloring/completion it makes it harder to use). 
I see 2 possibilities: 
1/ the i3 modules could concat several files via importConfigs which IMO would be very helpful
2/ or setup the module to generate an other file than XDG_CONFIG_HOME config

Here is what my current build_config.sh does:
```
if [ $(i3 --version | grep -c gaps) -gt 0 ]
then 
	list="$folder/config.gaps "
fi

list="${list:-} $folder/config.header $folder/config.xp $folder/config.audio  $folder/config.colors $folder/config.mediakeys $folder/filters.config $folder/config.main "
cat $list > "$folder/config"
```
Option 1 has my preference, it could replace advantageously my script as it could check for i3gaps and include the config conditionnally etc.

**Comment by uvNikita** [comment]
You can keep your configuration files as they are and just use `builtins.readFile` nix function to put them into `extraConfig` option. You could also check with nix if 3-gaps package is currently in use and conditionally append `$folder/config.gaps` file.

**Comment by teto** [comment]
I had to delete the original config via config=null otherwise it looks good. Didnùt think of readFile thanks 
```
  i3extraConfig = lib.concatStrings [
    (builtins.readFile ../i3/config.header)
    (builtins.readFile ../i3/config.main)
    (builtins.readFile ../i3/config.mediakeys)
    (builtins.readFile ../i3/config.xp)
    (builtins.readFile ../i3/config.audio)
    (builtins.readFile ../i3/config.colors)
  ];

  xsession.windowManager.i3 = {
    enable = true;
    extraConfig = i3extraConfig;
    config = null;
  };
```
