### ISSUE TITLE
i3: don't assume no-startup-id

### ISSUE THREAD

**Issue by nico202** [rycee/home-manager#129]
https://github.com/rycee/home-manager/blob/d2572315ca14f225ff3b41c03b0c0b670dffa3a8/modules/services/window-managers/i3.nix#L483

Hi, I was asking why do you assume that every command wants "no-startup-id". I'd have a bool to set it up

thanks, nicolò

**Comment by uvNikita** [comment]
Good point, created PR which fixes that. Thank you for the feedback!
