### ISSUE TITLE
Document how to use permittedInsecurePackages

### ISSUE THREAD

**Issue by epigramengineer** [rycee/home-manager#1290]
### Issue description

I can't add:

```
permittedInsecurePackages = [
  "p7zip-16.02"
];
```

to my .config/nixpkgs/config.nix. Can you document how it's supposed to work with home manager?

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.19.107, NixOS, 20.03.2015.e7752db2fb6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.5`
 - channels(root): `"nixos-20.03.2015.e7752db2fb6"`
 - channels($USER): `"nixpkgs-20.09pre226586.571212eb839"`
 - nixpkgs: `/home/$USER/.nix-defexpr/channels/nixpkgs`
```

**Comment by rycee** [comment]
Does you configuration include anything under [`nixpkgs.config`](https://rycee.gitlab.io/home-manager/options.html#opt-nixpkgs.config)? If so then the `~/.config/nixpkgs/config.nix` will not be used. You could, instead try to add
```
nixpkgs.config.permittedInsecurePackages = [ "p7zip-16.02" ];
```
to your configuration.

**Comment by epigramengineer** [comment]
Ah awesome - I did not realize you could just put the config.nix stuff inside the home manager configuration file!

Thanks :)
