### ISSUE TITLE
~/.nixpkgs should be ~/.config/nixpkgs

### ISSUE THREAD

**Issue by therealpxc** [rycee/home-manager#13]
[Right](https://github.com/NixOS/nixpkgs/commit/9d6a55aefd771f047d2aa3085c9a3f8a2f452333)?

I've symlinked them for now. This is hardly a showstopper. (I'm not sure what fallback/compatibility behavior you want, which is why I'm submitting just an issue and not a PR.)

**Comment by rycee** [comment]
Thanks for the report! Yeah, you are absolutely right. I will change the preferred default to `~/.config/nixpkgs` with fallback to `~/.nixpkgs`.

**Comment by rycee** [comment]
Pushed a branch [fix/default-conf-dir](https://github.com/rycee/home-manager/tree/fix/default-conf-dir) that hopefully should resolve this. Please give it a try and see if it works as you expect.

**Comment by therealpxc** [comment]
I won't get a chance to play with it until tomorrow evening, but I'll let you know how it works. Thanks! :-)

**Comment by rycee** [comment]
@therealpxc Have you had a change to try this out? I've been using the fix/default-conf-dir branch for some time now and feel pretty happy with it but additional confirmation would of course still be welcomed. Regardless, I'll merge this weekend.

**Comment by therealpxc** [comment]
I've been extraordinarily busy IRL lately, and so I haven't. I ended up getting sucked into refactoring my whole NixOS config so that I can more easily use pieces of it with tools like home-manager and [nix-darwin](https://github.com/LnL7/nix-darwin), then various things happened in my life that delayed me from working on that for about a week.

I will try to get to this within the next couple days, because that's when I expect for that work to be done. Sorry for playing ding-dong-ditch with you here. :-(

**Comment by rycee** [comment]
No worries! I've merged the branch since I've successfully used it for some time now. Of course I still would like to hear whether it as you expect (which is why I'll leave this issue open) but feel free to do so and close the issue at your own pace.

In any case, many thanks for raising this issue, I would have left this problem lingering for longer without you taking the time to report it!

**Comment by rycee** [comment]
I think it is safe to close this issue since a number of people are now running home manager with configuration taken from `~/.config`.
