### ISSUE TITLE
Symlinks are writeable

### ISSUE THREAD

**Issue by fzakaria** [rycee/home-manager#1307]
### Issue description

Seeing a weird problem on my machine.
Looks like the symlinks are writeable by my user however the actual store contents is only readable.

```
 ls -l ~/.zshrc
lrwxrwxrwx 1 fmzakari primarygroup 69 Jun  6 15:23 /home/fmzakari/.zshrc -> /nix/store/mqn789lgj79fvhdahgabshs2093qi5b5-home-manager-files/.zshrc

ls -l /nix/store/mqn789lgj79fvhdahgabshs2093qi5b5-home-manager-files/.zshrc
lrwxrwxrwx 1 fmzakari primarygroup 53 Dec 31  1969 /nix/store/mqn789lgj79fvhdahgabshs2093qi5b5-home-manager-files/.zshrc -> /nix/store/sdx1f2sxvdy5nbc9s22a3nmpa8aryf8q-hm_.zshrc

ls -l /nix/store/sdx1f2sxvdy5nbc9s22a3nmpa8aryf8q-hm_.zshrc
-r--r--r-- 1 fmzakari primarygroup 2998 Dec 31  1969 /nix/store/sdx1f2sxvdy5nbc9s22a3nmpa8aryf8q-hm_.zshrc
```

* I'm also told that the owned user shouldn't be my user.

My home-manager setup is at https://github.com/fzakaria/nix-home
My workflow is:

1. Git clone the directory (anywhere)
2. home-manager switch --file ./home.nix

### Machine

Debian based distro
(#1 SMP Debian 5.5.17-1rodete4 (2020-05-08 > 2018))

PS: I find that much simpler than putting it in ~/.config/nix

**Comment by peterhoeg** [comment]
That's how symlinks work:

```
$ ls -la
total 8
drwxr-xr-x  1 peter users   20 Jun  7 13:22 .
drwx------+ 1 peter users 2004 Jun  7 13:22 ..
lrwxrwxrwx  1 peter users    7 Jun  7 13:22 foo -> woot.md
-rw-------  1 peter users   29 Jun  7 13:22 woot.md
```
