### ISSUE TITLE
mail management

### ISSUE THREAD

**Issue by teto** [rycee/home-manager#132]
Mail management is my biggest nightmare on linux. So many software to configure; most of the time with redundant data, which becomes painful with several accounts. 
Thunderbird is easy to configure/use but it has numerous flaws and I prefer handling mails via astroid/notmuch/alot/offlineimap setup (never got to sync notmuch tags across computers but that could add yet another soft). 
That's where nix should shine.
I imagine having a central list of accout sets that would be used to generate "X" mail program configs so that you need to change it only once instead of "X".
There seems to be a nixos project + that one https://github.com/r-raymond/nixos-mailserver but they seem more full fledged and ignore notmuch/astroid/notmuch I believe. 
I got hit by the problem when deploying my config on a new machine. Everytime everything works but the mail so I started writing some code but maybe it's best to have some feedback first.

**Comment by rycee** [comment]
Indeed, I think this is a very nice idea! Being able to set up mail stuff once and end up with a nice integrated setup across multiple programs would be very cool.

**Comment by flokli** [comment]
I'm also very much interested into this.

I currently use some combination of `msmtp` to send, and `isync`/`mbsync` to sync, together with `notmuch` and `afew`, to do sorting and tagging afterwards.

At least the first part, sending and syncing, would profit a lot from a generic 'account' abstraction.

**Comment by teto** [comment]
I have started some notmuch/msmtp/alot generation here https://github.com/teto/home-manager/tree/notmuch . I've targeted the moving part of the config; I would be interested in seeing an mbsync module. The ,qin qbstrqction is in home-environment: I add things on the go; when required.

**Comment by teto** [comment]
project is well engaged. closing
