### ISSUE TITLE
i3: add missing options

### ISSUE THREAD

**Issue by nico202** [rycee/home-manager#135]
@uvNikita Hi, I'm moving my i3 configuration (that was something like 600+ lines) to the home-manager module.
Instead of opening multiple issues, I'll add to this one the things I'm missing
For now I miss the option: 
`hide_edge_borders none|vertical|horizontal|both|smart`
and
`mouse_warping output|none`.

I could use the extraConfig option, but since there are that many (like window.titlebar) adding the few missing might be feasible. Let me know.

Also, I'm missing the `bindcode` (similar to bindsym but expects a keycode instead of a key combination).

Last, it seems to miss also the `for_window` option

PS: how do I disable the i3bar (to use polybar instead)? -- answering to myself: set it to empty list

I'm sorry to bother you, but except for those I find this nix config easier to maintain than the i3 one
Thanks!

edit: changed the config file length estimation, I was a bit off XD
edit: add question on bar

**Comment by flokli** [comment]
If you just want to use `for_window` to enable floating, refer to `config.floating.criteria`.

There are other options also missing, not sure if it's feasible to add all of them:

 - `workspace_auto_back_and_forth`
- `popup_during_fullscreen`

**Comment by uvNikita** [comment]
Thank you for the input! I've created PR https://github.com/rycee/home-manager/pull/142 that add some of the mentioned options. I could find place for `hide_edge_borders`, `mouse_warping`, `bindcode` and `for_window` options, but not for `workspace_auto_back_and_forth` and `popup_during_fullscreen` for now. Let me know what you think about the placements and names of the new options and if you have any ideas on where to put the missing ones.

**Comment by nico202** [comment]
Thanks. Yes having some option in the extraConfig is not a problem, but bindcode and for_windows are so similar to bindsym and assign that was strange not to see them.

However, it's nice the option workspace_auto_back_and_forth, didn't know about it

@flokli I'm using for_window for windows that change their class/title after their creation (ie, I had problems with assign used on gimp)

**Comment by uvNikita** [comment]
I pushed changes to master: https://github.com/rycee/home-manager/commit/177565567e793e5483290dbb5b9487c3ce15ca60.
