### ISSUE TITLE
Where the "imports" is defined and used?

### ISSUE THREAD

**Issue by nodew** [rycee/home-manager#1350]
When I import multiple module with `imports`, like
```
{
  imports = [
    ./a.nix,
    ./b.nix
  ]
}
```
I want to pass some parameter to the modules, I don't find out how `home-manager` handle the imports declaration, could any one help figure it out?

**Comment by rycee** [comment]
Either

1. change `./a.nix` to `(import ./a.nix param1 param2)` add add corresponding function arguments in the `a.nix` file, or

2. add `_module.args.param1 = "whatever";` to the root configuration and retrieve the `param1` argument in the module's argument attribute set. I.e., change `{ pkgs, ... }:` to `{ pkgs, param1, ... }:` at the beginning of `a.nix`.
