### ISSUE TITLE
Request Backport: Flutter

### ISSUE THREAD

**Issue by rschulman** [rycee/home-manager#1352]
### Issue description

I was wondering if there was any possibility to get the flutter packages currently in unstable backported into 20.03. Per the readme, I'm opening a quick issue.

Thanks!

#### Technical details

```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.44, NixOS, 20.03.2107.70717a337f7 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(ross): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by cole-h** [comment]
I think you want to file this in https://github.com/NixOS/nixpkgs -- home-manager doesn't deal with channels (unstable and 20.03) at all, rather only configuration for some packages and services.

**Comment by rycee** [comment]
Yep, definitely open an issue in Nixpkgs and CC the package maintainer, @babariviere.

**Comment by rschulman** [comment]
Dangit! Sorry for the noise everyone.

**Comment by rycee** [comment]
No worries. I might be worth noting that it's pretty easy to install packages from Nixpkgs unstable even if you are running a stable NixOS version. For example,

```console
$ nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs-unstable
$ nix-channel --update
$ nix-env -f '<nixpkgs-unstable>' -iA flutter
```

**Comment by cole-h** [comment]
There is also this wiki article that is frequently linked on IRC (usually courtesy of the bot's `,unstable` command): https://nixos.wiki/wiki/FAQ#How_can_I_install_a_package_from_unstable_while_remaining_on_the_stable_channel.3F
