### ISSUE TITLE
wayland.windowManager.sway.config.bars has weird defaults

### ISSUE THREAD

**Issue by billop** [rycee/home-manager#1361]
### Issue description
My bar configuration for sway is very simple:
```
bar {
    position top
    swaybar_command waybar
}
```
But setting this with home-manager as such:
```
bars = [
  {
    position = "top";
    command = "waybar";
  }
];
```
Results in:
```
bar {

  font pango:monospace 8
  mode dock
  hidden_state hide
  position top
  status_command /nix/store/h7s6i9q1z5fxrlyyw5ls8vqxhf5bcs5a-i3status-2.13/bin/i3status
  swaybar_command waybar
  workspace_buttons yes
  strip_workspace_numbers no
  tray_output primary
  colors {
    background #000000
    statusline #ffffff
    separator #666666
    focused_workspace #4c7899 #285577 #ffffff
    active_workspace #333333 #5f676a #ffffff
    inactive_workspace #333333 #222222 #888888
    urgent_workspace #2f343a #900000 #ffffff
    binding_mode #2f343a #900000 #ffffff
  }

}
```

The defaults don't really make sense. `i3status` should not be pulled and used for swaywm. And in the usecase of waybar, all the other settings are unnecessary.

#### Maintainer CC

@alexarice 
#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.48, NixOS, 20.03.2351.f8248ab6d9e (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.6`
 - channels(root): `"nixos-20.03.2351.f8248ab6d9e"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by alexarice** [comment]
`i3status` can be used with `swaybar` I believe, which is why that is there, however I see your point that all these options are irrelevant in this case. It looks a lot of these should really be null by default but this could break current configs. @rycee are non-backward compatible changes allowed?

**Comment by rycee** [comment]
Defaults should be changed with a state version guard. The changed defaults can be active for state version ≥20.09.

**Comment by fooker** [comment]
Can we change the types to allow `null` at least without changing the defaults? This would allow to disable settings explicitly without breaking existing changes, right?

**Comment by alexarice** [comment]
> Can we change the types to allow `null` at least without changing the defaults? This would allow to disable settings explicitly without breaking existing changes, right?

You can already supply an empty list to `bars`, I'm not sure if this is what you mean

**Comment by billop** [comment]
> Can we change the types to allow `null` at least without changing the defaults? This would allow to disable settings explicitly without breaking existing changes, right?

Whether or not this is implemented, this doesn't fix the issue of weird defaults. I think the defaults should mostly be nulls or empty lists (which is funnily enough literally what null means).

**Comment by alexarice** [comment]
I agree the defaults are very weird. My feeling is that the defaults should just be changed and if it breaks someones config then so be it (I sort of doubt anyone is relying on these defaults)

**Comment by rycee** [comment]
I haven't been following but w.r.t changing defaults that's completely fine but ideally done with a state version guard. So starting from state version 20.09, for example, the new default applies but existing configurations for state version 19.09 or 20.03, for example, will continue to work. Such a change should also go into the release notes for the 20.09 release in the section of changes tied to a state version.

**Comment by alexarice** [comment]
Wouldn't this mean that anyone that installed nixos before now would get the weird defaults or is this state version separate from the nixos state version?

**Comment by rycee** [comment]
Yeah, I'm referring to the [`home.stateVersion`](https://rycee.gitlab.io/home-manager/options.html#opt-home.stateVersion) option in Home Manager which is indeed completely separate from the NixOS

**Comment by alexarice** [comment]
I've just taken a look at the code for this. The `bars` code is shared with i3 and I believe the defaults were originally just pulled from there though it should be fine to change this. I am not sure if the i3 module has a maintainer we could ping to make sure.

 I suggest that the defaults in bar are changed to be nullable and the default for the `bars` field includes all of these fields as they are now. This way if the config doesn't touch the bar then they get the default one but none of these defaults will affect your custom bars. I can put together a PR for this at some point (probably over the weekend) if no one else has a burning desire to make one.
