### ISSUE TITLE
Using NixOS modules possible / foreseen in home-manager config ?

### ISSUE THREAD

**Issue by 573** [rycee/home-manager#1362]
### Question only

Would it be possible to just import or callPackage [nixos binfmt.nix module](https://github.com/NixOS/nixpkgs/blob/f82e9b88c983b5fad78b35ec57985e9609c416b0/nixos/modules/system/boot/binfmt.nix) in my config to enable building aarch64 packages [via qemu](https://nixos.wiki/wiki/NixOS_on_ARM#Compiling_through_QEMU) in my non-NixOS system ?

**Comment by rycee** [comment]
No, Home Manager can only do things that you as a regular user can. It cannot change system level configurations.

Also, the modules in NixOS are almost universally incompatible with Home Manager. So even if HM could change system configurations you wouldn't be able to just import the NixOS module.

I would recommend changing the system configuration if you are running NixOS and perhaps manually set up a build environment inside a virtual machine.
