### ISSUE TITLE
Dconf mkTuple with negative numbers

### ISSUE THREAD

**Issue by gvolpe** [rycee/home-manager#1363]
We can currenlty add some tuples using `lib.hm.gvariant.mkTuple`. However, it doesn't seem possible to express tuples of negative numbers, as the following legit case shows:

```init
[org/gnome/epiphany/state]
is-maximized=false
window-position=(-1, -1)
window-size=(1024, 768)
```

Because the following Nix code is illegal:

```nix
{ lib, ... }:

let
  mkTuple = lib.hm.gvariant.mkTuple;
in
{
  "org/gnome/epiphany/state" = {
    "is-maximized" = false;
    "window-position" = mkTuple [ -1 -1 ]; # illegal code
    "window-size" = mkTuple [ 1024 768 ]; # this is fine
  };
}
```

The workaround is to wrap them in quotes, though, that seems to generate invalid dconf configuration.

Any suggestions? I'm building a tool to that generates the correct `dconf.nix` from a `dconf` file and so far this is the only issue I've found.

Thanks a lot for making Home Manager, I love it! :heart:

**Comment by rycee** [comment]
Try `mkTuple [ (-1) (-1) ]`.

**Comment by gvolpe** [comment]
Wow, that was really quick! Thanks a lot, seems to work :)

**Comment by rycee** [comment]
No worries, glad it worked out 👍

**Comment by gvolpe** [comment]
I just made the repo public, in case it's of interest to anyone. It works with a lot of options I tested but there might be some edge cases I'm missing: https://github.com/gvolpe/dconf2nix
