### ISSUE TITLE
[Question] Replicating home-manager environment by copying the closure

### ISSUE THREAD

**Issue by alexvorobiev** [rycee/home-manager#1367]
I want to be able to replicate my home-manager environment to other computers which may or may not have internet access by copying the closure (nix-copy-closure or nix-store --export/--import). Is `home-manager-path` the right derivation to use for the closure? How do I recreate the symlinks to the dot files?

**Comment by rycee** [comment]
You'll want the `home-manager-generation` derivation, which is built by `home-manager build` or instantiated by `home-manager instantiate`. Inside the build output you'll find an activation script, you can run that.

**Comment by alexvorobiev** [comment]
That worked, thank you!
