### ISSUE TITLE
Patching `home-manager` modules?

### ISSUE THREAD

**Issue by evanrelf** [rycee/home-manager#1375]
I'd like to use modules provided by `home-manager`, but make some of my own tweaks. 

For example, I'd like to not add `kitty` to `home.packages` when I have `programs.kitty.enabled = true` since I'm on macOS and I prefer to use kitty from Homebrew Cask.

I'd like to use patches to avoid vendoring the modules entirely. However my attempts so far have not worked. `home-manager` seems to somehow ignore the modified source code I've provided.

Am I doing something wrong here? I don't understand why `home-manager` isn't using my patched version of the modules. Or is there a better way of making these kinds of modifications to modules?

---

<details>
<summary>Overlay to modify the <code>home-manager</code> derivation from Nixpkgs to use patched source code</summary>

(If there's a better way of applying patches to source code and persisting that patched source code in the Nix store, I'd love to know)

```nix
self: super:

{
  home-manager =
    let
      originalSource =
        super.fetchFromGitHub {
          name = "home-manager-source";
          owner = "rycee";
          repo = "home-manager";
          rev = "7f7348b47049e8d25fb5b98db1d6215f8f643f0d";
          sha256 = "1s8j8h42k354xzwlqizbzxlqvsagx7yrxl20qfxgxmx522ajw63p";
        };
      patchedSource =
        super.stdenv.mkDerivation {
          name = "home-manager-source-patched";
          src = originalSource;
          phases = [ "unpackPhase" "patchPhase" "installPhase" ];
          installPhase = "cp -r . $out";
          patches = [
            ../patches/home-manager-kitty.patch
          ];
        };
    in
      super.home-manager.overrideAttrs (old: {
        version = "HEAD";
        src = patchedSource;
      });
}
```

</details>

<details>
<summary>Patch to remove <code>kitty</code> from <code>home.packages</code></summary>

`patches/home-manager-kitty.patch`

```patch
diff --git a/modules/programs/kitty.nix b/modules/programs/kitty.nix
index 313a0bf..6bd651b 100644
--- a/modules/programs/kitty.nix
+++ b/modules/programs/kitty.nix
@@ -73,7 +73,7 @@ in {
   };
 
   config = mkIf cfg.enable {
-    home.packages = [ pkgs.kitty ] ++ optionalPackage cfg.font;
+    home.packages = optionalPackage cfg.font;
 
     xdg.configFile."kitty/kitty.conf".text = ''
       # Generated by Home Manager.
```

</details>

<details>
<summary>Nix shell made for running a pinned <code>home-manager</code> with specific settings</summary>

```nix
let
  pkgs = import ./nixpkgs.nix { overlays = import ./overlays; };

in
  pkgs.mkShell {
    buildInputs = with pkgs; [ home-manager ];

    shellHook = ''
      export NIX_PATH="nixpkgs=${pkgs.path}:nixpkgs-overlays=./overlays/default.nix:home-manager=${pkgs.home-manager.src}"
      export HOME_MANAGER_CONFIG="./home.nix"
    '';
  }
```

</details>

**Comment by rycee** [comment]
It'll be tricky to patch HM given the way the package in Nixpkgs is made. I think the easiest option you have available is to override the kitty package by an empty one. You can try putting

    nixpkgs.overlays = [
      (self: super: { kitty = pkgs.runCommandLocal "no-kitty" {} "mkdir $out"; })
    ];

in your HM configuration.

**Comment by evanrelf** [comment]
There are some other modifications I'd like to make, which would definitely require patching; I just gave the `kitty` one as an example. 

I'm also able to patch Nixpkgs in the same way I'm patching `home-manager` above, or I could or override `home-manager` in Nixpkgs with the `home-manager` from this repo?

**Comment by evanrelf** [comment]
I see what you mean now, how the way Nixpkgs packages `home-manager` makes overriding `src` tricky. The old path is already baked into their `installPhase`. Thanks for the pointer.

I was able to get my patches applied successfully by copy pasting the `installPhase` from Nixpkgs into my overlay, so that I could change what `src` it was using. Unless there's a better way of changing `home-manager` modules, I'm going to go with this solution.
