### ISSUE TITLE
How to handle collisions between home-manager-path and systemPackages?

### ISSUE THREAD

**Issue by jokogr** [rycee/home-manager#138]
Hello,

Suppose that I have non-root access to a NixOS system which has a package already installed via `environment.systemPackages` and I would like to reuse my dotfiles' `.config/nixpkgs/home.nix` which has the same package overlapping.

`home-manager switch` fails in that case, e.g. trying to install `htop`:

```
building path(s) ‘/nix/store/y6mvlngfpn0nfarwszq9icvp6iq3jllh-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 79.
collision between ‘/nix/store/m93ryazgf6z88hncfg8f3vgk0b8inip3-home-manager-path/bin/htop’ and ‘/nix/store/k84sbzv05s8kc1zy1ri2002dgkxgyrqc-htop-2.0.2/bin/htop’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
builder for ‘/nix/store/x5f7j9s6x55h84661qkr8i1pba06cnq8-user-environment.drv’ failed with exit code 2
error: build of ‘/nix/store/x5f7j9s6x55h84661qkr8i1pba06cnq8-user-environment.drv’ failed
```

Is there a way to define priority or so?

**Comment by rycee** [comment]
Hmm, packages installed by Home Manager should not collide with system packages. Are you sure you don't have htop installed in your user profile? I.e., does `nix-env -q | grep htop` find an install?

**Comment by jokogr** [comment]
@rycee you are totally right, it was already installed in my user profile, thanks for the quick reply!
