### ISSUE TITLE
home-manager is trying to use an old path

### ISSUE THREAD

**Issue by nico202** [rycee/home-manager#139]
Hi, I'm facing a problem that's leading me to the inability to change my home.nix file

I switched to a configuration with a non-existant path (I placed there the .git github repository, ‘https://github.com/nico202/home-manager.git’) and I get the expected:

`tar: This does not look like a tar archive `

I then changed the url to the tar archive. But now it keep trying to fetch the .git path.

Deleting the home.nix file leads to the "No configuration file error". Touching the file (without editing it) leads home-manager trying to fetch the .git path again.

Is this intended? How do I clear the cache and start over?
Thanks

**Comment by nico202** [comment]
Ok solved it by re-running the installation script

**Comment by rycee** [comment]
Yeah, it was probably in the Nix tarball cache and it started working again when the cache timeout triggered. You can always clear the tarball cache by doing `rm .cache/nix/tarballs/*`, then it should re-download immediately.

If you want to use your own repo that you have locally then you can also put the path to that in `programs.home-manager.path` (as a string). For example, I have
```
programs.home-manager.path = "${config.home.homeDirectory}/devel/home-manager";
```
in my configuration.

**Comment by nico202** [comment]
No it was a cache problem. In the /nix/store/**home-manager script there was at line 46:
`    for path in "@HOME_MANAGER_PATH@" \
`

My broken https://* url
