### ISSUE TITLE
systemd: don't suggest restarting units with RefuseManualStart=true

### ISSUE THREAD

**Issue by flokli** [rycee/home-manager#140]
Today, home-manager suggested me to restart `gpg-agent.service`, which has `RefuseManualStart` set to `true`.

Trying to issue the suggested command complained:
```
Failed to restart gpg-agent.service: Operation refused, unit gpg-agent.service may be requested by dependency only (it is configured to refuse manual start/stop).
See user logs and 'systemctl --user status gpg-agent.service' for details.
```

The suggestion script should simply exclude services that can't be restarted manually.

**Comment by rycee** [comment]
Thanks for reporting! I think this should be fixed in master now.

Note, we'll never be very intelligent about the suggested commands here. In this case I think we can do something reasonably but in general I think it'll have to wait until we can use the NixOS machinery, which is much smarter.

**Comment by flokli** [comment]
Sure, but this small idea just came into my mind. Thanks for the fix :-)
