### ISSUE TITLE
How to enable oh-my-fish theme

### ISSUE THREAD

**Issue by woylie** [rycee/home-manager#1400]
I installed an Oh My Fish theme by adding it to `programs.fish.plugins`.

```nix
{
  name = "bobthefish";
  src = pkgs.fetchFromGitHub {
  owner = "oh-my-fish";
    repo = "theme-bobthefish";
    rev = "a2ad38aa051aaed25ae3bd6129986e7f27d42d7b";
    sha256 = "1fssb5bqd2d7856gsylf93d28n3rw4rlqkhbg120j5ng27c7v7lq";
  };
}
```

Now I'd like to activate it. The issue is that the `~/.config/fish/conf.d/plugin-bobthefish.fish` file that is created only sources `$plugin_dir/init.fish`, `$plugin_dir/key_bindings.fish` and `$plugin_dir/conf.d/*.fish`. However, it seems that the `.fish` files that need to be sourced are located in the root plugin directory in the case of Oh My Fish themes.

```
> ls /nix/store/jnz46wgfh3k7mxmiwfjgxy6gzb2gd45z-source
LICENSE                 fish_mode_prompt.fish   fish_title.fish
README.md               fish_prompt.fish        functions/
fish_greeting.fish      fish_right_prompt.fish  hooks/
```

I would like to source all these files in my `loginShellInit` script. Is there any way to get the plugin directory within the nix store so I can do that?

**Comment by rycee** [comment]
I don't really know anything about fish but perhaps you have add some manual sourcing through something like
```
xdg.configFile."fish/conf.d/plugin-bobthefish.fish".text = lib.mkAfter ''
  source $plugin_dir/whatever.fish
'';
```
?

**Comment by woylie** [comment]
I added this and it works fine:

```
  xdg.configFile."fish/conf.d/plugin-bobthefish.fish".text = lib.mkAfter ''
    for f in $plugin_dir/*.fish
      source $f
    end
    '';
```

Thanks for your help!
