### ISSUE TITLE
How would I add something to ~/.profile ?

### ISSUE THREAD

**Issue by 573** [rycee/home-manager#1414]
Assumed I had `programs.bash.enable = true;` and the `~/.profile` file is generated via home.nix.

Where would I add `. somefile` such that the line is added to the generated `~/.profile` ?

Right now I just have `programs.bash.initExtra = ''. somefile'';` but that adds the line to `~/.bashrc` which seems to work but kind of not to belong right there ?

**Comment by uvNikita** [comment]
I think you are looking for `programs.bash.profileExtra` option.

**Comment by 573** [comment]
thx @uvNikita
