### ISSUE TITLE
Is it possible to read config in home.nix?

### ISSUE THREAD

**Issue by jokogr** [rycee/home-manager#143]
Hello,

Is it possible to check NixOS configuration in home.nix? I was thinking of something like the following:

```
{ config, pkgs, ... }:

home.packages = with pkgs; ([ blabla ] ++
  pkgs.lib.optionals config.services.xserver.enable [ myXpackages ]);
```

**Comment by rycee** [comment]
Something like
```nix
{ config, pkgs, ... }:

let

  sysconfig = (import <nixpkgs/nixos> {}).config;

in

{
  home.packages = with pkgs; ([ blabla ] ++
    pkgs.lib.optionals sysconfig.services.xserver.enable [ myXpackages ]);
}
```
may work.

**Comment by jokogr** [comment]
I was wondering if it is possible to remove `<nixpkgs/nixos>` impurity, so that I my Hydra instance could build the required packages per machine configuration. I've tried something like that:

```
{ pkgs, sysconfig ? import (<nixpkgs/nixos> {}).config, ... }:

{
  programs.home-manager.enable = true;
  programs.home-manager.path = https://github.com/rycee/home-manager/archive/master.tar.gz;

  home.packages = with pkgs; ([ blabla ] ++
    pkgs.lib.optionals sysconfig.services.xserver.enable [ myXpackages ]);
}
```

but apparently I cannot add an argument with a default value:

```
% home-manager switch --show-trace                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ~
error: attribute ‘sysconfig’ missing, at /nix/store/zkq9psjl7011gv75j4ljgf2bpwkngm4l-nixos/nixos/lib/modules.nix:163:28
(use ‘--show-trace’ to show detailed location information)
```

**Comment by rycee** [comment]
Hmm, can you give some more details about your setup for building the machine in Hydra? Do you use `NIXOS_CONFIG` to specify the machine configuration? If so then the `import (<nixpkgs/nixos> {}).config` should honor `NIXOS_CONFIG` but it would assume the system configuration targets your build host's `builtins.currentSystem`, which may not be what you want. I assume your pkgs is targetting the correct system so maybe can set the system manually?

Maybe something like

```nix
{ config, pkgs, ... }:

let

  sysconfig = (import <nixpkgs/nixos> {
    system = config.nixpkgs.system;
  }).config;

in

{
  programs.home-manager.enable = true;
  programs.home-manager.path = https://github.com/rycee/home-manager/archive/master.tar.gz;

  home.packages = with pkgs; ([ blabla ] ++
    pkgs.lib.optionals sysconfig.services.xserver.enable [ myXpackages ]);
}
```

**Comment by jokogr** [comment]
@rycee Sure thing, have a look @ https://git.joko.gr/joko/etc-nixos/src/master/jobs.nix#L35

You are correct, I have set the system (x86_64-linux) manually. I will have to be very careful, so that I avoid using `builtins.currentSystem`.

In your suggestion I still cannot see how Hydra would understand `config.nixpkgs.system`... Maybe I could set config?

**Comment by rycee** [comment]
The `config.nixpkgs.system` option is by default set to `pkgs.system` so it will use whichever system your Nixpkgs is targeting. And since you already have set the system when you assign the `pkgs` argument I'm thinking that my suggestion above should work.

In any case I'll try to look into adding some form of `sysconfig` argument that is set when running HM on NixOS.

**Comment by jokogr** [comment]
`home-manager switch` is still working properly, but Hydra is also still failing:

```
file 'nixos-config' was not found in the Nix search path (add it using $NIX_PATH or -I), at [1m/nix/store/adqlp2c7ybd89lnmgi8x9dby86n2h4z9-git-export/nixos/default.nix[0m:1:60
```

I have tried setting the input argument `config` of `home.nix` to `nixos.config` which more or less comes from the following expression:

```
import <nixpkgs/nixos/lib/eval-config.nix> {
    system = "x86_64-linux";
    modules = [ ... ];
};
```

**Comment by rycee** [comment]
Ok, a new proposal. In your `home.nix` add

```
lib =
  let
    nixos = import <nixpkgs/nixos> { system = config.nixpkgs.system; };
  in
    lib.mkBefore { jokogrNixosConfig = nixos.config; };
```

somewhere inside the configuration attribute set and replace

    sysconfig = (import <nixpkgs/nixos> {}).config;

by

    sysconfig = config.lib.jokogrNixosConfig;

Then, in `jobs.nix` change [line 35](https://git.joko.gr/joko/etc-nixos/src/master/jobs.nix#L35) to something like

```
pkgs =
  let
    homeManager = import <home-manager>/modules {
      configuration = {
        imports = [ <dotfiles/home/.config/nixpkgs/home.nix> ];
        lib.jokogrNixosConfig = nixos.config;
      };
      pkgs = import <nixpkgs> { system = "x86_64-linux"; };
    };
    hmPkgs = homeManager.config.home.packages;
  in
    listToAttrs (map (pkg: { name = pkg.name; value = pkg; }) hmPkgs);
```

where `<home-manager>` is the path to the Home Manager project root.

**Comment by jokogr** [comment]
Many thanks for looking into this 👍 

The `lib` part went ok after using **pkgs.**`lib.mkBefore` (before that I was getting *error: infinite recursion encountered* for that particular line).

In jobs.nix, I had to import `<home-manager/modules`**>**, not `<home-manager>/modules`.

Unfortunately, I now get the following error:

```
infinite recursion encountered, at undefined position
```

**Comment by jokogr** [comment]
@rycee made it once again! He suggested the following:

* Copy the original `home.nix` to `home-base.nix`.
* Use the following as `home.nix`:

```
{
  imports = [ ./home-base.nix ];
  lib.myConfig = import <nixpkgs/nixos> { system = config.nixpkgs.system; };
}
```

* Use something similar to this for generating the `pkgs`:

```
      pkgs =
        let
          homeManager = import <home-manager/modules> {
            configuration = {
              imports = [ <dotfiles/home/.config/nixpkgs/home-base.nix> ];
              lib.myConfig = nixos.config;
              home.homeDirectory = "/home/joko";
              home.username = "joko";
            };
            pkgs = nixos.pkgs;
          };
          hmPkgs = homeManager.config.home.packages;
        in
          listToAttrs (map (pkg: { name = pkg.name; value = pkg;}) hmPkgs);
```
