### ISSUE TITLE
source: Error encountered while sourcing file '/nix/store/izdgybj5b5bwm69xx8mdimdm7q1f04dy-mcfly-0.4.1/share/mcfly/mcfly.fish':

### ISSUE THREAD

**Issue by bbigras** [rycee/home-manager#1466]
### Issue description

```
❯ env LANG=c fish
source: Error encountered while sourcing file '/nix/store/izdgybj5b5bwm69xx8mdimdm7q1f04dy-mcfly-0.4.1/share/mcfly/mcfly.fish':
source: No such file or directory
~/.config/fish/config.fish (line 14):
mcfly_key_bindings
^
from sourcing file ~/.config/fish/config.fish
	called during startup
```

#### Maintainer CC

@marsam

#### Technical details

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.10-zen1, NixOS, 20.09pre-git (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09pre237686.96069f7d890"`
 - nixpkgs: `/run/current-system/nixpkgs`

**Comment by marsam** [comment]
Hi, thanks for trying the mcfly module. 
You need mcfly 0.5.0 (already in nixpkgs HEAD) for this module. I think you could apply https://github.com/NixOS/nixpkgs/commit/6b8e30c2dc8 to your local nixpkgs as a workaround.

**Comment by bbigras** [comment]
It seems to work fine with 0.5.0. Thanks for the help, and the module :smile:

**Comment by bbigras** [comment]
I have some weird message when I install my nixos config with nixus. and sometimes in emacs too:

```
Directory `/home/bbigras/dev/neuron/fish: Unknown command: mcfly_key_bindings
~/.config/fish/config.fish (ligne 14) : 
mcfly_key_bindings
^
du fichier source ~/.config/fish/config.fish
	appelé pendant le démarrage
```
