### ISSUE TITLE
homeDirectory when listed as path scans whole directory

### ISSUE THREAD

**Issue by fzakaria** [rycee/home-manager#1471]
### Issue description

I recently upgraded my home-manager installation and changed _homeDirectory_ to the new path format:
```nix
{ config, pkgs, lib, ... }:
{
  home.username = "fmzakari";
  home.homeDirectory = /home/fmzakari;
}
```

When I run `home-manager switch` however I'm immediately hit with
```bash
$ home-manager switch

warning: dumping very large path (> 256 MiB); this may run out of memory
```

What is interesting; is if I reset it back to the `builtins.getEnv` 

```nix
{ config, pkgs, lib, ... }:
{
  home.username = "fmzakari";
  home.homeDirectory = builtins.getEnv "HOME";
}
```
It does **not** suffer this issue.
```bash
nix repl
Welcome to Nix version 2.3.7. Type :? for help.

nix-repl> builtins.getEnv "HOME"
"/home/fmzakari"
```

#### Maintainer CC
@rycee 

#### Technical details
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.10-1rodete2-amd64, Debian GNU/Linux, noversion`
```

**Comment by terlar** [comment]
When you are using path nix will copy the contents into the nix-store. What about putting it as a string?

**Comment by fzakaria** [comment]
That works too;  Can the option force String and not allow path ?

Seems like a gotcha to allow path.

**Comment by fzakaria** [comment]
The option description lists this:
```
home.homeDirectory
The user's home directory. Must be an absolute path.

Type: path
```

**Type: path**

**Comment by terlar** [comment]
Indeed, or I think the path could be converted to a string to avoid this behind the scenes. Lets see if there is any reason why this should be path or if the copying of the path could be prevented internally.

**Comment by rycee** [comment]
Added a `toString`, hopefully that fixes the issue.

**Comment by fzakaria** [comment]
Thank you!
