### ISSUE TITLE
Are both file.<name>.source and file.<name>.target managed by home-manager?

### ISSUE THREAD

**Issue by shadowrylander** [rycee/home-manager#1474]
Hello!

I just wanted to know something:

When managing custom dotfiles, are both the `source` and `target` files managed by `home-manager`? I wanted the module to leave the source file alone, so that I could manage it with another program, and use `<name>.text = lib.mkAfter [...]` to add NixOS-specific configurations to the target dotfiles. Specifically, I wanted to use the `yadm` program to manage the file `~/.xonshrc##template`, which will be used as the source file for the `~/.xonshrc` target, which is managed by `home-manager`. However, I find that if I try to create `~/.xonshrc##template`, for example with `vim`, `~/.xonshrc` opens up instead as a read-only file, despite `~/.xonshrc##template` not existing yet. This occurs even without setting `~/.xonshrc##template` as the source file, implying that any file in the same directory as the managed file, and beginning with the managed file's name (such as `~/.xonshrc` and `~/.xonshrc##template`) cannot be created or modified.

Thank you kindly for the help!

**Comment by rycee** [comment]
No, HM does not modify the source file in any way. You have found that HM created a symlink from `~/.xonshrc##template` to the Nix store?

**Comment by shadowrylander** [comment]
Ah; essentially what happened is that, since the `~/.xonshrc##template` had not been created yet, I left the source (i.e. `~/.xonshrc`) out, intending for the text attribute to manage the file (`file.".xonshrc"`) before I eventually created the source. However, what I find when I go to create `~/.xonshrc##template`, instead of opening a new file, the text editor opens `~/.xonshrc`, which is currently managed by just it's text attribute using your module. While I'm assuming that this is a Linux issue itself, since I can't use vim, touch, etc. to create `~/.xonshrc##template`, I was wondering whether this should be accounted for?

**Comment by shadowrylander** [comment]
Basically: Linux can't open the new file `~/.xonshrc##template`, instead opening `~/.xonshrc`.
Question: Should this be accounted for when setting up the home directory right after a fresh install of NixOS?

**Comment by shadowrylander** [comment]
Sorry for the confusion in wording; it's really confusing to explain, even though the situation itself is simple!

**Comment by rycee** [comment]
Perhaps you are trying to open the file in a shell and the `#` parts gets interpreted as a comment? Try `vim ~/'.xonshrc##template'`.

**Comment by shadowrylander** [comment]
Why yes; yes they are. Unfortunately, the single quotes do not work either, as they appear in the filename as well.

**Comment by shadowrylander** [comment]
Oh, no, wait; switched to `"~/.xonshrc##template"`, and it works fine.

Sorry for the trouble; I'll close this now! 😅
