### ISSUE TITLE
Feature request:  link $out/share/applications/ of home.packages into $XDG_DATA_HOME/applications

### ISSUE THREAD

**Issue by eqyiel** [rycee/home-manager#149]
This will allow desktop managers like gnome3 to launch applications installed by home-manager.

Maybe there's already a way?  With my limited knowledge I can't think of a way to do this other than

```nix
home.file.".local/share/applications/firefox.desktop".source = "${pkgs.firefox}/share/applications/firefox.desktop";
```

For each package that has a desktop entry.

**Comment by rycee** [comment]
Are you using NixOS or some other platform? I think these desktop entries should already be visible under NixOS. For other platforms it may be sufficient to ensure that `$HOME/.nix-profile/share` is added to the `XDG_DATA_DIRS` environment variable.

You could try adding
```bash
export XDG_DATA_DIRS=$XDG_DATA_DIRS${XDG_DATA_DIRS:+:}$HOME/.nix-profile/share
```
to your `~/.profile` and see if that makes gnome3 find the desktop entries. If they show up then it might be worth adding this assignment as part of an option in HM.

**Comment by eqyiel** [comment]
Yeah this is 100% PEBKAC, gnome-session just needed restarting for it to find the desktop files in `~/.nix-profile/share`.  Sorry for the noise!

**Comment by eqyiel** [comment]
For future humans, you can get gnome-session to reload by pressing Alt-F2 (run command dialog) and entering `r`.
![screenshot from 2017-11-25 11-25-39](https://user-images.githubusercontent.com/3422442/33226039-8a494024-d17b-11e7-91eb-0d23fb189fde.png)

**Comment by rycee** [comment]
No problems. Glad it worked out for you 😄
