### ISSUE TITLE
Will HM dotfiles port to NixUP?

### ISSUE THREAD

**Issue by ixxie** [rycee/home-manager#151]
I saw the talk of NixUP being released soon, and I up wondering how much of my dotfiles will carry over once its ready; I know you have been collaborating on this project and I am curious to hear whether it makes sense to continue hacking my HM config ^^

**Comment by rycee** [comment]
Unfortunately I haven't had time to look deeply into the recent changes in NixUP. In general though, the two should be quite close and a HM configuration should be quite easy to convert. Some variable renaming may be necessary and I'm not sure if some more advanced features carry over 1-to-1, e.g., when using the `recursive` home file option. The `systemd.user.*` options will change completely in NixUP, though, to match the NixOS setup.

In any case, I will continue working on Home Manager until NixUP is in stable NixOS and also supports non-NixOS systems.

**Comment by ixxie** [comment]
@rycee thanks for clearing that up :) this is what I was hoping to hear of course!
