### ISSUE TITLE
home-manager-generation.drv: No such file or directory 

### ISSUE THREAD

**Issue by datakurre** [rycee/home-manager#168]
Suddenly after ``nix-collect-garbage -d`` and restart I started getting this error with ``home-manager switch`` and even with trying to reinstall:

```
nix-shell https://github.com/rycee/home-manager/archive/master.tar.gz -A install

Creating initial Home Manager generation...

error: opening file '/nix/store/pwikb841sinjv037cd1d04b6dmn5k18s-home-manager-generation.drv': No such file or directory
 ```

How should I clear home-manager state?

**Comment by rycee** [comment]
Hmm, home manager should be safe w.r.t Nix garbage collections. What does

```console
$ ls -l /nix/var/nix/gcroots/per-user/$USER
```

and

```console
$ ls -l /nix/var/nix/profiles/per-user/$USER/home-manager*
```

say? If you want to make a clean reinstall you can try deleting the old gcroot and profiles from the above directories.

**Comment by datakurre** [comment]
It looks correct

```
$  ls -l /nix/var/nix/gcroots/per-user/$USER
lrwxrwxrwx 1 datakurre users 67 17.12. 18:58 current-home -> /nix/store/8c3m9qcvnjwnb9frwawig2mhvcjqdp2d-home-manager-generation

$ ls -l /nix/var/nix/profiles/per-user/$USER/home-manager*
lrwxrwxrwx 1 datakurre users 20 17.12. 18:58 /nix/var/nix/profiles/per-user/datakurre/home-manager -> home-manager-28-link
lrwxrwxrwx 1 datakurre users 67 17.12. 18:58 /nix/var/nix/profiles/per-user/datakurre/home-manager-28-link -> /nix/store/8c3m9qcvnjwnb9frwawig2mhvcjqdp2d-home-manager-generation
```

After removing those roots, and running garbage collection, I was able install home manager again, but after installation got the same error

```
$ nix-shell https://github.com/rycee/home-manager/archive/master.tar.gz -A install
unpacking 'https://github.com/rycee/home-manager/archive/master.tar.gz'...
these derivations will be built:
  /nix/store/11w8q56cj95bz543xr2yq35s9zrwjb2s-home-manager.drv
building '/nix/store/11w8q56cj95bz543xr2yq35s9zrwjb2s-home-manager.drv'...
install: creating directory '/nix/store/12mnn7caair5mlq0ip2cji3hj5anvj7k-home-manager'
install: creating directory '/nix/store/12mnn7caair5mlq0ip2cji3hj5anvj7k-home-manager/bin'
'/nix/store/x5j6gy7mgb9kjv9w0916jxs8j7sybblj-home-manager' -> '/nix/store/12mnn7caair5mlq0ip2cji3hj5anvj7k-home-manager/bin/home-manager'

Creating initial Home Manager generation...

error: opening file '/nix/store/pwikb841sinjv037cd1d04b6dmn5k18s-home-manager-generation.drv': No such file or directory

There are 2 unread and relevant news items.
Read them by running the command 'home-manager news'.


Uh oh, the installation failed! Please create an issue at

    https://github.com/rycee/home-manager/issues

if the error seems to be the fault of Home Manager.
```

**Comment by datakurre** [comment]
@rycee It might be related (though I have no idea how it could be) that before gc I moved all extra environment packages from global NixOS configuration into home manager controlled ``home.packages``.

**Comment by datakurre** [comment]
@rycee Adding seemingly irrelevant change to a ``home.file...text`` contents made both install and subsequent switch to pass. I have no idea why, but works now again.

**Comment by rycee** [comment]
Hmm, that is very odd! Did you have some odd target file name?

**Comment by datakurre** [comment]
@rycee No. Target filename was ``.buildout/default.cfg``. I had no issues with that until gc. I'll reopen if I see that issue ever again. Thank a lot for support (and, of course, this very useful project)!

**Comment by rycee** [comment]
Yeah, please do. I've never seen this before and it looks like a quite annoying error!

And thanks for the kind words 😄

**Comment by raboof** [comment]
I had a somewhat-similar-looking problem (though it was the `user-environment.drv` that could not be found). This happened when running in a VM created with `nixos-rebuild build-vm` with `useUserPackages = false`.

While it is likely not the same problem, since search engines seem to rank this issue highly I wanted to mention here that enabling `useUserPackages` appears to have fixed it.
