### ISSUE TITLE
Feature request: change detection in `home.files`

### ISSUE THREAD

**Issue by Nadrieril** [rycee/home-manager#179]
A fair number of files in the home directory have to somehow be reloaded to take effect immediately. In my case I have noticed at least `.XResources`, `.tmux.conf` and the i3 config file.
I think this is a common pattern and it would be cool if there was a `home.files.<file>.onChange` option to trigger a user-defined script on activation when the file has changed since the last generation.
This is already done by the i3 service for its own config file (https://github.com/rycee/home-manager/blob/master/modules/services/window-managers/i3.nix#L625) but I'm not familiar enough with the internals of `home.files` to see how to generalize it properly myself.

**Comment by rycee** [comment]
Yeah, I've been meaning to do just this and it shouldn't be tricky to implement. Thanks for making an issue about it so I won't forget! :-)

I'll try to find some time to get it done.

**Comment by Nadrieril** [comment]
Oh, that's great ! Thanks ! I'd be happy to help with testing or whatnot if you need.

**Comment by ayyjayess** [comment]
I've been running with an `onChange` option that works all right but might need revisiting to tidy up.
https://github.com/rycee/home-manager/compare/master...ayyjayess:files_on_change

**Comment by Nadrieril** [comment]
@ayyjayess any chance you could make this into a PR ?

**Comment by ayyjayess** [comment]
@Nadrieril I'm a bit busy at the moment so feel free.

**Comment by rycee** [comment]
Fixed in 30cba446f2c2e04db5a5001aaf606a4a5563e1de 🙂

**Comment by BadDecisionsAlex** [comment]
Is there a suggested pattern to aggregate multiple "onChange" triggers to a single activation action? An example illustrates my point better:
I have multiple source files that all feed into my XMonad config, I would like to rebuild XMonad when any of them are changed.
I naively tried copying the `xmonad.hs` (main config) file's `onChange` hook to all of the additional source files; but (as you probably predicted) this causes XMonad to rebuild N times when N/|inputs| are changed, when the desired behavior is a single rebuild at the end of the activation process (or at least at the end of activating the group).

I considered building some kind of external script or something (aliasing `home-manager switch or something`) where each `onChange` ticks some external counter, which is triggered after home manager completes it's rebuild; but I was certain there was already an existing feature to handle this type of thing.

I thought I would check in for some direction before I go and reinvent the wheel haha.

**Comment by rycee** [comment]
@BadDecisionsAlex I think the simplest would be to insert a comment
```haskell
-- Rebuild triggers: @file1@ @file2@
```
in your main `xmonad.hs`. Then change the configuration to
```
xsession.windowManager.xmonad.config = pkgs.substituteAll {
  src = ./path/to/main/xmonad.hs;
  file1 = ./path/to/file1.hs;
  file2 = ./path/to/file2.hs;
};
```
