### ISSUE TITLE
Add NixOS module to configure users with home manager

### ISSUE THREAD

**Issue by rycee** [rycee/home-manager#18]
It would be quite nice to be able to set up the user environment directly from the system configuration. Especially when creating containers.

In principle this should be relatively simple to do by hooking in the Home Manager activation script in the NixOS activation script. It may be trickier in practice, though…

**Comment by rycee** [comment]
See #97 for work on this. Any testing would be appreciated.

**Comment by flokli** [comment]
Awesome! Will give this a try this weekend :-)

**Comment by rycee** [comment]
Fixed in 1bc59f729047886b845ffd9162d40593fad5c7f0. Thanks for everybody's patience ;-)
