### ISSUE TITLE
ssh compression doesn't allow you to turn it *off* for a particular host

### ISSUE THREAD

**Issue by jwiegley** [rycee/home-manager#181]
Although you can use the `compression` attribute to turn compression on or off globally in the config file, you can only turn it *on* for a particular host.

**Comment by rycee** [comment]
Now you can turn it off by setting `compression = false;` the field will be omitted only if `compression = null;` (which it is by default).

**Comment by jwiegley** [comment]
I mentioned this because I set `compression = true` for the default, but `compression = false` for a particular host. However, the code for particular hosts reads:

```
    ++ optional cf.compression            "  Compression yes"
```

I.e., it will turn *on* compression for a given host, but it will not turn it *off* if you've set the default to be true, which is governed by this bit of code:

```
      Compression ${yn cfg.compression}
```

**Comment by rycee** [comment]
But the code for a host in the commit that closed this issue now says

```
++ optional (cf.compression != null)  "  Compression ${yn cf.compression}"
```

so with any luck you should be able to put `compression = false` for a given host and the generated config will say `Compression no` for that host.
