### ISSUE TITLE
polybar: "invalid include file" when setting polybar.config to file

### ISSUE THREAD

**Issue by Tmplt** [rycee/home-manager#185]
In `home.nix`:
```nix
polybar = {
  enable = true;
  config = /home/tmplt/.config/polybar/example;
  script = "polybar example &";
};
```

The above compiles but polybar doesn't start. Trying to manually start it via `polybar -c ~/.config/polybar/config example` yields `"error: Invalid include file ""/nix/store/<hash>-example"" defined on line 2`. Passing that file to `-c` instead starts the program as expected.

From the doubled qoutation marks in the error message, I figure they might not be needed in the generated `config`; I'd try without myself, but I can't seem to edit the files, even via sudo.

**Comment by Tmplt** [comment]
I forgot to mention I'm using the latest release of `home-manager`; I'll try with `master` tomorrow.

**Comment by rycee** [comment]
Hmm, from looking at the [polybar code](https://github.com/jaagr/polybar/blob/1739e4490dc3f693b8a7c93fcd43c1d2c2723532/src/components/config.cpp#L95-L115) it does indeed seem like it simply uses the value (the text after '=') as-is when including files. So it shouldn't be printed to the configuration file with quotes.

Looking further down in the code it seems like other polybar configuration keys allow their value to be surrounded by quotes, but this is not required. So perhaps it is enough to do

```patch
diff --git a/modules/services/polybar.nix b/modules/services/polybar.nix
index b218c6c..d6f78b6 100644
--- a/modules/services/polybar.nix
+++ b/modules/services/polybar.nix
@@ -13,7 +13,7 @@ let
     let
       value' =
         if isBool value then (if value then "true" else "false")
-        else if isString value then "\"${value}\""
+        else if isString value then value
         else toString value;
     in
       "${key}=${value'}";
```

@uvNikita What do you think?

**Comment by Tmplt** [comment]
@rycee Applying that patch resolves the issue.

**Comment by uvNikita** [comment]
@rycee Thank you for investigating the issue!

The reason I decided to surround values with double quotes is that someone might want to have trailing spaces after the value, e.g. to add spacing:
```
      "module/xkeyboard" = {
        type = "internal/xkeyboard";
        format-prefix = "kb ";  # note trailing space here
        label-layout = "%layout%";
      };
```
With the proposed patch this space will be ignored by polybar. It is possible to use the following workaround for this case though, but I'm not sure how obvious it will be for users:
```
      "module/xkeyboard" = {
        type = "internal/xkeyboard";
        format-prefix = ''"kb "'';
        label-layout = "%layout%";
      };
```

**Comment by uvNikita** [comment]
Due to above reason, I've created PR with the special case for `include-file` property. Let me know what you think.

**Comment by rycee** [comment]
@Tmplt Thanks for testing and verifying that it worked(ish) :-)

@uvNikita Good point about the trailing spaces and thanks for the fixed patch! I think it is quite reasonable that polybar's special case reflects in our code.
