### ISSUE TITLE
environment.pathsToLink alternative for home configuration

### ISSUE THREAD

**Issue by uvNikita** [rycee/home-manager#191]
System configuration has [environment.pathsToLink](https://github.com/NixOS/nixpkgs/blob/9c96edf8d7d64afeea0d9d1541e97cabcdb03ba8/nixos/modules/config/system-path.nix#L68) option that can be used to symlink additional directories to system profile. In particular, it's used in [bash](https://github.com/NixOS/nixpkgs/blob/9c96edf8d7d64afeea0d9d1541e97cabcdb03ba8/nixos/modules/programs/bash/bash.nix#L205) and [zsh](https://github.com/NixOS/nixpkgs/blob/9c96edf8d7d64afeea0d9d1541e97cabcdb03ba8/nixos/modules/programs/zsh/zsh.nix#L191) modules to add shell completion for packages that provide it.

I wonder if we could have a similar option, but for home configuration, meaning that declaring something like `environment.pathsToLink = "/share/zsh"` would symlink this folder from all packages to `~/.nix-profile/share/zsh`.

**Comment by rycee** [comment]
Hmm, I'm a bit confused. What do you mean by *all* packages here. For packages in `home.packages` I understand their `/share/zsh` path will already be linked from `~/.nix-profile/share/zsh`.

**Comment by uvNikita** [comment]
Nevermind, I was a bit confused and thought to have system packages' `/share/zsh` folders in `~/.nix-profile`. But then it makes sense to set `environment.pathsToLink` parameter in system configuration and reference it from `.zshrc` :)

Fixed system packages completions here https://github.com/rycee/home-manager/pull/196.

**Comment by shlevy** [comment]
What about having headers available in the user profile? Currently I don't see `/include` linked in.

**Comment by rycee** [comment]
@shlevy Aren't the headers typically placed in a `dev` output? You can try adding

    home.extraOutputsToInstall = [ "dev" ];

to your configuration.

**Comment by shlevy** [comment]
I have that as well, though in this case I do have `/include` in a non-dev output of one of my drvs
