### ISSUE TITLE
Using home-manager on Ubuntu

### ISSUE THREAD

**Issue by sgraf812** [rycee/home-manager#201]
I'm currently setting up an Ubuntu machine and wanted to give `home-manager` a try to manage my `nix` config.

Unfortunately, this fails after the `nix-shell $HM_PATH -A install` step.
In particular, the shell invocation seems to download and install stuff, but I can't access `home-manager` within the shell: 

```
$ nix-shell $HM_PATH -A install        
downloading ‘https://github.com/rycee/home-manager/archive/master.tar.gz’... [0/0 KiB, 0.0 KiB/s]
unpacking ‘https://github.com/rycee/home-manager/archive/master.tar.gz’...
these derivations will be built:
  /nix/store/1kvigm7xrn265b8294vnyz8ya733x872-home-manager.drv
these paths will be fetched (65.48 MiB download, 383.55 MiB unpacked):
...
fetching path ‘/nix/store/1fhlzxwchqnfg3q6dy1jg661jf5jq6q8-bash-4.4-p12-doc’...
...
building path(s) ‘/nix/store/n3i39rddsnw0m63p2zigjdqkgb5zg0n1-home-manager’
install: creating directory '/nix/store/n3i39rddsnw0m63p2zigjdqkgb5zg0n1-home-manager'
install: creating directory '/nix/store/n3i39rddsnw0m63p2zigjdqkgb5zg0n1-home-manager/bin'
'/nix/store/pzd76az2grpfxhpw0fp9l6ihspixkaq1-home-manager' -> '/nix/store/n3i39rddsnw0m63p2zigjdqkgb5zg0n1-home-manager/bin/home-manager'
$ which home-manager
home-manager not found
$ ^D

Creating initial Home Manager generation...

these derivations will be built:
  /nix/store/1v3di0mbgfwn85daxq77v3nny3g17lcs-link.drv
...
Starting home manager activation
Activating checkLinkTargets
Activating writeBoundary
Activating uninstallHomeManager
Activating installPackages
installing ‘home-manager-path’
building path(s) ‘/nix/store/sspclkff7c6r1ifz8i0lh3x10ss48a15-user-environment’
Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 79.
collision between ‘/nix/store/gy4yv67gv3j6in0lalw37j353zdmfcwm-nix-1.11.16/bin/nix-build’ and ‘/nix/store/cbrjfmfdc2p0vx56jzl7ip31gyr0daxv-home-manager-path/bin/nix-build’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
builder for ‘/nix/store/rr70b71w1wlzmc0gmfsc3gj5v6av5xda-user-environment.drv’ failed with exit code 255
error: build of ‘/nix/store/rr70b71w1wlzmc0gmfsc3gj5v6av5xda-user-environment.drv’ failed

Uh oh, the installation failed! Please create an issue at

    https://github.com/rycee/home-manager/issues

if the error seems to be the fault of Home Manager.
```

Strange enough, the build only really finishes after leaving the `nix-shell` (is this expected? Need to work on my nix foo).

There seems to be a conflict with the installed `nix` package because `home-manager-path` provides its own. I tried to resolve this with `nix-env --set-flag priority 100 nix`, but then it would only break at a later point.

Any advice?

**Comment by sgraf812** [comment]
FYI, `nix-home` seems to have the same problem in the final installation step. It's the top-level `all` derivation that's conflicting there.

**Comment by sgraf812** [comment]
Nevermind, I figured it out. `nix-env -q` lists the `nix` package at a minimum and of course I can't include that in my `paths` list if I want to avoid conflicts. I wasn't aware of the machinery behind `home-manager` and replicated most of it by hand, only to find out why this failed.

**Comment by rycee** [comment]
I'm glad it worked out for you! Honestly I've never tried following the setup instructions on a non-NixOS system. Do you have any suggestion on how to improve the instructions so that others can avoid the problem you encountered?

**Comment by sgraf812** [comment]
A hint that you can't have a package both show up in `nix-env -q` and in your `paths` attribute/`home-manager packages` would be helpful.

Also I'm not sure how `nix-shell $HM_PATH -A install` is supposed to work, but as you can see from the log above the shell that opens doesn't really have the right environment. Only after quitting the shell `home-manager` creates its initial generation. That felt weird, because it wasn't mentioned in the instructions that I was supposed to leave the shell immediately.

Otherwise this mostly works for me now, so that's great. Thanks for your efforts!

**Comment by rycee** [comment]
Hmm, the `nix-shell $HM_PATH -A install` command should never put you in an interactive shell. It should just automatically run the installation commands and then exit back into your regular shell. If you re-run `nix-shell $HM_PATH -A install` do you still get this shell prompt? Which version of nix do you have (nix-env --version)?

I'll add a note about not having packages installed through both `home.packages` and `nix-env -q` in the readme. Thanks!

**Comment by sgraf812** [comment]
I get the interactive shell also on re-runs. `nix` version is `1.11.16` on Ubuntu 17.10.
