### ISSUE TITLE
zsh: oh-my-zsh plugin configuration via env vars is flawed

### ISSUE THREAD

**Issue by Nadrieril** [rycee/home-manager#207]
A lot of oh-my-zsh plugins can be configured by setting appropriate environment variables. The problem is that a number of those plugins expect those variables to be set *before* oh-my-zsh is loaded, and the `zsh` module loads custom env vars *after* oh-my-zsh.
An example of a such a plugin is `per-directory-history`, that will ignore changes made to `$HISTORY_BASE` after is has been loaded (see https://github.com/robbyrussell/oh-my-zsh/blob/37c2d0ddd751e15d0c87a51e2d9f9849093571dc/plugins/per-directory-history/per-directory-history.zsh#L86).
Could there be a way to set some env vars before loading oh-my-zsh ?

**Comment by Nadrieril** [comment]
I believe it worked before, and I suspect https://github.com/rycee/home-manager/commit/fa6f697dbbe06b47b17057d93dffdfcd6f39cbbc is the culprit of the change.

**Comment by uvNikita** [comment]
Thanks for reporting the issue!

I now moved session variables setting back before oh-my-zsh sourcing. I don't see the reason why this would be an issue.

I moved it to the end with the thought that some plugins might override user-specified session variables, but I haven't experienced this problem myself.

**Comment by Nadrieril** [comment]
It does, thanks a lot !
