### ISSUE TITLE
Cannot switch on Darwin after most recent commits

### ISSUE THREAD

**Issue by jwiegley** [rycee/home-manager#209]
Hi @rycee, when I try to use `home-manager switch` on Darwin after updating today, I get:

```
Failed assertions:
- Username could not be determined
```

After setting `home.username = "johnw"`, I then get:

```
home-manager switch
/nix/store/q25ykmbgi5y56as0m92bvg9gj7pa8bmk-home-manager-generation/activate: line 13: USER: unbound
 variable                                                                                          
make: *** [Makefile:11: home-switch] Error 1
```

What is the expected way to use the new code on Darwin?

**Comment by jwiegley** [comment]
For whatever reason, `git bisect` reports this as the first failing commit: f2265b10e4eb48c66d334fa1d90bebb4affbec69

**Comment by rycee** [comment]
That looks quite odd! The activation script relies on the environment variable `USER` being set during activation, but this has been the case forever. Is `USER` for some reason not set on your system?

**Comment by jwiegley** [comment]
Thanks, it was just an oddness in my environment when starting iTerm with Emacs as the parent process.
