### ISSUE TITLE
xsession.windowManager should take an expression

### ISSUE THREAD

**Issue by Eisfreak7** [rycee/home-manager#21]
Hi,

currently, setting a wm requires the path to the executable:
`xsession.windowManager = "${pkgs.wm}/bin/wm";`
I think this should instead be handled like it is in `configuration.nix`:
`xsession.windowManager = pkgs.wm;`.

**Comment by rycee** [comment]
Y

**Comment by rycee** [comment]
I think `xsession.windowManager = pkgs.wm;` specifically is unlikely to happen but I would like to have something like `xsession.windowManager.xmonad.enable = true;`. Thus far I have avoided this but may revisit it soon, shouldn't be too difficult.

**Comment by Eisfreak7** [comment]
That'd be good as well. I ran into this problem because I just specified `"wm"` (instead of an absolute path). Thus X couldn't be started.

Both alternative solutions would already give me an error when rebuilding the configuration, which I think is preferable.

But the sake of consistency and ease of adding new wms, why not `xsession.windowManager = pkgs.wm`?

**Comment by nocoolnametom** [comment]
The value of `pkgs.wm` is just a path to the derivation `wm` itself.  It doesn't know where in that derivation path the binary is located nor what it's named (true, it's usually going to be at `{derivationPath}/bin/{packageName}` but that can't be assumed for all window managers).

**Comment by Eisfreak7** [comment]
Ah I see. Maybe the [nixpkgs windowmanager files](https://github.com/NixOS/nixpkgs/tree/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/nixos/modules/services/x11/window-managers) could be reused for this purpose. That's what `configuration.nix` uses and it seems like a bad idea to maintain the same information twice.

**Comment by rycee** [comment]
Yeah, @nocoolnametom got it right. Additionally, even if we could guess the name of the executable we still might want to add customization.

I've added a branch [xsession-wm](https://github.com/rycee/home-manager/tree/xsession-wm) that frees up the `xsession.windowManager` namespace and adds an xmonad module (I reserve the right to force push to that branch at my leisure). With this my configuration is now

```
xsession = {
  enable = true;
  windowManager.xmonad = {
    enable = true;
    extraPackages = haskellPackages: [
      haskellPackages.xmonad-contrib
      haskellPackages.taffybar
    ];
  };
};
```

which I think is quite an improvement. The xmonad module I added borrows quite a bit of code from the NixOS module so it should be easy to move over additional wm modules.

**Comment by Eisfreak7** [comment]
Great! My personal preference would be different  (I think configuring a package should be standardized and distinct from setting that package as the window manager), but that seems to be the nix standard.

Your `xmonad.nix` seems to do exactly the same (apart from the naming of the options) as nixpkgs `xmonad.nix`. I have no experience with nix, but wouldn't it be better to abstract the difference away instead of copying and slightly modifying the files?

**Comment by rycee** [comment]
I'm inclined to agree with the idea that the package should be configured separately.

I initially had something like

```
xsession.windowManager = "xmonad";

program.xmonad = {
  enable = true;
  extraPackages = haskellPackages: [
    haskellPackages.xmonad-contrib
    haskellPackages.taffybar
  ];
};
```

where the xmonad binary with the configured packages would be installed because `enable = true` and it would be used as a window manager because `xsession.windowManager = "xmonad"`. This way you could set `xsession.windowManager = "fvwm"` and still have the xmonad command available.

I also considered having simply

```
services.xmonad = {
  enable = true;
  extraPackages = haskellPackages: [
    haskellPackages.xmonad-contrib
    haskellPackages.taffybar
  ];
};
```

That is, no mention of window managers at all. This kind of fits the intended future where the window manager starts like a user service like any other service. I'm kind of fond of this one but figured it was best to do something close to the NixOS way of setting the window manager.

About the module yeah I realize it would be good if the module from Nixpkgs could be used here as well. Unfortunately I think the modules differ enough (especially in the `config` attribute) that it isn't worth attempting to generalize them, at least I'm unlikely to allocate time to sort it out but I would be happy to see others doing it ☺

**Comment by Eisfreak7** [comment]
As someone new to nix (so without much knowledge of the technical concerns that formed the current way to do things), my ideal world without regard for correct syntax or package names would be:
```
myPrograms.taffybar = pkgs.haskellPackages.taffybar {
	# some configuration
}

# creating a modified version of the default xmonad
myPrograms.xmonad = pkgs.xmonad {
	# "optDependencies" and other options should be standardized and documented
	optDependencies = {
		xmonad-contrib = haskellPackages.xmonad-contrib # default, unconfigured version
		taffybar = myPrograms.taffybar # my configured version
		someOtherDep = pkgs.haskellPackages.someOtherDep {
			# some inline configuration
		}
	}
}

xsession.displayManager = program.slimdm {
	choices = [
		myPrograms.xmonad # configured version
		pkgs.xmonad # "slim" version without configuration
		pkgs.xterm
	];
}
```
That's of course way out of scope for this project.
I agree that staying as close to NixOS as possible is the right way to go. Ideally, my `home.nix` works exactly like my `configuration.nix` (having the same relationship as `/etc/vimrc` and `~/.vimrc`).

Regarding the reuse: Unfortunately I don't think I have enough experience with the nix syntax yet to do that myself.

**Comment by rycee** [comment]
Sorry for the long silence. I see your point @Eisfreak7. It's not very likely we'll move to that sort of structure though, at least not presently. For now it'll stay closer to the NixOS method for symmetry reasons. In particular, the xsession has changed to allow submodules for specific window managers. Only [xmonad](https://github.com/rycee/home-manager/blob/9c859d26553aebe56bb669f275af04cc1dbc4af5/modules/services/window-managers/xmonad.nix) is available in module form for now but more will hopefully show up in the future.

So I'll close this issue as "fixed as well as can be expected" :-) Thanks for opening it in the first place!

**Comment by Eisfreak7** [comment]
Okay, thank you for considering it!
