### ISSUE TITLE
Can't update configuration without internet connection

### ISSUE THREAD

**Issue by krey** [rycee/home-manager#211]
I tried to update a config file managed by Home Manager

```
> home-manager switch                                                                                                                                                                                         
downloading ‘https://github.com/rycee/home-manager/archive/master.tar.gz’... [0/0 KiB, 0.0 KiB/s]
warning: Nix search path entry ‘https://github.com/rycee/home-manager/archive/master.tar.gz’ cannot be downloaded, ignoring
error: file ‘home-manager/home-manager/home-manager.nix’ was not found in the Nix search path (add it using $NIX_PATH or -I)
```

**Comment by rycee** [comment]
Ow! Yeah, that's not so good. I think for now, if you need to have offline functionality the fastest way to accomplish that is to git clone the home-manager repo and point the `programs.home-manager.path` to your clone.

Using the http:… path is relying on a feature in Nix that'll handle all of the downloading and caching. Unfortunately it is somewhat limited in that the cache time cannot be configured and, apparently, it doesn't handle situations when there is no network available. I'll see about raising an issue in the Nix repo to see this can be changed.

Thanks for the report and I hope my reply is not too depressing :-)

**Comment by manveru** [comment]
You can configure the cache by setting the time in seconds:

    nix.extraOptions = ''
      tarball-ttl = ${toString (60 * 60 * 72)}
    '';

That's of course not much help if you're offline already, and rather unpredictable... but might be an option worth mentioning.

**Comment by LeOtaku** [comment]
Cloning the repo and adding the path to "imports" should also work, at least that's how I do it. [(my repo)](https://github.com/LeOtaku/nixos-config/blob/master/home-thinkpad-leo.nix#L10)

**Comment by rycee** [comment]
I'll close this issue. The recommended way to install Home Manager now uses channels, which works while offline.
