### ISSUE TITLE
Nix database directory ‘/nix/var/nix/db’ is not writable

### ISSUE THREAD

**Issue by pasqui23** [rycee/home-manager#218]
`home-manager switch` terminates with the following error:

```
home-manager switch    
Starting home manager activation
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
error: Nix database directory ‘/nix/var/nix/db’ is not writable: Permission denied
```

Of note that `nix-env` works normally without errors.
```
nix-info
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.0pre5943_52c777a7, channels(root): "nixos-18.03pre127921.9b25b9347d9", channels(pasquale): "nixos-18.03pre127921.9b25b9347d9", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs
```

**Comment by pasqui23** [comment]
Also the error remains even after running `sudo chmod -R +arwx /nix/var/nix/db`

**Comment by dotlambda** [comment]
You're probably using Nix 1.11 with a Nix 2.0 database.

**Comment by pasqui23** [comment]
solved by literally reinstalling nixos

**Comment by tkerber** [comment]
I request reopening. I have the same issue, with a little digging, the home manager activation script indeed links to nix 1.11, although I'm unsure why, as `nix.package` is set to `nixStable2`. Any thoughts on why this isn't propagating properly?

**Comment by rycee** [comment]
Give it a try now. With the latest master, the nix-env found in `PATH` will be used, not the one from `pkgs.nix`.

**Comment by tkerber** [comment]
Thanks, works great :)
