### ISSUE TITLE
Temporary failure to build basic configuration?

### ISSUE THREAD

**Issue by jpotier** [rycee/home-manager#22]
Today, I've installed home-manager following the README. At the `switch` step, it fails with:

    these derivations will be built:
      /nix/store/jzdvny020lx4j09ic1jl1hfcf0yvfh2i-nixos-manual-combined.drv
      /nix/store/007i2mkm6ns8qjhxm4hswr772pc85ivs-manual-olinkdb.drv
      /nix/store/9zqri7vxqkqmi2gzdanh7033b3y7j288-nixos-manpages.drv
      /nix/store/4idwybmyhbkraddsr09a25ijk9xmrkkj-home-environment-manpages.drv
      /nix/store/i7g2r5a45bp931mwv1srbzlx5y8dijwf-home-manager-files.drv
      /nix/store/fqjzsjz2xm1r078wh2irspaiw68v4kw5-home-manager-path.drv
      /nix/store/xmrkvr6bgzkqwfhc350jmxjd25gxyajc-activation-script.drv
      /nix/store/9k1fpwjffshpvnkwasv2nci8g6f5a1gk-home-manager-generation.drv
    these paths will be fetched (1.20 MiB download, 17.84 MiB unpacked):
      /nix/store/a8ys1mm9i87n4xi8sx8lxjpppxfv8x9c-docbook-xsl-ns-1.79.1
      /nix/store/bl48w7h24n6379fa200yv60n4pwynd9c-stdenv
    fetching path ‘/nix/store/bl48w7h24n6379fa200yv60n4pwynd9c-stdenv’...
    fetching path ‘/nix/store/a8ys1mm9i87n4xi8sx8lxjpppxfv8x9c-docbook-xsl-ns-1.79.1’...
    building path(s) ‘/nix/store/ad2dckd55maw12zj40bqacy2fki8k577-nixos-manual-combined’
    
    *** Downloading ‘https://cache.nixos.org/nar/0f8s4h5mgqqx2ng09xqwis3gxz15vn5wsnly70yvdcdn9r0wiaa4.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/a8ys1mm9i87n4xi8sx8lxjpppxfv8x9c-docbook-xsl-ns-1.79.1’...
    
    *** Downloading ‘https://cache.nixos.org/nar/0vk9ab95pf1f293ylaknn38b97b3hhz8y71p4cxd0ya2nzsxzqy1.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/bl48w7h24n6379fa200yv60n4pwynd9c-stdenv’...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    manual-combined.xml:2558: element para: Relax-NG validity error : Did not expect element para there
    manual-combined.xml:1504: element chapter: Relax-NG validity error : Element part has extra content: chapter
    manual-combined.xml:4: element info: Relax-NG validity error : Element book has extra content: info
    manual-combined.xml fails to validate
    builder for ‘/nix/store/jzdvny020lx4j09ic1jl1hfcf0yvfh2i-nixos-manual-combined.drv’ failed with exit code 3
    killing process 28096
    cannot build derivation ‘/nix/store/9zqri7vxqkqmi2gzdanh7033b3y7j288-nixos-manpages.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/4idwybmyhbkraddsr09a25ijk9xmrkkj-home-environment-manpages.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/fqjzsjz2xm1r078wh2irspaiw68v4kw5-home-manager-path.drv’: 1 dependencies couldn't be built
    cannot build derivation ‘/nix/store/xmrkvr6bgzkqwfhc350jmxjd25gxyajc-activation-script.drv’: 1 dependencies couldn't be built
    killing process 28095
    cannot build derivation ‘/nix/store/9k1fpwjffshpvnkwasv2nci8g6f5a1gk-home-manager-generation.drv’: 1 dependencies couldn't be built
    error: build of ‘/nix/store/9k1fpwjffshpvnkwasv2nci8g6f5a1gk-home-manager-generation.drv’ failed

My `.config/nixpkgs/home.nix` is

    { pkgs, ... }:
    
    {
      # home.packages = with pkgs; [
      # ];
    
      # Maintain home-manager up-to-date
      programs.home-manager.enable = true;
    }

I'm using `https://nixos.org/channels/nixos-unstable-small` in my user profile.

**Comment by adisbladis** [comment]
I hit the same thing but forgot to create an issue, my workaround was simply putting `manual.manpages.enable = false;` in home.nix.

Presumably this issue has something to do with the fix found here https://github.com/rycee/home-manager/blob/master/modules/manual.nix#L63

**Comment by jpotier** [comment]
Oh, I see.

  1. Thank you, I'll use your suggested workaround
  2. Now, this is bug has a reference, which is good.

I plan to dig in a little deeper in `home-manager` over the next 2-3 weeks and if possible, I'll suggest a fix.

**Comment by rycee** [comment]
I would guess that Nixpkgs master recently had some changes in how it builds the man page. Home manager is very hackily reusing that code. I'll have a look.

**Comment by adisbladis** [comment]
@rycee Here is the commit that broke it https://github.com/NixOS/nixpkgs/pull/26940/commits/1eb979db0e472557897405474288e9dae502a4f7

**Comment by rycee** [comment]
I think I have fixed this in dba14bfe90949003056786d50589014fbf4233ce, which is in the master branch. Please update and give `manual.manpages.enable = true;` a try. Many thanks for reporting the issue!

**Comment by jpotier** [comment]
Fixed here, nice work rycee!

**Comment by Mohammer5** [comment]
This resurfaced for me after upgrading the nixos channel from 20.03 to 20.09

**Comment by arx7ti** [comment]
This happened after upgrading from 20.03 to 20.09. Fixed by adding channel for home-manager 20.09 release.
