### ISSUE TITLE
error: hash '' has wrong length for hash type 'sha256'

### ISSUE THREAD

**Issue by balsoft** [rycee/home-manager#229]
When I run `home-manager switch`, I get the following error. Didn't happen before today.
```
$ home-manager switch            
error: hash '' has wrong length for hash type 'sha256'
(use '--show-trace' to show detailed location information)
```
(--show-trace doesn't work, I guess because it's nix-build argument and not home-manager's).
My configuration: https://gist.github.com/balsoft/d158ad4a919b5e4b08e0f37fc6cba9e6

**Comment by teto** [comment]
seems like you have somewhere a package with a sha256 equal to '' ? in your overlay maybe ?  or the 
```
pkgs.fetchgit {
					url = "git://github.com/zsh-users/zsh-syntax-highlighting";
};
```

**Comment by rycee** [comment]
Yeah, like @teto said, I think you'll need a sha256 field in the fetchgit call.

Like you notices it is unfortunately not possible to use `--show-trace` with the home-manager command but if use the `-v` option then it will also enable `--show-trace`. So you can try running `home-manager -v switch` and see if it gives a more useful error message.

**Comment by balsoft** [comment]
@teto thank you, that was the problem. The weird thing is that worked many times before, maybe there was an update to `pkgs.fetchgit`.
