### ISSUE TITLE
home-manager module is conflicting with home-manager

### ISSUE THREAD

**Issue by jpotier** [rycee/home-manager#23]
More precisely, I have the following `home.nix`

    { pkgs, ... }:
    
    {
      # Maintain home-manager up-to-date
      programs.home-manager.enable = true;
    }

When running `home-manager switch`, I get the following error

    /nix/store/0kfik30f4b3q1h3girqqrg1cpmznwymn-home-manager-generation
    Starting home manager activation
    Activating checkLinkTargets
    Activating writeBoundary
    Activating installPackages
    installing ‘home-manager-path’
    building path(s) ‘/nix/store/ckgcpiqjnashnd791bzl3hfnkvahsz41-user-environment’
    Wide character in die at /nix/store/64jc9gd2rkbgdb4yjx3nrgc91bpjj5ky-buildenv.pl line 79.
    collision between ‘/nix/store/kcm2957czc8lip13w88kybhk31gf2616-home-manager/bin/home-manager’ and ‘/nix/store/aiyf3wby4m0ckag3zpifr5gzap0ivbkp-home-manager-path/bin/home-manager’; use ‘nix-env --set-flag priority NUMBER PKGNAME’ to change the priority of one of the conflicting packages
    builder for ‘/nix/store/vcc3vh3r5svh3bfq0rkyhjj0ixgqa3z1-user-environment.drv’ failed with exit code 255
    error: build of ‘/nix/store/vcc3vh3r5svh3bfq0rkyhjj0ixgqa3z1-user-environment.drv’ failed

My guess is that my user installation of `home-manager` is already providing the binary `home-manager` in my user environment. When enabling the `home-manager` module, there's another binary to be linked in my user environment. This is not a really blocking bug, but maybe it should eventually be documented in the installation procedure.

Moreover, I understand the `home-manager` module is fairly new (just a few days) and I'm very excited to finally get some time to test it out.

**Comment by dermetfan** [comment]
Looking at 28d3f746146a66dbd64816b8638deaa83199302f..7a18a0fb348393a4d4cb9aaff39626d63351edc3 it seems @rycee intended to remove the `home-manager` package from your `nix-env` user profile. You need to uninstall home-manager prior to `switch`ing to avoid the collision with the home-manager in `home-manager-path`:

```sh
$ nix-env -q
home-manager
home-manager-path

$ home-manager build # build the new generation
$ nix-env -e home-manager # uninstall to avoid collision
$ result/activate # switch to the new generation

$ nix-env -q
home-manager-path
```

The activation script could do that for you, but if it doesn't I agree we should mention this in the docs.

**Comment by jpotier** [comment]
Oh, nice! I didn't notice one could use ./result/activate!

**Comment by rycee** [comment]
Yeah, I just added the home-manager module on a whim so didn't write too much documentation about how to switch to a self-managed mode. You got it right though, you first have to use `nix-env -e` to remove the old version and then use the activation script directly.

I may add an extra command to `home-manager` that will do these steps automatically, something like `home-manager switch-to-managed`.

**Comment by dermetfan** [comment]
Wouldn't it be enough to add `nix-env -e home-manager` to the activation script in the `programs/home-manager` module?

**Comment by rycee** [comment]
@dermetfan Ah, yes of course! I think that would work :-) Thanks! I'll see about adding that to the activation script if `programs.home-manager.enable` is set.

**Comment by rycee** [comment]
Implemented @dermetfan's suggestion and it work quite nicely! So hopefully @jpotier's problem won't happen to anybody else.

**Comment by jpotier** [comment]
Nice, now it's really closed : )
