### ISSUE TITLE
problems with ssh config

### ISSUE THREAD

**Issue by phryneas** [rycee/home-manager#232]
Hi there :)

I'm currently trying to migrate my ssh config, and I'm having some problems.

The problem is this property of [the config](https://man.openbsd.org/ssh_config):

```
Since the first obtained value for each parameter is used, more host-specific declarations should be given near the beginning of the file, and general defaults at the end.
```

currently, the configuration looks like this:

```
ForwardAgent no
Compression no
ServerAliveInterval 0
HashKnownHosts no
UserKnownHostsFile ~/.ssh/known_hosts
ControlMaster no
ControlPath ~/.ssh/master-%r@%h:%p
ControlPersist no

// custom host configurations down here *in random order*
```

this essentially means that when I set `ForwardAgent no`, I cannot set it to `ForwardAgent yes` for a specific host.

Also, if I have configurations like
```
            "x.example.com" = {
                username = "b";
            };

           "*.example.com" = {
                username = "a";
                // some other options
            };
```
they possibly end up in reverse (or any) order, which means a connect to "x.example.com" may, depending on the random order end up in using username a or b.

I could fix the first problem myself, by moving the global configuration to the bottom, prefixed by `Host * `, but I'm not fluent enough in nix yet to understand the random mapping.

Can we fix that?

**Comment by phryneas** [comment]
PS: I took a second look and it seems that the order might be alphabetical (I have only 3 entries so far).
If sets in nix are always alphabetical, would switching the type of `matchBlocks` to an array be an option? I fear that might break many configurations :/

**Comment by rycee** [comment]
Yeah, for these types of configurations you need to specify the match blocks as a list instead of an attribute set. Try changing to something like

```
matchBlocks = [
  {
    host = "x.example.com";
    username = "b";
  }

  {
    host = "*.example.com";
    username = "a";
    // some other options
  }
];
```

**Comment by phryneas** [comment]
Argh, I missed that one in the documentation, thanks!

That leaves the part with the general config (that I cannot turn off) - would you accept a pull request to move that to the bottom prefixed with `Host *` ?

**Comment by rycee** [comment]
I think that seems like a fair proposal. I made a basic implementation in the PR above.

Thanks for raising the issue! :-)

**Comment by phryneas** [comment]
great, thanks for the fast reaction :)

**Comment by Matt3o12** [comment]
I know this is a very old thread, but I have found it on Google, and I would like to share my solution in case someone else has the same problem. I have replicated my SSH config in Nix. My SSH config was somewhat complicated, and I heavily relied on **ordered** drop-in config files like this:

```
.ssh/config.d/
├── 10-work-machines
├── 50-personal
└── 90-defaults
```

And my `ssh_config` just had `Include ~/.ssh/config.d/*` in it.

In order to replicate this in Nix, I have created several modules like `modules/ssh-config/configs/90-defaults.nix`, which match my previous bash format, a global config that loads them, orders them correctly before giving them to `program.ssh.matchBlocks`. The trick is to set the attribute key of the first item to `1000` and the next key to `1001`. As long as you either define `match` or `host` inside the attribute value, the attribute key is only used for ordering, as far as I can tell.

<details>

<summary>My config for reference</summary>

```nix
# modules/ssh-config/configs/90-defaults.nix
{
  lib,
  pkgs,
  sshScripts,
  ...
}:

{
  controlMaster = "auto";

  matchBlock = [
    {
      host = "foo",
      user = "bar",
    },
    {
      match = ''
        host *
        exec "..."
      '';
      extraOptions = {
        // ...
      };
    }
  ];
}

# modules/ssh-config/default.nix

{ pkgs, lib, ... }:

# SSH Configuration Management System
#
# OVERVIEW:
# This configuration manages SSH settings in a structured, ordered way using
# separate module files. This solves the alphabetical sorting issue in Nix's
# attribute sets that breaks SSH config precedence rules.
#
# THE ORDERING PROBLEM:
# SSH configurations depend critically on order — later entries override earlier ones.
# However, Nix attribute sets are unordered (or rather, sorted alphabetically when
# rendered), which breaks SSH config precedence rules. For example:
#
#   { "z-host" = { ... }; "a-host" = { ... }; }
#
# would result in "a-host" appearing first in the generated config, regardless of
# how they were defined in the Nix code.
#
# THE SOLUTION:
# 1. In each module, define match blocks as an ordered LIST instead of attributes
# 2. Convert these lists to attribute sets with carefully constructed keys:
#    - Each key follows the pattern: "modulename-NNNN" (e.g., "90-defaults-1001")
#    - Module names are prefixed with numbers (10-, 20-, etc.) to control inter-module ordering
#    - Within each module, we append sequential 4-digit numbers (1001, 1002, etc.)
# 3. When Nix alphabetically sorts these keys, they maintain the exact order we want
#
# MODULE FORMAT:
# Each module should export an attribute set with:
# - matchBlock: A list of SSH match blocks in desired precedence order
# - Any global SSH options (controlMaster, controlPath, etc)
#
# Example module:
# {
#   controlMaster = "auto";
#
#   matchBlocks = [
#     { host = "server1"; user = "admin"; }     # Will become "modulename-1001"
#     { host = "server2"; port = 2222; }        # Will become "modulename-1002"
#   ];
# }
#
# The system will:
# 1. Convert matchBlock lists to ordered attribute sets with prefixed names
# 2. Merge global options from all modules
# 3. Create necessary directories for SSH operation

let
  sshScripts = {};

  # Function to convert a list of match blocks to an ordered attribute set
  listToOrderedAttrs = prefix: matchBlockList:
    builtins.listToAttrs (
      lib.imap0
        (idx: block: {
          name = "${prefix}-${toString (builtins.floor (idx + 1001))}";
          value = block;
        })
        matchBlockList
    );

  # Common module arguments
  moduleArgs = { inherit sshScripts lib pkgs; };

  # List of module configurations to load
  moduleConfigs = [
    "10-work"
    "20-private"
    "90-defaults"
  ];

  # Load all modules
  loadedModules = map (name: import (./configs + "/${name}.nix") moduleArgs) moduleConfigs;

  # Extract and merge global SSH options from all modules
  globalOptions = lib.filterAttrs (name: _: name != "matchBlock")
                  (lib.foldl lib.recursiveUpdate {} loadedModules);

  # Process match blocks from all modules
  processedMatchBlocks = lib.mkMerge (lib.imap0
    (idx: module:
      let name = builtins.elemAt moduleConfigs idx;
      in if builtins.hasAttr "matchBlocks" module
         then listToOrderedAttrs name module.matchBlocks
         else {})
    loadedModules);
in
{
  programs.ssh = lib.recursiveUpdate globalOptions {
    enable = true;
    matchBlocks = processedMatchBlocks;
  };
}
```

This will create attribute keys such as `10-work-1000`, `10-work-1001`, `90-defaults-1000`, which is exactly how I want it.
</details>

I hope this can help someone else.
