### ISSUE TITLE
Allow shell plugins to be "just files"

### ISSUE THREAD

**Issue by jwiegley** [rycee/home-manager#234]
Not every shell plugin on the Web comes packaged into a directory, sometimes it's just a bare script at a URL.  Currently there's no way to express these in zsh.plugins, for example.

**Comment by uvNikita** [comment]
This PR might solve the issue: https://github.com/rycee/home-manager/pull/245. It should be possible now to set `zsh.plugins.*.src` to a plugin file instead of a directory, but I haven't tried it myself. You could use `fetchurl` function instead of `fetchFromGitHub` to download the file.

**Comment by rycee** [comment]
@jwiegley Did #245 fix the issue?

**Comment by jwiegley** [comment]
@rycee Yes!

Here's how I ended up using it:

```
      initExtra = lib.mkBefore ''
        if [[ -o interactive ]]; then
           . ${xdg.configHome}/zsh/plugins/iterm2_shell_integration
        fi
      '';

      plugins = [
        { name = "iterm2_shell_integration";
          src = pkgs.fetchurl {
            url = https://iterm2.com/shell_integration/zsh;
            sha256 = "17x6mqgn0j1cn6xvzl6x7d36zrkrmq81bqnbmz797prsgs1g4i98";
            # date = 2018-04-26T14:38:20-0700;
          };
        }
      ];
```

I still have to source it in myself, but it works.

**Comment by rycee** [comment]
Oops, I forgot to close this 🙂
