### ISSUE TITLE
calling builtins.mapAttributes on a loaOf shifts list order

### ISSUE THREAD

**Issue by phryneas** [rycee/home-manager#235]
I was experiencing this in the ssh module, but it might be relevant elsewhere too.

Apparently the list is re-sorted alphabetically, which leads to this behaviour:

```builtins.attrNames hmConfig.config.programs.ssh.matchBlocks
[ "unnamed-1.1" "unnamed-1.10" "unnamed-1.11" "unnamed-1.12" "unnamed-1.13" "unnamed-1.14" "unnamed-1.15" "unnamed-1.2" "unnamed-1.3" "unnamed-1.4" "unnamed-1.5" "unnamed-1.6" "unnamed-1.7" "unnamed-1.8" "unnamed-1.9" ]
```

**Comment by phryneas** [comment]
if someone needs a workaround for this:

my current workaround is preprending the list with 9 dummy hosts - I don't care where those get sorted in. but if you have more than 90 hosts this might not be feasible.

```
{ host = "dummy-1"; }
                { host = "dummy-2"; }
                { host = "dummy-3"; }
                { host = "dummy-4"; }
                { host = "dummy-5"; }
                { host = "dummy-6"; }
                { host = "dummy-7"; }
                { host = "dummy-8"; }
                { host = "dummy-9"; }
```

**Comment by rycee** [comment]
Took quite a while but the upstream fix just got in the stable NixOS channel so I'll close this. The workaround should no longer be necessary 🙂

**Comment by phryneas** [comment]
Cool, thanks again :)
