### ISSUE TITLE
zsh: NIX_REMOTE seems not to be set

### ISSUE THREAD

**Issue by phryneas** [rycee/home-manager#236]
I noticed this as I couldn't open nix-repl any more without setting the variable. This could be s sign of other things not being set, too.
Right now I'm still in the process of investigating this, and if I have any progress I'll add it here.

Rycee told me to cc @Infinisil  and @uvNikita  - maybe you have some ideas on this one?

**Comment by phryneas** [comment]
After some digging I'm honestly not even sure any more if this is a home-manager specific problem, because I can find nowhere in my whole system where this variable would have been set.

I'd love to hear some feedback from Infinisil and uvNikita, but if you too think that this is not related, feel free to close this :/

**Comment by rycee** [comment]
It should come from the `set-environment` script:

```console
$ grep -C4 NIX_REMOTE $(grep -o '/.*set-environment' /etc/profile)

# Set up secure multi-user builds: non-root users build through the
# Nix daemon.
if [ "$USER" != root -o ! -w /nix/var/nix/db ]; then
    export NIX_REMOTE=daemon
fi

# Wrappers override other bin directories.
export PATH="/run/wrappers/bin:$PATH"
```

So I guess it wouldn't be set if you are `root` or have write permissions to `/nix/var/nix/db`.

**Comment by phryneas** [comment]
Wow, thanks for digging. 
I digged some more, and apparently `nixos/modules/services/misc/nix-daemon.nix` declares this only if nix2 is not installed - and as it seems, my system has switched to nix2 without me noticing it.

So I've got a changelog to read now. Thank you for your patience with me and investigating this, and sorry for blaming this on home-manager.

**Comment by rycee** [comment]
Glad you found the cause :+1:
