### ISSUE TITLE
home manager won't build; archive lacks a signature

### ISSUE THREAD

**Issue by krey** [rycee/home-manager#237]
```
$ home-manager switch
error: imported archive of ‘/nix/store/xacm6g2f3i9j7885k93zyqw11psyixjv-master.tar.gz’ lacks a signature
```

```
$ nix-shell -p nix-info --run "nix-info -m"                                                  ~
warning: unknown setting 'signed-binary-caches'
warning: unknown setting 'signed-binary-caches'
 - system: `"x86_64-linux"`
 - host os: `Linux 4.9.86, NixOS, 17.09.3159.c665fcca9e7 (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
warning: unknown setting 'signed-binary-caches'
 - version: `nix-env (Nix) 2.0`
warning: unknown setting 'signed-binary-caches'
 - channels(root): `"nixpkgs-unstable-18.09pre132003.13e74a838db, nixos-unstable-18.03pre130932.cc4677c36ee, nixos-17.09.3159.c665fcca9e7"`
warning: unknown setting 'signed-binary-caches'
 - channels(krey): `""`
warning: unknown setting 'signed-binary-caches'
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by rycee** [comment]
Maybe this is related to https://github.com/NixOS/nix/issues/1860 and/or https://github.com/NixOS/nix/issues/1641? Perhaps you have a 1.11 nix-daemon and have Nix 2.0 installed for your user? Have you recently updated to NixOS 18.03?

**Comment by krey** [comment]
Thanks rycee.

The issue turned out to be the `nixStable2` package. Switching back to `nixUnstable` fixed the issue. 

ps. too scared to update to 18.03 at this point

**Comment by rycee** [comment]
Glad you found the solution and hopefully your eventual switch to 18.03 will be a smooth one :-)

Note, I won't be able to support the 17.09 branch of Home Manager for very long once 18.03 is officially released so please don't wait too long.
