### ISSUE TITLE
home-manager tried to remove ~ when deleting an obsolete file

### ISSUE THREAD

**Issue by utdemir** [rycee/home-manager#25]
I renamed one of the config file (`home.file.".minidlna".text = "..."`), but it looks like `home-manager` tried to nuke my home directory instead :). I'm not sure if there's a risk or not, but seeing `rmdir: failed to remove: /home/utdemir` was pretty scary.

See:

```
$ home-manager switch
Starting home manager activation
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
replacing old ‘home-manager-path’
installing ‘home-manager-path’
building path(s) ‘/nix/store/9wyqccwgy02j6p5hzdi5iqqdxdj75i2w-user-environment’
created 438 symlinks in user environment
Activating linkGeneration
Creating profile generation 47
Cleaning up orphan links from /home/utdemir
Checking /home/utdemir/.minidlna  gone (deleting)
rmdir: failed to remove '/home/utdemir'
Activating reloadSystemD
```

**Comment by rycee** [comment]
I understand your worry but in this case it is harmless and your home directory will not be removed unless it is actually completely empty. When a link is removed by home manager it will attempt to remove the containing directory, if it is empty using `rmdir --parents`. Unfortunately this means that it will print this error on the first non-empty directory it finds, which in your case is your home directory.

Unfortunately `rmdir` doesn't seem to offer a way to silence this particular error message. I've considered simply doing something like
```
rmdir --parent blahblah 2>&1 | grep -v 'Directory not empty'
```
but it's not exactly pretty so I have delayed in case a better solution comes.

**Comment by utdemir** [comment]
Fair enough, I'm closing the issue 👍 .

It's an awesome tool, thank you very much!

**Comment by rycee** [comment]
Thanks! That's nice to hear :-)

By the way, I've pushed commit 5862a05fb1cc0de5d6c48ea4d709c2fca8050689 to master and I think it will fix this issue. Basically, the error will only show up if the containing directory is `$HOME` so I just added a little code to run `rmdir` only if the containing directory is _not_ `$HOME`.

Many thanks for reporting this issue!
