### ISSUE TITLE
Custom modules when using nixos/default.nix

### ISSUE THREAD

**Issue by pjones** [rycee/home-manager#250]
First, I love Home Manager.  Thank you for all the work that you've put into this project!

I'm using Home Manager as part of my NixOS system configuration and would like to write some custom modules that wouldn't be useful to the general public.  In `nixos/default.nix` the `hmModule` submodule imports all of the Home Manager modules.

How would I go about adding a custom module?  I know I can write a standard NixOS module and use `home-manager.users.myusername` but I'm not sure how I can use the Home Manager properties directly (e.g. `services`, `systemd.user.services`, `xdg.configFile`, etc.)

Thank you.

**Comment by rycee** [comment]
Thanks for the kind words! :blush:

If you want home manager module to recognize a new module then you could simply use the `imports` option. For example in #252 you see the imports section, there you could put the path to your module file and it should be picked up by Home Manager and inside it your should be able to access all the Home Manger configuration and options as if it was a bundled Home Manager module.

Note, you might run into the same problem as @uvNikita did in #252 so keep an eye on that issue to see how things progress.

**Comment by pjones** [comment]
Closing this since #252 is the way to go.
