### ISSUE TITLE
Some issues when using home manager as nixos module

### ISSUE THREAD

**Issue by uvNikita** [rycee/home-manager#252]
I'm trying to switch configuration to nixos module instead of using home-manager program. Previously I was able to split `home.nix` into separate files using imports like this:

```
{ pkgs, lib, ... }:
{
    imports = [ /path/to/user/base.nix ];
    home.packages = [ pkgs.hello ];
}
```

But if I'm trying to do the same with nixos module, I'm getting `error: The option 'home-manager.users.user.imports' defined in ... does not exist.`. `configuration.nix` looks something like this:
```
{ config, pkgs, ... }:
{
  users.users.user.isNormalUser = true;

  home-manager.users.user = {
    imports = [ ../lib/user/base.nix ];

    home.packages = [ pkgs.hello ];
  };
}
```

I'm probably missing something obvious here, but can't figure out the correct way to do it for now.

**Comment by rycee** [comment]
Hmm, it works OK for me but I simply have something like
```
home-manager.users.rah = import ../user/rah-config.nix;
```
where `rah-config.nix` is precisely the same configuration I used with the home-manager command.

And the first few lines in `rah-config.nix` are

```
{ pkgs, ... }:
{
  imports = [ ./common.nix ./extra-packages.nix ];

  …
```

It might be important that the option is set to a function? Could you try something like

```nix
{ config, pkgs, ... }:
{
  users.users.user.isNormalUser = true;

  home-manager.users.user = { ... }: {
    imports = [ ../lib/user/base.nix ];

    home.packages = [ pkgs.hello ];
  };
}
```

**Comment by pjones** [comment]
I can confirm that setting `home-manager.users.USERNAME` to a function works!  Thanks.

**Comment by uvNikita** [comment]
Yes, making it function solved the problem, thanks @rycee !

I'm now getting this error during the activation. Am I missing something more?

```
systemd[1]: Starting Home Manager environment for USER...
hm-activate-USER[28762]: Activating home-manager configuration for USER
hm-activate-USER[28762]: Starting home manager activation
hm-activate-USER[28762]: Activating checkI3
hm-activate-USER[28762]: Activating checkPolybar
hm-activate-USER[28762]: Activating checkLinkTargets
hm-activate-USER[28762]: Activating writeBoundary
hm-activate-USER[28762]: Activating linkGeneration
hm-activate-USER[28762]: Cleaning up orphan links from /home/USER
hm-activate-USER[28762]: Creating profile generation 1605
hm-activate-USER[28762]: Creating home file links in /home/USER
hm-activate-USER[28762]: Activating reloadSystemD
hm-activate-USER[28762]: User systemd daemon not running. Skipping reload.
hm-activate-USER[28762]: Activating applyPolybar
hm-activate-USER[28762]: Activating installPackages
hm-activate-USER[28762]: replacing old 'home-manager-path'
hm-activate-USER[28762]: installing 'home-manager-path'
hm-activate-USER[28762]: building '/nix/store/h8an8dcbagrv5xdhrxg3vc7mjnr38ix5-user-environment.drv'...
hm-activate-USER[28762]: created 9 symlinks in user environment
hm-activate-USER[28762]: Activating gnomeTerminal
hm-activate-USER[28762]: error: Cannot autolaunch D-Bus without X11 $DISPLAY
hm-activate-USER[28762]: Usage:
hm-activate-USER[28762]:   dconf load DIR
hm-activate-USER[28762]: Populate a subpath from stdin
hm-activate-USER[28762]: Arguments:
hm-activate-USER[28762]:   DIR         A directory path (starting and ending with '/')
systemd[1]: home-manager-USER.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: home-manager-USER.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Home Manager environment for USER.
```

I also was wondering if there is a way to say to home-manager that I want to use the unstable branch for everything managed by home-manager (something like `pkgs = <nixpkgs-unstable>`) leaving my nixos system branch to be stable?

**Comment by uvNikita** [comment]
Seems like it's the problem with gnome-terminal only, removing it from the configuration solves the issue.

**Comment by rycee** [comment]
@uvNikita I suspect the underlying issue for the dconf issue is that the session dbus in NixOS is not socket activated. See https://github.com/NixOS/nixpkgs/issues/17943#issuecomment-341860410 for an analysis of mine about the situation. And I don't know of anything that can be done in Home Manager to work around this :frowning_face:

**Comment by uvNikita** [comment]
OK, thank you for the clarification! I'll switch to urxvt in the meantime.

I noticed that i3 reloading on config change doesn't work with nixos module, even though I see "Activating reloadI3" message in the log output. Is this something expected?

**Comment by rycee** [comment]
@uvNikita Sorry about the delay. It is probably because `DISPLAY` is not set when the activation script is run. So
```bash
if [[ -v i3Changed && -v DISPLAY ]]; then
  echo "Reloading i3"
  ${cfg.package}/bin/i3-msg reload 1>/dev/null
fi
```
will not trigger. I don't know if i3-msg can run without DISPLAY or there is some other way to determine whether a reload actually should happen.
