### ISSUE TITLE
home-manager-manual error

### ISSUE THREAD

**Issue by mightybyte** [rycee/home-manager#261]
I just started getting the following error when I run `home-manager switch`:

```
./manual.xml:38: element include: XInclude error : could not load generated/options-db.xml, and no fallback was found
builder for '/nix/store/n0yg6anycws9play1anx12m6j9xyh77f-home-manager-manual-combined.drv' failed with exit code 1
```

**Comment by rycee** [comment]
Hmm, I did fundamentally change how the manual is generated the other day but haven't noticed any issues building them on NixOS 18.03 or master. Which environment are you using home manager in? NixOS or some other distro? Version?

**Comment by mightybyte** [comment]
I'm using macOS High Sierra 10.13.3 with Nix 2.

**Comment by rycee** [comment]
I guess there must be some difference between the macOS 10.12 that travis-ci seem to use and 10.13 because it [seems to build ok](https://travis-ci.org/rycee/home-manager/jobs/376128196#L663-L672) there.

Would you mind pasting all the log lines from `building '/nix/store/XYZ-home-manager-manual-combined.drv'...` to the error place? Any difference from the travis-ci output?

**Comment by rycee** [comment]
Oh, btw. In case you've missed it, if you disable the `manual.manpages.enable` option I guess you should be able to complete the `home-manager switch` so that you aren't blocked completely by this bug.

**Comment by mightybyte** [comment]
The above is all the lines in that range.  Here's some more though:

```
building '/nix/store/n0yg6anycws9play1anx12m6j9xyh77f-home-manager-manual-combined.drv'...
./manual.xml:38: element include: XInclude error : could not load generated/options-db.xml, and no fallback was found
builder for '/nix/store/n0yg6anycws9play1anx12m6j9xyh77f-home-manager-manual-combined.drv' failed with exit code 1
cannot build derivation '/nix/store/15ayvjnaq91822j963yyyamr1bfal01k-home-manager-manpages.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/x5ijnzpjhsnllmxjk79wbkjx1k089ss4-home-manager-path.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/3jfyvjqlc4jbmd40x4f6hr50vdkdg3v5-home-manager-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/3jfyvjqlc4jbmd40x4f6hr50vdkdg3v5-home-manager-generation.drv' failed
```

That workaround got me unblocked, thanks!

**Comment by PhDyellow** [comment]
I had the same error under NixOS 18.03, using home-manager as a nixos module.

I tried commenting out `manual.manpages.enable`, but it didn't work. 

I had success after commenting out all refernces to homemanager in my `configuration.nix`, rebuilding nixos, running a full `sudo nix-collect-garbage -d`, then enabling homemanager again and rebuilding nixos.

**Comment by j0xaf** [comment]
Same issue here under Ubuntu 18.04. Disabling `manual.manpages.enable` as workaround helped.

**Comment by jbgi** [comment]
> I tried commenting out manual.manpages.enable, but it didn't work.

I had to set it to `false`, commenting was not enough.

**Comment by rycee** [comment]
I'm pretty certain I've managed to fix this in #264. Unfortunately travis-ci is not doing macos builds at the moment so I'll wait a bit with the merge. It would be great if somebody here could test that branch and see if it actually fixes the problem.

As a bonus I managed to produce the beginnings of an HTML manual including the options: https://rycee.github.io/home-manager/

**Comment by rycee** [comment]
Merged to master now. Please give `manual.manpages.enable = true` a try, hopefully it should build the manual OK now.

**Comment by dermetfan** [comment]
Fixed it for me, I had the same problem on NixOS 18.09.

**Comment by rycee** [comment]
Cool, I'll close this then. If anybody still experiences this issue then please reopen.
