### ISSUE TITLE
README unclear: nixos-unstable or nixpkgs-unstable?

### ISSUE THREAD

**Issue by ivanbrennan** [rycee/home-manager#270]
The README is unclear/inconsistent in describing which channels home-manager targets.

The ["Words of warning"](https://github.com/rycee/home-manager/blame/bbcef2fd33165c987ec0b746211782aca7815ac6/README.md#L22) section refers to NixOS unstable:
> Home Manager targets NixOS unstable and NixOS version 18.03 (the current stable version), it may or may not work on other Linux distributions and NixOS versions.

The ["Installation"](https://github.com/rycee/home-manager/blame/bbcef2fd33165c987ec0b746211782aca7815ac6/README.md#L70) section refers to Nixpkgs unstable:
> ... depending on whether you follow Nixpkgs unstable or version 18.03.

Since ([nixos-unstable](https://nixos.org/channels/nixos-unstable) / [nixpkgs-unstable](https://nixos.org/channels/nixpkgs-unstable)) are different channels, it should be made clear which one is targeted.

I would have submitted a PR, but I don't know which channel is correct.

**Comment by rycee** [comment]
Hmm, honestly I don't think we're targeting any one of these in particular. For example, right now there are four commits between nixos-unstable and nixpkgs-unstable, which for Home Manager's purposes are basically the same.

That said, I agree that more consistent wording in the readme would be good. I'll see about cleaning it up. Thanks for reporting the issue 🙂

**Comment by ivanbrennan** [comment]
Thanks. I was trying to figure out which one was targeted in order to decide what to set `HM_PATH` to in step 2 of the installation instructions.

Maybe it makes sense to recommend
```
HM_PATH=https://github.com/rycee/home-manager/archive/master.tar.gz
```
if you're following nixos-18.03, and
```
HM_PATH=https://github.com/rycee/home-manager/archive/release-18.03.tar.gz
```
if you're following either of the unstable channels.

**Comment by rycee** [comment]
Thanks, that's a good suggestion. I created #271, which should implement this although I worded it slightly differently. Please have a look.

**Comment by ivanbrennan** [comment]
That's great, thanks so much!
