### ISSUE TITLE
programs.bash.shellAliases.<name> produces invalid .bashrc due to quoting

### ISSUE THREAD

**Issue by ldesgoui** [rycee/home-manager#273]
Hello,

    programs.bash.shellAliases.nix-stray-roots = "nix-store --gc --print-roots | egrep -v '^(/nix/var|/run/\w+-system|\{memory)'";

will produce

    alias nix-stray-roots='nix-store --gc --print-roots | egrep -v '^(/nix/var|/run/w+-system|{memory)''

and

    bash: /home/ldesgoui/.bashrc: line 16: syntax error near unexpected token `('
    bash: /home/ldesgoui/.bashrc: line 16: `  alias nix-stray-roots='nix-store --gc --print-roots | egrep -v '^(/nix/var|/run/w+-system|{memory)'''

The code in question: https://github.com/rycee/home-manager/blob/9ea353569a437659157230d740467778e91a2baa/modules/programs/bash.nix#L132-L134

I'm uncertain what would be an idiomatic way to fix this, hence no PR.

Thanks

**Comment by rycee** [comment]
Thanks for the report! I've created a PR that hopefully resolves this issue.

**Comment by ldesgoui** [comment]
Excellent, thanks!
