### ISSUE TITLE
home-manager and plasma5

### ISSUE THREAD

**Issue by uvNikita** [rycee/home-manager#29]
I'm trying to run home-manager together with plasma5, but can't figure out what I should specify in `xsession.windowManager` option. I've tried `${pkgs.kwin}/bin/kwin_x11`, but it didn't work.

**Comment by rycee** [comment]
Hmm, I'm not familiar with kwin but in principle your configuration looks ok here. Do you get any error message or similar when starting your X session? Anything suspicious in the output of `journalctl --user -b` after attempting it?

What is your complete settings in the system `services.xserver` and the home manager `xsession` sections?

**Comment by uvNikita** [comment]
This error appears in log after I login in `sddm`:
`/home/user/.xsession line 19: /nix/store/<hash>-kwin-5.10.3/bin/kwin_x11: No such file or directory`

when I execute `ls -la /run/current-system/sw/bin/kwin_x11` I get:
`/run/current-system/sw/bin/kwin_x11 -> /nix/store/<hash>-kwin-5.10.3-bin/bin/kwin_x11`

Seems like I should specify another package instead of `${pkgs.kwin}`, but not sure what.

**Comment by rycee** [comment]
Ah, you could try `${lib.getBin pkgs.kwin}/bin/kwin_x11`…

**Comment by uvNikita** [comment]
With this configuration applied, after login, I get a black screen. The log output for `journalctl --user -b` looks like this: https://pastebin.com/N9senvFb

**Comment by uvNikita** [comment]
Here is the settings for xserver service from my `/etc/nixos/configuration.nix`:

```
xserver = {
    enable = true;
    layout = "gb";
    libinput = {
      enable = true;
      clickMethod = "clickfinger";
      naturalScrolling = true;
      tapping = false;
    };
    displayManager.sddm.enable = true;
    desktopManager.plasma5.enable = true;
    videoDrivers = [ "intel" ];
};
```

**Comment by rycee** [comment]
Ok, so the problem may be that you are trying to run a whole desktop manager. The way Home Manager does X sessions at the moment doesn't work very well together with that (basically it overrides the whole start up the desktop manager thing). You could attempt to do something like
```
xsession.windowManager = pkgs.plasma5.startkde;
```
but if that doesn't work I'm afraid that the `xsession` option won't work for you. I hope to improve this situation in the future.

**Comment by uvNikita** [comment]
That actually helped :) KDE launched and graphical services seem also work as it should.

Thank you for your help and for this project in general :)

**Comment by rycee** [comment]
Ah, that is very nice! Thanks for reporting this issue and I'm glad to learn it works.
