### ISSUE TITLE
gpg-agent doesn't work out of the box for SSH support

### ISSUE THREAD

**Issue by turion** [rycee/home-manager#292]
When setting `services.gpg-agent.enableSshSupport = true;` it only modifies `~/.gnupg/gpg-agent.conf`, but it doesn't export the `SSH_AUTH_SOCK` and `SSH_AGENT_PID` variables, so running `ssh-add` from the console will cause it not to find the agent.

**Comment by rycee** [comment]
Hmm, it should set the `SSH_AUTH_SOCK` variable:
https://github.com/rycee/home-manager/blob/5641ee3f942e700de35b28fc879b0d8a10a7a1fe/modules/services/gpg-agent.nix#L108-L111

Do you have the `programs.bash.enable` or `programs.zsh.enable` set to `true`? If not did you add
```sh
. "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
```
to your shell configuration (for example `~/.profile` in Bash)?

If either of the bash or zsh enable options above are true could see if `SSH_AUTH_SOCK` is present in the `~/.nix-profile/etc/profile.d/hm-session-vars.sh` file? And if this file is sourced in `~/.profile` or `~/.zshrc`, respectively?

**Comment by turion** [comment]
(Yes, I have `programs.bash.enable`, and it works as expected.) Ah! I didn't `source .profile` in my shell after `home-manager switch`! I thought `source .bashrc` was the right thing to do, which it wasn't. Great, thanks a lot!

**Comment by turion** [comment]
Sorry, it seems like the issue persists. I have to manually `source .profile` every time I open a new console. Is this the expected behaviour? (See my configuration at https://gitlab.com/turion/enigmanix)

**Comment by rycee** [comment]
No, that should not be necessary. The `~/.profile` file should be sourced by Bash automatically when you log in. Perhaps you haven't logged out and back in since enabling gpg-agent?

**Comment by turion** [comment]
I have, and restarted as well a few times. Is my `home.nix` maybe wrong?

**Comment by turion** [comment]
Or is there an interaction with a system-wide installed bash?

**Comment by turion** [comment]
I can confirm that this issue still persists with KDE5 and konsole as well, without a system-wide bash installation.

**Comment by rycee** [comment]
Sorry for the delay. Quick question, do you have an `~/.xprofile` file? If you do, does it source `~/.profile`? If you don't, or it doesn't source the `~/.profile` file, could you add

```bash
. "$HOME/.profile"
```

to it and try logging out and back in? I've been thinking about what could differ between your and my system and this is the thing I could come up with 🙂

**Comment by turion** [comment]
Indeed I didn't have `.xprofile`, and creating it in the way you said resolved it. Shouldn't home-manager create it instead? Note that I don't configure my xserver with home-manager.

**Comment by rycee** [comment]
Yeah, I'll have to think of some nice way to solve that. I'm a bit adverse of having Home Manager unconditionally manage the `~/.xprofile` file since the user might have their own `~/.xprofile` file that they don't want under HM control.

I suspect this is a documentation issue, something like expanding step 5 to mention `~/.xprofile` in the [installation instructions](https://github.com/rycee/home-manager#installation).

**Comment by rycee** [comment]
I'll close this issue since it's now working for you but I opened the above issue to track the general problem.
