### ISSUE TITLE
Feature Request: Emacs service

### ISSUE THREAD

**Issue by Targuinius** [rycee/home-manager#299]
Currenly there doesn't seem to be a service to start an Emacs daemon with the packages configured in programs.emacs.extraPackages. I have tried to write my own service, but failed miserably, as I am not very good with Nix.

There is also a unit file in the system-wide configuration, but I don't think that can use the home-manager instance of Emacs.

**Comment by rycee** [comment]
Hi. Yeah, you are right on both accounts, there is no Emacs daemon module for HM yet and the NixOS module cannot be used (easily) with the Emacs package produced by HM. I think making a simple systemd service for Emacs shouldn't be terribly tricky. I found a [service file](https://www.emacswiki.org/emacs/EmacsAsDaemon#toc2) on the EmacsWiki and maybe a semi-straight translation like

```nix

{
  systemd.user.services.emacs-daemon = {
    Unit = {
      Description = "Emacs text editor";
      Documentation = "info:emacs man:emacs(1) https://gnu.org/software/emacs/";
    };

    Service = {
      Type = "simple";
      ExecStart = "${pkgs.stdenv.shell} -l -c 'exec %h/.nix-profile/bin/emacs --fg-daemon'";
      ExecStop = "%h/.nix-profile/bin/emacsclient --eval '(kill-emacs)'";
      Restart = "on-failure";
    };

    Install = {
      WantedBy = "default.target";
    };
  };
}
```

might work (note this is completely untested). The only difference from the service from EmacsWiki (beside the paths to the emacs binaries) is that I replaced the `Environment` field by instead running the emacs daemon in a Bash login shell (which should set up your session variables correctly).

So try putting this in your `home.nix` and see how it goes. Like I said it's completely untested so you might have to tweak it a bit.

Eventually I hope we'll have a bundled `services.emacs` module but hopefully you can live with something like this until then. If you clean it up and make a full module of it feel free to open a PR! 🙂

**Comment by rossabaker** [comment]
This worked for me on emacs 25.3, which is currently on the 18.03 channel.

```nix
{
  systemd.user.services.emacs-daemon = {
    Unit = {
      Description = "Emacs text editor";
      Documentation = "info:emacs man:emacs(1) https://gnu.org/software/emacs/";
    };
    Service = {
      Type = "forking";
      ExecStart = "${pkgs.stdenv.shell} -l -c 'exec %h/.nix-profile/bin/emacs --daemon'";
      ExecStop = "%h/.nix-profile/bin/emacsclient --eval '(kill-emacs)'";
      Restart = "on-failure";
    };
    Install = {
      WantedBy = [ "default.target" ];
    };
  };
}
```

I suspect @rycee's version works on emacs26, as long as `WantedBy` is a list.

**Comment by Jomik** [comment]
This should be closed now, I'd say @rycee
