### ISSUE TITLE
Deprecated "traceValIfNot" in nixpkgs-config option.

### ISSUE THREAD

**Issue by LeOtaku** [rycee/home-manager#301]
When running any home-manager command or using the nixos module I get the following message:

``
trace: Warning: 'traceValIfNot' is deprecated and will be removed in the next release. Please use 'if/then/else' and 'traceValSeq' 1.
``

`traceValIfNot` seems to only be called [here](https://github.com/rycee/home-manager/blob/5ab57f4a873ba333579eddf62f9002d4825b2e35/modules/misc/nixpkgs.nix#L37) so I suspect that line is the problem. Maybe this should be fixed?

**Comment by rycee** [comment]
Thanks for the report! I've replaced the use of `traceValIfNot` in master and hopefully you won't see the warning after your next update 🙂

**Comment by LeOtaku** [comment]
I can confirm that I do no longer see the warning. Thank you for the quick fix!
