### ISSUE TITLE
Path issue

### ISSUE THREAD

**Issue by bumbleblym** [rycee/home-manager#304]
Hi @rycee,

I ran into a path issue when trying to use home-manager to [manage its own config (minimal repro)](https://github.com/bumbleblym/fictional-dollop).

With the repro cloned in ~:
```
$ HOME_MANAGER_CONFIG=~/fictional-dollop/config/nixpkgs/home.nix nix-shell -A install ~/fictional-dollop/home-manager
$ realpath ~/.config
/home/blym/fictional-dollop/config
```

Switching works when passing the resolved config path:
```
$ home-manager -f ~/fictional-dollop/config/nixpkgs/home.nix switch
$ realpath ~/.config
/home/blym/fictional-dollop/config
```

But using the default unresolved config path (~/.config/nixpkgs/home.nix) sets paths relative to the unresolved path:
- It links ~/.config to ~/config, or ~/fictional-dollop/config/nixpkgs/../../config, and
- searches for home-manager in ~/home-manager, or ~/fictional-dollop/config/nixpkgs/../../home-manager
```
$ home-manager switch
$ realpath ~/.config
/home/blym/config
$ home-manager switch
No configuration file found. Please create one at /home/blym/.config/nixpkgs/home.nix
```

Adding `confFile="$(realpath "$confFile")"` [here](https://github.com/rycee/home-manager/blob/06e7d087f29c7890f33e698c2fab073e1a67ce02/home-manager/home-manager#L33-L34) seems to fix the issue, but I'm not sure if that's the correct fix.

**Comment by rycee** [comment]
Thanks for the detailed bug report! It's a neat problem that I haven't thought of before. I implemented a slight variation of your suggested fix in #308. If you can please give it a try.

**Comment by bumbleblym** [comment]
I gave it a try; confirming that #308 _resolves_ the issue. Thank you!

**Comment by rycee** [comment]
Thanks for the confirmation. I've merged it now.
