### ISSUE TITLE
Is it okay to use unstable packages?

### ISSUE THREAD

**Issue by pltanton** [rycee/home-manager#313]
Just to clearify. Is it okay to make modifications, that uses packages (or package's new featuers) from unstable nixpkgs channel, but don't exists in stable channel and make PR to `master` branch?

If it is not may be we can create "unstable" branch to support that feature?

**Comment by rycee** [comment]
Sure, the master branch is tracking Nixpkgs unstable and the release-18.03 branch tracks Nixpkgs 18.03. Currently they are both the same but that is mostly a happy accident.

**Comment by pltanton** [comment]
Thanks! I'll make a few PRs then =)
