### ISSUE TITLE
What is the equivalent of using a modified nixpkgs?

### ISSUE THREAD

**Issue by bbigras** [rycee/home-manager#335]
I'm pretty new to NixOS but I know I can run `nix-instantiate '<nixpkgs>' --eval -A lib.nixpkgsVersion` to figure out the current commit, checkout that commit, do some edits and then do `nixos-rebuild switch -I nixpkgs=/my_own/nixpkgs`.

What would be the equivalent with home-manager? Can I just use a modified nixpkgs?

In this case I wanted to update emacs to 26.1 (maybe it's in unstable) but there would be times where I would want to use my own nixpkgs (when doing my own changes).

**Comment by rycee** [comment]
Give `home-manager -I nixpkgs=/my_own/nixpkgs switch` a try. The `-I` option has to be before the `switch` subcommand due to some limitations in home-manager's option parsing.

**Comment by bbigras** [comment]
It seems to work. Thanks!
