### ISSUE TITLE
bspwm integration

### ISSUE THREAD

**Issue by NefixEstrada** [rycee/home-manager#359]
Hey! I just started using home-manager today and I'm loving it! There's one issue though: there's no support for bspwm. It would be great to have since it's one of the most popular WM out there. I would be happy to write it, but I have no clue where to start and no idea how nix works (I started with NixOS two days ago). Thanks in advance!

**Comment by rycee** [comment]
Thanks for the interest! Unfortunately I know very little about bspwm so I can't say how complicated it would be to make a module. But have a look at the files [awesome.nix](https://github.com/rycee/home-manager/blob/master/modules/services/window-managers/awesome.nix) or [xmonad.nix](https://github.com/rycee/home-manager/blob/master/modules/services/window-managers/xmonad.nix) and see if they seem suitable as a base for a bspwn module. The [i3.nix](https://github.com/rycee/home-manager/blob/master/modules/services/window-managers/i3.nix) file is quite a bit more advanced so it is probably not a good place to start.

**Comment by JonathanReeve** [comment]
This would be great! As of yet, I haven't been able to get bspwm to play nice with home-manager. If there were a switch for this, it'd make it a lot easier.

**Comment by NefixEstrada** [comment]
I've almost finished with the bspwm module (with my crappy nix code :P) I just need to create the option for the rules and it's going to be finished. The sxhkd module still needs to be created though (I think that tomorrow it'll be finished (or at least started)

**Comment by rycee** [comment]
Yep, nice work getting it going so quickly!

**Comment by JonathanReeve** [comment]
@NefixEstrada, how's this coming along? I'd be happy to help test this whenever it's in a testable state.

**Comment by JonathanReeve** [comment]
Please do. Commit whatever you have left and I'll see if I can hack away on it. I don't really know what I'm doing, either, but it'll be a learning experience to try.

**Comment by NefixEstrada** [comment]
I've been really busy these days. I'll try to do it tomorrow morning

**Comment by NefixEstrada** [comment]
Okay, I've commited all the work it's done. Check #362 for the repository. In the last commit message, I've explained a bit how the integration is done and in which status is it. Sorry for dropping it :(

**Comment by JonathanReeve** [comment]
Ok great. It looks like the BSPWM integration is pretty much done, except for maybe one part? And the config is there for SXHKD, but it's not yet formatted into config files? Looks great. I might not have much time to look into this soon, so everyone else feel free, but when I have time, I'll look into it.

**Comment by rycee** [comment]
Closed by #981.
