### ISSUE TITLE
Potential PATH issue in Polybar module? 

### ISSUE THREAD

**Issue by JonathanReeve** [rycee/home-manager#364]
I have a rather strange bug that only shows up when I'm running a custom script in polybar, and only when I run polybar as a service (as generated by home-manager). I describe [the issue here in the Polybar issue tracker](https://github.com/jaagr/polybar/issues/1405), but I have a feeling it might be more of a home-manager issue than a polybar issue? I can't tell. 

My best guess is that this is a PATH thing--that polybar is trying to run some commands, but doesn't have those commands in its path.

**Comment by rycee** [comment]
The services running under systemd are typically having a very reduced PATH. In my case
```console
$ systemctl --user show-environment | grep ^PATH=
PATH=/nix/store/920k63py2w97xpfyb5ps9l6wbidvzfjz-coreutils-8.29/bin:/nix/store/hlgglqv1vm88frmysq2laifavxjhaf55-findutils-4.6.0/bin:/nix/store/iywd02hbirf506q740z0v6zyrvsa9gcf-gnugrep-3.1/bin:/nix/store/wkgszaq2dkc4asapcbx6ypd7xdnzad9f-gnused-4.4/bin:/nix/store/3hmpbbcv1db42m9g34c9g4q6qinw50x4-systemd-237/bin:/nix/store/920k63py2w97xpfyb5ps9l6wbidvzfjz-coreutils-8.29/sbin:/nix/store/hlgglqv1vm88frmysq2laifavxjhaf55-findutils-4.6.0/sbin:/nix/store/iywd02hbirf506q740z0v6zyrvsa9gcf-gnugrep-3.1/sbin:/nix/store/wkgszaq2dkc4asapcbx6ypd7xdnzad9f-gnused-4.4/sbin:/nix/store/3hmpbbcv1db42m9g34c9g4q6qinw50x4-systemd-237/sbin
```
But it does include coreutils so, e.g.,
```console
$ /nix/store/920k63py2w97xpfyb5ps9l6wbidvzfjz-coreutils-8.29/bin/env --version
env (GNU coreutils) 8.29
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Richard Mlynarik and David MacKenzie.
```

On the other hand, the polybar service seems to set the `PATH` variable and therefore probably overwrites the ambient setting.

You could try doing `echo $PATH > /tmp/foo` in your script to see what it says.

**Comment by JonathanReeve** [comment]
I think my script needed `emacsclient`, and `head` and one or two more. I rewrote the script (in BASH), removing the utilities, and expanding `emacsclient` to the full path (i.e. `/run/current-system/sw/...`), and now it works! Thanks for the help with this, @rycee.

**Comment by rycee** [comment]
Glad it worked out for you! 👍
