### ISSUE TITLE
emacs packages are not linked

### ISSUE THREAD

**Issue by BrianHicks** [rycee/home-manager#370]
In [my configuration](https://github.com/BrianHicks/dotfiles.nix) (with home-manager pinned at 99c9009 as per the README) I have the following included:

```nix
{ pkgs, ... }:

{
  programs.emacs.enable = true;
  programs.emacs.extraPackages = epkgs: [
    epkgs.evil
  ];

  # home.file.".emacs.d" = {
  #   source = ./emacs;
  # };
}
```

This *does* install Emacs, and I can run it… but when I build and look `result`, I only have these files (looks like because I'm also using the `programs.git`):

```
$ tree result/home-path/share/emacs/site-lisp
result/home-path/share/emacs/site-lisp
├── git-blame.el -> /nix/store/pknzw3kh5mwzrgddfa7ldgl3rz6bqavc-git-2.18.0/share/git/contrib/emacs/git-blame.el
└── git.el -> /nix/store/pknzw3kh5mwzrgddfa7ldgl3rz6bqavc-git-2.18.0/share/git/contrib/emacs/git.el

0 directories, 2 files
```

In fact, I can't find any file with anything to do with evil anywhere in the result. Am I doing something weird in my configuration?

**Comment by rycee** [comment]
No, it's just a bit confusing because the packages you specify for the Emacs package will not actually be installed to your profile. Instead they are just put in the Nix store and the path to them is put in the emacs wrapper script. So
```console
$ cat $(which emacs)
#! /nix/store/czx8vkrb9jdgjyz8qfksh10vrnqa723l-bash-4.4-p23/bin/bash -e
export EMACSLOADPATH=$EMACSLOADPATH${EMACSLOADPATH:+':'}'/nix/store/ra5098pi253f690fj57xbczn45bf5lxy-emacs-packages-deps/share/emacs/site-lisp:'
exec "/nix/store/7ibw81cqgx32cr95l82yqbi67zzg8wjv-emacs-25.3/bin/emacs"  "${extraFlagsArray[@]}" "$@"
$ ls /nix/store/ra5098pi253f690fj57xbczn45bf5lxy-emacs-packages-deps/share/emacs/site-lisp{,/elpa}
/nix/store/ra5098pi253f690fj57xbczn45bf5lxy-emacs-packages-deps/share/emacs/site-lisp:
elpa          nyan-mode.elc  site-start.elc
nyan-mode.el  site-start.el  subdirs.el

/nix/store/ra5098pi253f690fj57xbczn45bf5lxy-emacs-packages-deps/share/emacs/site-lisp/elpa:
ace-window-20180607.1223
ac-php-core-20180629.144
adoc-mode-20160314.1430
…
```

If you do something like the above I'm sure you'll find evil.

**Comment by BrianHicks** [comment]
oh, how slick! What a cool way to do things!

I realize now that I didn't share enough context: I looked in site-lisp because Emacs could not load some libraries. But evil is indeed in the location you told me! So I'll look elsewhere.

Thanks for home-manager. This is very fun to use. ❤️

**Comment by rycee** [comment]
Glad you like it! And good luck with finding the issue with the Emacs library loading.
