### ISSUE TITLE
Few questions of using home-manager as nixos module

### ISSUE THREAD

**Issue by gnidorah** [rycee/home-manager#373]
1. The guide says that I should do
```nix
      imports = [
        "${builtins.fetchTarball https://github.com/rycee/home-manager/archive/master.tar.gz}/nixos"
      ];
```
Though I want to use source revision that home-manager in nixpkgs uses, so something like
```nix
      imports = [
        "${pkgs.home-manager.src}/nixos"
      ];
```
However this way I get `infinite recursion` when doing `nixos-rebuild switch`. What would be the proper way for that?

2. I'm exporting `hm-session-vars.sh` globally because 1. I don't know a local way that is compatible with my sh imcompatible shell (fish) 2. i'm the only user so I don't care
Here's the way
home.nix
```nix
home.file.".profile".source = "${config.home.profileDirectory}/etc/profile.d/hm-session-vars.sh";
```
configuration.nix
```nix
environment.extraInit = builtins.readFile /home/gnidorah/.profile;
```
My question here is how to directly get `profileDirectory` value in configuration.nix without that .profile dance

**Comment by rycee** [comment]
For 1 I'm not entire certain but I think it is because 
```nix
imports = [ "${pkgs.home-manager.src}/nixos" ];
```
will be interpreted sort of like
```nix
imports = [ "${config._module.args.pkgs.home-manager.src}/nixos" ];
```
and since the `config` variable cannot be populated until all imports are accounted for we're ending up in a loop.

To break it I guess it is best to import Nixpkgs yourself. I.e., doing something like
```nix
"${(import <nixpkgs> {}).pkgs.home-manager.src}/nixos"
```

**Comment by rycee** [comment]
About 2 I'm not certain. I've never used fish but in the discussion about the Home Manager fish module [I found](https://github.com/rycee/home-manager/pull/337#discussion_r209776299) something called [bass](https://github.com/edc/bass). Maybe adding something like
```fish
bass source "${config.home.profileDirectory}/etc/profile.d/hm-session-vars.sh"
```
to your fish configuration could work?

**Comment by gnidorah** [comment]
@rycee Thanks much for the help! And thanks for the second idea, thats what actually NixOS fish module does for initialization scripts, though via [fish-foreign-env](https://github.com/oh-my-fish/plugin-foreign-env) instead of bass. I've created a PR that adds `hm-session-vars.sh` initialization to fish home-manager module
