### ISSUE TITLE
Feature Request: Add tmux integration

### ISSUE THREAD

**Issue by stites** [rycee/home-manager#385]
I found this repo when trying to bundle tmuxplugins with tmux and first found https://github.com/pjan/nix/blob/master/config/nix-darwin/modules/tmux.nix I'm not 100% if this is for nixos, osx, or home-manager, but I am hoping it won't be too hard to port. I'm fairly new to nix and don't mind doing this myself, but a little pointer might be nice!

**Comment by rycee** [comment]
This appears to be for the nix-darwin [tmux module](https://github.com/LnL7/nix-darwin/blob/master/modules/programs/tmux.nix). I had a quick look at it and I think it would be very simple to port to Home Manager. Mostly a matter of changing the config section like, for example, changing
```nix
environment.systemPackages = [ tmux ];
```
to
```
home.packages = [ tmux ];
```

and a few of the options to better fit the HM style. E.g., the `programs.tmux.tmuxConfig` option we would call `programs.tmux.extraConfig`.

**Comment by rycee** [comment]
I'll close this because the PR was merged. Thanks again! :+1:
