### ISSUE TITLE
Run a command after creating a profile

### ISSUE THREAD

**Issue by jokogr** [rycee/home-manager#386]
Hello,

I would like to create a cache for the MIME applications defined in `~/.nix-profile/share/applications` (`~/.nix-profile` is a symlink to `/nix/var/nix/profiles/per-user/*username*/profile`), I need something to be run after the directory is created, e.g. for `/run/current-system/sw/share` this is done in `nixos/modules/config/xdg/mime.nix` as follows:

```
    environment.extraSetup = ''
      if [ -w $out/share/applications ]; then
        ${pkgs.desktop-file-utils}/bin/update-desktop-database $out/share/applications
      fi
```

**Comment by rycee** [comment]
There is no such option currently in Home Manager. It would be simple to add but would only affect packages installed through Home Manager, i.e., if you do `nix-env -iA` or something to install packages to your `~/.nix-profile` they would not be included in the cache file.

**Comment by jokogr** [comment]
Affecting only packages installed through Home Manager is fine, any idea how to do so?
