### ISSUE TITLE
using HM nixos module, how to access nixos config?

### ISSUE THREAD

**Issue by kalbasit** [rycee/home-manager#393]
Suppose that I have the following in my `configuration.nix`

```nix
home-manager.users.kalbasit = import ./home-cfg.nix;
```

how can I access nixos top-level config from within `home-cfg.nix`? In particular, I need access to `config.networking.hostname` so I can have different i3 monitor settings per host.

**Comment by rycee** [comment]
I think the easiest is to add a function argument to the HM configuration. That is, to have something like
```nix
systemConfig:
{ pkgs, ... }:

{
  # HM configuration. For example,
  home.file."the-hostname".text = systemConfig.networking.hostName;
}
```
then change your import line to
```nix
home-manager.users.kalbasit = import ./home-cfg.nix config;
```

**Comment by kalbasit** [comment]
@rycee thank you that worked for the `home-cfg.nix` but I can't seem to access the same variable from inside a file that's sourced via `imports`. Getting an error `attribute 'systemConfig' missing, at /nix/store/x9b0f3rpbp0i37h9brkbd6wi4hf2jsr5-source/lib/modules.nix:163:28`

I've opened a PR for my system [here](https://github.com/kalbasit/system/pull/49/files) with my changes so far. Thx for your help.

**Comment by LightDiscord** [comment]
I had to do something like that in my dotfiles, the easiest way I found was with this trick.

```nix
{ ... }:

let
	sysconfig = (import <nixpkgs/nixos> {}).config;
in {
	# HM configuration. For example,
	home.file."the-hostname".text = sysconfig.networking.hostName;
}
```

**Comment by kalbasit** [comment]
@LightDiscord nice! This worked for me as well

```nix
{ sysconfig ? (import <nixpkgs/nixos> {}).config, ... }:

{
	# HM configuration. For example,
	home.file."the-hostname".text = sysconfig.networking.hostName;
}
```

**Comment by kalbasit** [comment]
@LightDiscord @rycee I found a better way to pass the NixOS config around.

First, I created a new option in NixOS config to which I assign a function that takes nixosConfig and returns the actual home-manager function.

```nix
# /etc/nixos/configuration.nix
# This is not tested, and only written as an illustration, see my actual files shown below.

{ config, lib, ...}:

with lib;

{
  options.mine.home-manager.config = mkOption {
    default = { nixosConfig }: {...}: {};
    description = ''
      Function that returns the Home Manager configuration.
    '';
  };

  config = {
    mine.home-manager.config = { nixosConfig }: { ... }: {
      options.mine.nixosConfig = mkOption {
        default = {};
        defaultText = ''
          NixOS configuration. On NixOS machines, it should be the config itself.
          On non-NixOS machines, all the required keys must be set manually.
        '';
      };

      config = {
        mine.nixosConfig = nixosConfig;

        # access the hostname through mine.nixosConfig.networking.hostName
      };
    };
  };
}
```

Links to my config:
- [`options.mine.home-manager.config`](https://github.com/kalbasit/system/blob/8aafea30f1fcf81e752e844c6cfba26c82d8a811/modules/nixos/general/home-manager.nix#L13-L18).
- [`mine.home-manager.config`](https://github.com/kalbasit/system/blob/8aafea30f1fcf81e752e844c6cfba26c82d8a811/hosts/hades/home.nix#L1-L19)
- [`options.mine.nixosConfig`](https://github.com/kalbasit/system/blob/8aafea30f1fcf81e752e844c6cfba26c82d8a811/modules/home/generic/nixos.nix#L6-L12)

**Comment by workflow** [comment]
There is also `_module.args` which can be populated like this in the flake module version:

```
          home-manager.nixosModules.home-manager
          {
            home-manager = {
              ...
              extraSpecialArgs = {
                hostName = "myHost";
              };
            };
          }
```

Then every home manager module and sub-module will have `hostName` available as an extra argument to its function:

```
{ lib, pkgs, hostName, ... }:

// hostName is available here and evaluates to "myHost"
```

This is the documentation for `_module.args`:

![image](https://user-images.githubusercontent.com/1276854/192105356-97893e60-6d2e-46ea-beb5-ae1e6a16689b.png)

**Comment by rycee** [comment]
For anybody happening to end up in here. There is since quite some time an module argument attribute `osConfig` injected when using Home Manager as a NixOS or nix-darwin module.

That is, instead of starting your configuration with something like

    { lib, pkgs, ... }:

start it with

    { lib, pkgs, osConfig, ... }:

Then you should be able to access the system configuration through the `osConfig` variable.

**Comment by zmberber** [comment]
@rycee

> start it with
> 
> ```
> { lib, pkgs, osConfig, ... }:
> ```
> 
> Then you should be able to access the system configuration through the `osConfig` variable.

this should be documented in Appendix A as well, perhaps.
