### ISSUE TITLE
home-manager as pure configuration manager?

### ISSUE THREAD

**Issue by gnidorah** [rycee/home-manager#399]
Hi.

Is it possible to say home-manager not to propagate packages listed in home-manager modules under `home.packages`?

Example case why this may be needed:

Case 1: I'm **not** using home-manager as nixos module. I've just built user configuration files with it, and don't call home-manager anymore, while I do NixOS updates from time to time. So I suppose old user packages will continue to be propagated in my user $PATH until I'll do `home-manager switch` manually

Case 2: I'm using home-manager as nixos module. But that will break on packages that call `dconf`, like `gnome-terminal` https://github.com/rycee/home-manager/issues/252#issuecomment-385797016

If there would be a way not to install packages declared in home-manager modules, then I could just add them into main nixos configuration and go with Case 1 solution

Of course it would be better to fix dconf case but I've no idea if that possible.

**Comment by rycee** [comment]
I haven't tested it but something like
```nix
home.packages = mkForce [];
```
might do it.

**Comment by gnidorah** [comment]
@rycee Cool, thanks! That did the trick!

**Comment by teto** [comment]
@rycee I've created a wiki page with a FAQ https://github.com/rycee/home-manager/wiki and this issue as an entry.
I plan to put some mail configuration examples there as well.

**Comment by rycee** [comment]
@teto Cool, thanks! Can also add to the [FAQ.md](https://github.com/rycee/home-manager/blob/master/FAQ.md) file.
