### ISSUE TITLE
home-manager switch fails

### ISSUE THREAD

**Issue by jpotier** [rycee/home-manager#40]
Hey, I've been facing this error after running `home-manager switch` recently. I'm using the nixos-unstable channel.

```
these derivations will be built:
  /nix/store/5m55psj9v5ni8djb8zlh4j5g4krsm430-home-manager-path.drv
  /nix/store/vs9zrpash3c7iqamhn2qy1wfcycdkaba-activation-script.drv
  /nix/store/nbrg4ahpvn67q9diqz82sh079jaff4ba-home-manager-generation.drv
building path(s) ‘/nix/store/cnbpx3ljhg3hxbnjsfnsww48ifw3dcgl-home-manager-path’
Use of uninitialized value $stat2 in numeric ne (!=) at /nix/store/9g4wc31j7a2xp22xpgwr0qssfxahxdzl-builder.pl line 74.
Use of uninitialized value $stat1 in numeric ne (!=) at /nix/store/9g4wc31j7a2xp22xpgwr0qssfxahxdzl-builder.pl line 74.
collision between `/nix/store/5w4m6vf5lawhbhfrgv6b55gg5kcpczcs-xmonad-with-packages/share/man' and `'
builder for ‘/nix/store/5m55psj9v5ni8djb8zlh4j5g4krsm430-home-manager-path.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/vs9zrpash3c7iqamhn2qy1wfcycdkaba-activation-script.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/nbrg4ahpvn67q9diqz82sh079jaff4ba-home-manager-generation.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/nbrg4ahpvn67q9diqz82sh079jaff4ba-home-manager-generation.drv’ failed

```

I have trouble determining if this comes from home-manager at all, I'll check more thouroughly, but in the meantime, if you know this, please help : )

**Comment by rycee** [comment]
Hmm, have you recently started using xmonad through Home Manager? If so maybe you still have an xmonad installed through nix-env? What does `nix-env -q` say?

**Comment by jpotier** [comment]
```
$ nix-env -q
home-manager-path
```

**Comment by rycee** [comment]
Hmm, mind sharing your Home Manager configuration?

**Comment by jpotier** [comment]
Sure: http://lpaste.net/8226369467274231808

**Comment by rycee** [comment]
Very peculiar! I created a container and tried to switch to your configuration, it worked perfectly fine for me (I just commented out `(python3.withPackages (ps: with ps; [ python-tasklib ]))` and `exa` from `home.packages`) but I'm using NixOS 17.03. Switching the container to Unstable gives the same error as you get.

Have to go now but tomorrow I'll try to figure out what's going on.

**Comment by rycee** [comment]
Got curious and checked it out anyway :-)

It seems like a problem in Nixpkgs, see https://github.com/NixOS/nixpkgs/issues/27982, so I would suggest to close this issue and hope for a fix in Nixpkgs.

**Comment by jpotier** [comment]
Thanks for checking it out!

**Comment by rycee** [comment]
Just to add. If you figure out a workaround for this issue and Nixpkgs is slow to add a fix please let me know and we'll try to add the workaround into home manager.

**Comment by jpotier** [comment]
So xmonad-with-packages works without problem when used in my configuration.nix (at least when it is called from `service.xserver.windowManager.xmonad` defined [here](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/window-managers/xmonad.nix)… I'm don't yet see what is so different between the two approaches.

**Comment by jpotier** [comment]
It is fixed now, can't really say why. Did you change something on your side?

**Comment by rycee** [comment]
No, I don't think any recent change in Home Manager would affect this. I imagine something changed in Nixpkgs. In any case, I'm glad it now works for you! :-)
