### ISSUE TITLE
Check if line editing is enabled in bash session

### ISSUE THREAD

**Issue by alexvorobiev** [rycee/home-manager#401]
I tried to use `enableBashIntegration` with `fzf` and got a bunch of `warning: line editing not enabled` warnings in the emacs shell. I was also unable to initiate x2go session which treated the warnings as connection errors. It turned out that that the current implementation of the bash module in `home-manager` checks for the presence of `PS1` as an indicator of interactive session and puts the commands from `initExtra` in a corresponding `if` statement (https://github.com/rycee/home-manager/blob/master/modules/programs/bash.nix#L158). Unfortunately in order for the `bind` command (which is used by the bash integration script in `fzf` to add some key combinations) to work having an interactive session is not enough. In addition the bash session has to have line editing enabled. So I ended up setting `enableBashIntegration` to `false` and adding these lines to `bashExtra`:
```
if [[ "$(set -o | grep 'emacs\|\bvi\b' | cut -f2 | tr '\n' ':')" != 'off:off:' ]]; then
   . ${pkgs.fzf}/share/fzf/completion.bash
   . ${pkgs.fzf}/share/fzf/key-bindings.bash
fi
```

Can something like that be added to `home-manager`'s bash module for the cases when bind command is used? Is there a better way to check if the line editing is enabled?

**Comment by alexvorobiev** [comment]
`$-` will have `i` for all interactive sessions regardless of the state of the line editing. For instance, emacs shell has it as `himBH`. `bind` is a very peculiar command for which having an interactive session is not enough. That's why my ugly snippet checks for the state of the both line editing options - vi and emacs. I think I now found a much better way:

```
if [[ "${SHELLOPTS}" =~ :(emacs|vi): ]] ; then 
   . ${pkgs.fzf}/share/fzf/completion.bash
   . ${pkgs.fzf}/share/fzf/key-bindings.bash
fi
```

**Comment by marsam** [comment]
I think checking if line editing is available is outside of the scope of home-manager. 
For your issue you can use the following:
```bash
if [ "$TERM" != "dumb" ]; then
  . ${pkgs.fzf}/share/fzf/completion.bash
  . ${pkgs.fzf}/share/fzf/key-bindings.bash
fi
```

**Comment by marsam** [comment]
@alexvorobiev sorry I misunderstood what you meant, would you mind giving https://github.com/rycee/home-manager/pull/406 a try?

**Comment by teto** [comment]
@marsam I think @alexvorobiev 's solution seems better since it actually checks for the setting instead of relying on some convention ?

**Comment by marsam** [comment]
Sorry for the delay. I think for practical terms they have the same effect; but I'm inclined to check $TERM because when nix-shell starts uses [`bash --rcfile TMPRC`](https://github.com/nixos/nix/blob/f90a67e24d906bdb86c86b9d1c7e6307aeb6ff7c/src/nix-build/nix-build.cc#L440), which starts bash with line editing, for instance when starting nix-shell under Emacs with the following snippet:
```elisp
(let ((explicit-shell-file-name "nix-shell")
      (explicit-nix-shell-args nil))
  (shell "*nix-shell*"))
```
still shows the warnings:
![image](https://user-images.githubusercontent.com/65531/47676263-20f99f00-db8a-11e8-8028-c64dc80af460.png)
Besides that inconvenience, I don't mind updating the PR with the snippet suggested by @alexvorobiev 
```diff
diff --git a/modules/programs/fzf.nix b/modules/programs/fzf.nix
index 7279d90..7ff2a12 100644
--- a/modules/programs/fzf.nix
+++ b/modules/programs/fzf.nix
@@ -122,13 +122,17 @@ in
       );

     programs.bash.initExtra = mkIf cfg.enableBashIntegration ''
-      . ${pkgs.fzf}/share/fzf/completion.bash
-      . ${pkgs.fzf}/share/fzf/key-bindings.bash
+      if [[ ":$SHELLOPTS:" =~ :(vi|emacs): ]]; then
+        . ${pkgs.fzf}/share/fzf/completion.bash
+        . ${pkgs.fzf}/share/fzf/key-bindings.bash
+      fi
     '';

     programs.zsh.initExtra = mkIf cfg.enableZshIntegration ''
-      . ${pkgs.fzf}/share/fzf/completion.zsh
-      . ${pkgs.fzf}/share/fzf/key-bindings.zsh
+      if [[ $options[zle] = on ]]; then
+        . ${pkgs.fzf}/share/fzf/completion.zsh
+        . ${pkgs.fzf}/share/fzf/key-bindings.zsh
+      fi
     '';
   };
 }
```

**Comment by rycee** [comment]
@marsam You still get the "line editing not enabled" in Emacs when using the `:$SHELLOPTS: =~ :(vi|emacs):` test? I just tried it and for me it worked fine. In the nix-shell you gave above I have
```console
[nix-shell:~]$ echo $SHELLOPTS
braceexpand:histexpand:history:ignoreeof:interactive-comments:monitor:pipefail
[nix-shell:~]$ echo $TERM
dumb
[nix-shell:~]$ echo $INSIDE_EMACS
26.1,comint
```

**Comment by rycee** [comment]
I think I will merge the last patch of @marsam, which follows the suggestion of @alexvorobiev. Mainly because of the more direct check as pointed out by @teto.

I also noticed this:
```console
$ bash --noediting 
bash: bind: warning: line editing not enabled
bash: bind: warning: line editing not enabled
bash: bind: warning: line editing not enabled
bash: bind: warning: line editing not enabled
bash: bind: warning: line editing not enabled
bash: bind: warning: line editing not enabled
$ echo $TERM
xterm-256color
```
With the `:$SHELLOPTS: =~ :(vi|emacs):` check it does
```console
$ bash --noediting 
$ echo $TERM
xterm-256color
```
