### ISSUE TITLE
failed install on Ubuntu 18.04

### ISSUE THREAD

**Issue by tbenst** [rycee/home-manager#431]
Hello, I'm a new Nix user, and would love to give home-manager a try. Let me know how I can help troubleshoot the below? I was following the guide on the README (understanding that it's only been tested on NixOS). Many thanks!

https://gist.github.com/tbenst/39307aa5dd772c1766b8edd1c234c221#file-gistfile1-txt-L640

**Comment by sboosali** [comment]
It's a bug (or typo) in your `home.nix`.

Somewhere, you're writing the following (or the dynamic equivalent thereof):

`programs.urxvt.ints`

but `programs.urxvt` doesn't have an `ints` field:

https://rycee.gitlab.io/home-manager/options.html#opt-programs.urxvt.enable

**Comment by rycee** [comment]
@tbenst Are you having an old Nixpkgs, perhaps version 17.09? The Home Manager master branch is only "officially" supporting Nixpkgs unstable although it currently is compatible with Nixpkgs 18.09.

**Comment by tbenst** [comment]
Yes, I was on an old version and updating fixed it. Working perfectly, thank you!
