### ISSUE TITLE
Compton Mesa 18 allow_rgb10_configs=false 

### ISSUE THREAD

**Issue by dali99** [rycee/home-manager#441]
Using compton and mesa 18 can result in colors being wrong, this is fixed by launching compton with an enviroment variable `allow_rgb10_configs=false compton`

This option is in [nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/x11/compton.nix#L243) enabled by default if the glx renderer is used, the renderer home-manager uses by default.

I'm very new to nix, so I'm not quite sure how I could help fix this!

**Comment by rycee** [comment]
I attempted fixing it and it seems to work for me. Please give it a try now. Many thanks for reporting the bug and taking the time to look up the corresponding solution in Nixpkgs!

**Comment by dtzWill** [comment]
FWIW I think this won't happen if you use the newer compton fork (`compton-git`)-- which IMO should probably be made the default soon, should make a PR for that (to nixpkgs).  Anyway might be worth trying, although I don't know that we lose much for now with the environment variable approach.
