### ISSUE TITLE
owncloud-client always ask for password

### ISSUE THREAD

**Issue by M-Gregoire** [rycee/home-manager#442]
*Summary*
This issue is closely related to [https://github.com/NixOS/nixpkgs/issues/38266](#38266).

The owncloud-client never remembers my password and ask for it at every reboot.

**What I tried**
I've enable `gnome-keyring` and `owncloud-client` services. I've also installed `gnome3.libgnome-keyring`.

I've also tried moving everything out of `home-manager` to the `configuration.nix` file but I have the exact same problem, thus, I don't think this is a problem with the home-manager module.

I'd be really interested to see if anyone successfully made it work.

Thank you

**Comment by gmarmstrong** [comment]
I encountered this bug as well. I found [this post](https://github.com/NixOS/nixpkgs/issues/38266#issuecomment-439633394) in that thread very helpful, which I implemented in `home.nix` with:

```
  nixpkgs.overlays = [
    (self: super: {
      nextcloud-client = super.nextcloud-client.override {
        withGnomeKeyring = true;
        libgnome-keyring = self.gnome3.libgnome-keyring;
      };
    } )
  ];```

This basically gives Nix instructions to provide `gnome-keyring` to `nextcloud-client`, and also to replace `libgnome-keyring2` with `gnome3.libgnome-keyring`.

**Comment by M-Gregoire** [comment]
Thanks a lot! I just adapted it for owncloud :
```
  nixpkgs.overlays = [
    (self: super: {
      owncloud-client = super.owncloud-client.override {
        withGnomeKeyring = true;
        libgnome-keyring = self.gnome3.libgnome-keyring;
      };
    } )
  ];
```

It's working perfectly :).

Thank you for taking the time to help!

**Comment by M-Gregoire** [comment]
Little update:
I previously fixed my issue using `kwallet` and when trying your fix, I forgot to remove one component so actually it doesn't work with only `gnome-keyring` and `owncloud-client`.

After looking at `nixpkgs`, `nextcloud-client` offers some build inputs:
https://github.com/M-Gregoire/nixpkgs/blob/master/pkgs/applications/networking/nextcloud-client/default.nix#L22
That `owncloud-client` doesn't have:
https://github.com/M-Gregoire/nixpkgs/blob/master/pkgs/applications/networking/owncloud-client/default.nix

However I was planning on migrating to `nextcloud-client` anyway so this is not a problem in my case. In order to make `owncloud-client` work with `gnome-keyring` a PR is needed (or use `kwallet`).
