### ISSUE TITLE
Add Sway support

### ISSUE THREAD

**Issue by M-Gregoire** [rycee/home-manager#454]
*Summary*

I'm quite new to Nixos and discovered home-manager: it's amazing! Thank you for this beautiful piece of software.

One thing I would love to see added to it would be a Sway module (Sway is tiling Wayland compositor and a drop-in replacement for the i3 window manager for X11, see https://swaywm.org/).
I'm not experienced enough to do it myself (yet!) but I will gladly contribute if needed.

Thank you

**Comment by rycee** [comment]
Yeah, I also like to have a better Wayland experience and hope to work a bit on that soon.

It's unlikely that I will add modules for any particular compositor, though. So any help with that would be much appreciated.

**Comment by M-Gregoire** [comment]
It's not as easy as some internal tools, such as `i3-msg` are replaced. See https://github.com/swaywm/sway/wiki/i3-Migration-Guide

**Comment by bbigras** [comment]
If you didn't know you can use sway on NixOS with an overlay: https://github.com/colemickens/nixpkgs-wayland

I use it in my configuration.nix. The dev might switch to a NUR repo.

**Comment by glglwty** [comment]
Sway also needs root privilege, presumably because it replaces xserver as well.

**Comment by t184256** [comment]
@glglwty no, it does not

**Comment by bram209** [comment]
#829 recently got merged, this issue can be closed
