### ISSUE TITLE
Shouldn't keybase.enable add keybase to home.packages? 

### ISSUE THREAD

**Issue by stites** [rycee/home-manager#455]
I just tried migrating keybase to home-manager and noticed that [keybase.nix](https://github.com/rycee/home-manager/blob/master/modules/services/keybase.nix) only creates a service which points to `pkgs.keybase`, however I don't think the CLI is added to the shell environment. I use keybase in a very low capacity, so I don't know if this is correct or not. @tadfisher

**Comment by rycee** [comment]
Seems reasonable to me. Is it the same `pkgs.keybase` that provides the CLI?

**Comment by stites** [comment]
yes, I believe so. I don't have too much time right now, but I'll try to submit a patch later.

**Comment by rycee** [comment]
Closing this because the above PR was merged.
