### ISSUE TITLE
pasystray not detecting other software

### ISSUE THREAD

**Issue by Amarandus** [rycee/home-manager#461]
Hello,

I am using pasystray (`services.pasystray.enable = true;`) and noticed that it does not detect other tools in the path. The other options are greyed out as described in https://github.com/christophgysin/pasystray/issues/23 . 
I added paprefs and pavucontrol:
```nix
home.packages = with pkgs; [
  pavucontrol
  paprefs
  ];
```

I am using home-manager in my system-wide `configuration.nix` by importing it with `builtins.fetchTarball`.

@pltanton is listed as maintainer, so maybe he can help.

Cheers
Amarandus

**Comment by rycee** [comment]
Please give it a try now. It should also work even if you don't have pavucontrol and paprefs explicitly installed.
