### ISSUE TITLE
attribute ‘activation-script’ missing?

### ISSUE THREAD

**Issue by jpotier** [rycee/home-manager#47]
I get an
`error: attribute ‘activation-script’ missing, at /nix/store/f4nd4xgj5fqdia5h4xml3q7s9z3bnb9r-home-manager.nix:13:4` with the latest master commit https://github.com/rycee/home-manager/commit/4a17d8ef970b7ab9cf99100d06f6734af3ea64cd

This commit builds fine: https://github.com/rycee/home-manager/commit/3bcd9d747b102b825bdf218245652eb763045d6c

**Comment by rycee** [comment]
Sorry! My fault. Please try an update now, hopefully it will work.

**Comment by jpotier** [comment]
Np! Fixed with this commit :)

**Comment by rycee** [comment]
Glad it worked again. Thanks for the quick report!

**Comment by jpotier** [comment]
I'm regularly updating and playing with it, so I'm bound to find with it does not work anymore. You'll know : )
