### ISSUE TITLE
syntax error on home-manager switch

### ISSUE THREAD

**Issue by uvNikita** [rycee/home-manager#48]
It seems it started to happen after this commit: https://github.com/rycee/home-manager/commit/e9ca4305a6bf8727f347c57b65883d2e1e1a5070
```
error: syntax error, unexpected IND_STRING_OPEN, expecting ID or OR_KW or DOLLAR_CURLY or '"', at /nix/store/g7m7q0204dbz6np3wrnjdw92lld99knj-home-manager.nix:9:47
```

I think the problem is in the `''` quotes in this line https://github.com/rycee/home-manager/blob/e9ca4305a6bf8727f347c57b65883d2e1e1a5070/home-manager/home-manager.nix#L9

I would try to fix it, but now since `$ home-manager switch` is not working for me, I'm not sure how to switch to a different version of the home-manager.

**Comment by rycee** [comment]
You should be able to simply run a home-manager from a previous generation. If you have a recent working generation (since e561beab449aebbf30bba34c2294f359c23cbc8d) then the tool should show up if you do
```
$ ls /nix/var/nix/profiles/per-user/$USER/home-manager-*-link/home-path/bin/home-manager
```
If you need an older generation then a more complicated command is necessary:
```
$ grep -o '/nix/store.*home-manager-path' /nix/var/nix/profiles/per-user/$USER/home-manager-*-link/activate | awk '{ print $1"/bin/home-manager" }'
```

**Comment by uvNikita** [comment]
Thank you for advice, it also worked to run this script:
```
/nix/var/nix/profiles/per-user/<user>/home-manager-<gen-num>-link/activate
```
After which I got working home-manager in my PATH and could use it to make a switch :)
