### ISSUE TITLE
Importing home-manager.users.foo configs from files

### ISSUE THREAD

**Issue by kreisys** [rycee/home-manager#483]
Hi!

I'd like to be able to import home-manager configs from GitHub (or anywhere really) when used declaratively. For example:

```nix
{
  home-manager.users.kreisys = builtins.fetchGit https://github.com/kreisys/my-home-manager-config.git;
  home-manager.users.rycee = builtins.fetchGit https://github.com/rycee/your-home-manager-config.git;
  home-manager.users.foo = /home/foo/.config/nixpkgs/home.nix;
  # ... etc
}
```

I'd then expect those to be called in the same way imperative nix would call them. Off the top of my head this would have several benefits:
- Allows using the same home.nix files that users might have already
- Allows users to maintain their own configs
- Avoids confusion with NixOS options altogether
- (... assuming a solution based on `lib.evalModules`) allows using `imports` within user modules 

I've been trying to modify the module so that it takes a `types.either hmModule type.path` but couldn't get it to work so far. Modules still make my head spin 🙃

Is something like that possible somehow? Am I missing anything? Is it a horrible idea?

Cheers

**Comment by rycee** [comment]
Sure, this is a good way to manage the user options. I do something similar in my configuration. But you'll need `import`:
```nix
{
  home-manager.users.kreisys = import (builtins.fetchGit https://github.com/kreisys/my-home-manager-config.git);
  home-manager.users.rycee = import (builtins.fetchGit https://github.com/rycee/your-home-manager-config.git);
  home-manager.users.foo = import /home/foo/.config/nixpkgs/home.nix;
  # ... etc
}
```

**Comment by kreisys** [comment]
Yeah that's the first thing I tried. The problem with that is that it doesn't let you use `imports` within the imported modules. In fact I should add that to my benefits bullet list

**Comment by kreisys** [comment]
Also I figured it out (at least for nix-darwin...). I modified `home-manager.users.foo` so that it takes either old school inline attrset or a list of paths (which are then run through `evalModules`). Do you want a PR?

**Comment by rycee** [comment]
Hmm, what do you mean by "The problem with that is that it doesn't let you use `imports` within the imported modules"? It should be possible to use imports. For example, a system configuration of mine has
```
home-manager.users.rah = import ../user/rah.nix;
```
where `rah.nix` contains
```
imports = [ ./common.nix ./extra-packages.nix ];
```
Or did you mean something else?

**Comment by kreisys** [comment]
That works for you? I'm pretty sure I tried that but I'll double-check.

**Comment by kreisys** [comment]
Yeah that doesn't work for me:

```
$ darwin-rebuild switch                                                                                                                                                                
building the system configuration...
error: The option `home-manager.users.kreisys.imports' defined in `/Users/kreisys/.nixpkgs/common/home-manager.nix' does not exist.
(use '--show-trace' to show detailed location information)
```

Could that be specific to darwin?

**Comment by kreisys** [comment]
It wasn't a function but turning it into one doesn't make a difference. strange 🤷‍♂️

**Comment by rycee** [comment]
I made an experiment. With `home-manager.users.hm-test = import ./test1.nix` I first tried
```nix
# test1.nix content:
{
  imports = [ ./test2.nix ];
}

# test2.nix content:
{
  home.file."TEST".text = "hello";
}
```
and then I got
```
error: The option `home-manager.users.hm-test.imports' defined in `/etc/nixos/configuration.nix' does not exist.
```
similar to the error you got. I then tried converting `test1.nix` to a function (leaving `test2.nix` unchanged):
```nix
# test1.nix content:
{ ... }:
{
  imports = [ ./test2.nix ];
}
```
and then the build works fine, producing the TEST file containing "hello".

**Comment by kreisys** [comment]
Might still be worth mentioning somewhere though!

**Comment by rycee** [comment]
Glad it worked out for you! I'll add a note of this in the [FAQ](https://github.com/rycee/home-manager/blob/master/FAQ.md).
