### ISSUE TITLE
How to use overrideScope' with Emacs configured via programs.emacs

### ISSUE THREAD

**Issue by terlar** [rycee/home-manager#486]
Reading through the documentation at:
https://nixos.org/nixpkgs/manual/#sec-emacs-config

I see that the recommended way to override packages is through the following method:
```nix
overrides = self: super: rec {
  haskell-mode = self.melpaPackages.haskell-mode;
  ...
};
((emacsPackagesNgGen emacs).overrideScope' overrides).emacsWithPackages (p: with p; [
  # here both these package will use haskell-mode of our own choice
  ghc-mod
  dante
])
```

However it seems to be no way to hook into that part via home-manager.

It is possible to set emacs and the last of packages through `package` and `extraPackages`. Perhaps introduce a configuration option called overrides?
If it is defined it would wrap the command with `overrideScope'`.

Is this understanding correct?

**Comment by rycee** [comment]
Yeah, you made a good point! The current design didn't allow such overrides. I added an `programs.emacs.overrides` option in the referenced PR. Can be used like so:
```nix
programs.emacs.overrides = self: super: {
  haskell-mode = self.melpaPackages.haskell-mode;
};
```
