### ISSUE TITLE
file 'home-manager' was not found in the Nix search path

### ISSUE THREAD

**Issue by mehandes** [rycee/home-manager#487]
```
$ nix-shell '<home-manager>' -A install
error: file 'home-manager' was not found in the Nix search path (add it using $NIX_PATH or -I)
```

Hi, I receive the above when trying to install home manager.

**Comment by uvNikita** [comment]
Did you remember to run:

```
$ nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
$ nix-channel --update
```

Because it seems that nix can't find a `home-manager` channel.

**Comment by mehandes** [comment]
Thanks for the quick reply. I have already home-manager channel added:
```
$ nix-channel --list
home-manager https://github.com/rycee/home-manager/archive/master.tar.gz
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

**Comment by rycee** [comment]
@mehandes Does your `NIX_PATH` contain `~/.nix-defexpr/channels`? Running `echo $NIX_PATH` gives me
```console
$ echo $NIX_PATH 
/home/rycee/.nix-defexpr/channels:nixpkgs=/home/rycee/devel/nixpkgs-18.09:nixos-config=/etc/nixos/configuration.nix
```
I did notice that if you don't have a `~/.nix-defexpr/channels` directory before doing `nix-channel --add` then it is necessary to log out and back in for it to show up in `NIX_PATH`.

**Comment by mehandes** [comment]
@rycee Yes, it does
```
$ echo $NIX_PATH
nixpkgs=/home/mc/.nix-defexpr/channels/nixpkgs
$ nix-shell '<home-manager>' -A install
error: file 'home-manager' was not found in the Nix search path (add it using $NIX_PATH or -I)
```

**Comment by rycee** [comment]
Hmm, from what I can tell it is actually missing the entry I was looking for. I believe it would work if it was set to

    /home/mc/.nix-defexpr/channels:nixpkgs=/home/mc/.nix-defexpr/channels/nixpkgs

Did you try a relog? Also are you using NixOS or a Nix installation on some other system? 

On December 7, 2018 6:32:10 PM GMT+01:00, Matt <notifications@github.com> wrote:
>@rycee Yes, it does
>```
>$ echo $NIX_PATH
>nixpkgs=/home/mc/.nix-defexpr/channels/nixpkgs
>$ nix-shell '<home-manager>' -A install
>error: file 'home-manager' was not found in the Nix search path (add it
>using $NIX_PATH or -I)
>```
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/rycee/home-manager/issues/487#issuecomment-445306369

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mehandes** [comment]
Yes, I relogged, rebooted and tried even on VPS. I am using `Linux 4.15.0-42-generic #45-Ubuntu SMP`. 

Thanks for the suggestion - I tried 
```
NIX_PATH=/home/mc/.nix-defexpr/channels:nixpkgs=/home/mc/.nix-defexpr/channels/nixpkgs nix-shell '<home-manager>' -A install
```
and it worked, but I don't know why and if I should change the NIX_PATH permanently.

**Comment by willbush** [comment]
> it is necessary to log out and back in for it to show up in `NIX_PATH`.

I had a similar issue when following the install instructions in the readme. However, logging out and back in added `~/.nix-defexpr/channels` and it now works.

**Comment by kerrnelPanic** [comment]
> Hmm, from what I can tell it is actually missing the entry I was looking for. I believe it would work if it was set to /home/mc/.nix-defexpr/channels:nixpkgs=/home/mc/.nix-defexpr/channels/nixpkgs Did you try a relog? Also are you using NixOS or a Nix installation on some other system?
> […](#)
> On December 7, 2018 6:32:10 PM GMT+01:00, Matt ***@***.***> wrote: @rycee Yes, it does ``` $ echo $NIX_PATH nixpkgs=/home/mc/.nix-defexpr/channels/nixpkgs $ nix-shell '<home-manager>' -A install error: file 'home-manager' was not found in the Nix search path (add it using $NIX_PATH or -I) ``` -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#487 (comment)](https://github.com/nix-community/home-manager/issues/487#issuecomment-445306369)
> -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

I faced that problem, too, relog, reboot didn't help. Executing the channel commands with elevated rights did help. I think the [documentation](https://nix-community.github.io/home-manager/index.html#sec-install-nixos-module) is a bit imprecise here, having '$ command someOption', instead of '# command someOption' as examples, so it doesn't point out that you may need elevated rights.
