### ISSUE TITLE
A way to ignore existing folders

### ISSUE THREAD

**Issue by seqizz** [rycee/home-manager#492]
Hi and thanks for this amazing tool. I am currently building my profile.

I am currently using stow and want to eliminate this need. Currently (because of stow) I have the following structure of config files:
```
./yubikey
./yubikey/.config
./yubikey/.config/Yubico
./yubikey/.config/Yubico/u2f_keys
./yubikey/.config/Yubico/YKPersonalization.conf
./firefox
./firefox/.mozilla
./firefox/.mozilla/firefox
./firefox/.mozilla/firefox/profiles.ini
./firefox/.mozilla/firefox/myprofile.default
./firefox/.mozilla/firefox/myprofile.default/chrome
./firefox/.mozilla/firefox/myprofile.default/chrome/userChrome.css
```

(The dotfiles folder itself also self-explanatory with this style.)

Using `stow -t ~ firefox` for example, places related files under .config folder. Stow doesn't care about the existing folders (as long as a real file doesn't conflict with the new symlink) and fills the blanks itself.

Can I somehow achieve the same thing? Giving the .config folder directly causing `Existing file '/home/user/.config' is in the way`. Or should I use something like [grahamc's symlink helper](https://github.com/grahamc/nixos-config/tree/master/packages/symlinks)?

> Edit: Another plus side if there is a way of doing this: We won't need to define every config file one by one if there is some empty folder is already there.

**Comment by rycee** [comment]
Happy to hear you like Home Manager! 😀

I believe what you are looking for is the [`home.file.<name?>.recursive`](https://rycee.gitlab.io/home-manager/options.html#opt-home.file._name__.recursive) option. I think something like
```nix
{
  home.file = [
    {
      target = ".";
      source = ./yubikey;
      recursive = true;
    }
    {
      target = ".";
      source = ./firefox;
      recursive = true;
    }
  ];
}
```
might do the trick. Of course you can probably abstract this a bit if you want:
```nix
{
  home.file = map (source: { inherit source; target = "."; recursive = true; }) [
    ./yubikey ./firefox
  ];
}
```

Everything above is untested but it should work, hypothetically 😉

**Comment by seqizz** [comment]
Hi,

Thanks for the inherit example. This language really dazzles me :smiley: 

The example works for yubikey, since there is no such folder under home. But sadly it doesn't create any symlink for firefox, since I do have .mozilla/firefox directory. That was my intention to ask a way to ignore folders if there was no actual file<->symlink collusion.

Weirdly, I did not get any error this time. It switched to new generation without linking or warnings :neutral_face:

**Comment by seqizz** [comment]
Umm.. Apparently it was working but not the way I thought. I misreported on my previous post by not checking the resulting link's missing dot.

```
/nix/store/1jvkxw7qj0qafc5b6q16al6080dwgdiq-home-manager-generation
Starting home manager activation
Sanity checking oldGenNum and oldGenPath
This is a live run
Using Nix version: nix-env (Nix) 2.1.3
Activation variables:
  oldGenNum=15
  oldGenPath=/nix/store/1jvkxw7qj0qafc5b6q16al6080dwgdiq-home-manager-generation
  newGenPath=/nix/store/1jvkxw7qj0qafc5b6q16al6080dwgdiq-home-manager-generation
  newGenNum=16
  newGenProfilePath=/nix/var/nix/profiles/per-user/gurkan/home-manager-16-link
  newGenGcPath=/nix/var/nix/gcroots/per-user/gurkan/current-home
  genProfilePath=/nix/var/nix/profiles/per-user/gurkan/home-manager
Activating checkFilesChanged
Activating checkLinkTargets
Activating writeBoundary
Activating installPackages
replacing old 'home-manager-path'
installing 'home-manager-path'
Activating linkGeneration
Cleaning up orphan links from /home/gurkan
Checking /home/gurkan/yubikey: exists
Checking /home/gurkan/firefox: exists
No change so reusing latest profile generation 15
Creating home file links in /home/gurkan
'/home/gurkan/yubikey' -> '/nix/store/nsbrr82g0lkjhbp94g9dbppdpgghn2zh-home-manager-files/yubikey'
'/home/gurkan/firefox' -> '/nix/store/nsbrr82g0lkjhbp94g9dbppdpgghn2zh-home-manager-files/firefox'
Activating onFilesChange
Activating reloadSystemD
Activating xdgCreateCache
```

I have the main folder named `yubikey` which contains a folder `.yubikey` and I wanted to create this subfolder under home, but apparently it is linking the parents and creating stuff like `$HOME/yubikey` :confused:

**Comment by rycee** [comment]
Can you paste your configuration as well? It looks to me like it's not using `recursive = true`. It should link files, not directories.

**Comment by seqizz** [comment]
Here is all with some unrelated debris:

```
{ pkgs, config, ... }:

let
    baseconfig = { allowUnfree = true; };
    unstable = import (
        fetchTarball https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz
    ) { config = baseconfig; };
    bleeding = import (
        fetchTarball https://github.com/NixOS/nixpkgs/archive/master.tar.gz
    ) { config = baseconfig; };

    dotfiles_folder = builtins.toPath "${config.home.homeDirectory}/syncfolder/dotfiles";
in
{
    home.packages = with pkgs;[
        taskwarrior
        inotify-tools
    ];

    home.file = [
    {
      target = ".";
      source = "${dotfiles_folder}/yubikey";
      recursive = true;
    }
    {
      target = ".";
      source = "${dotfiles_folder}/firefox";
      recursive = true;
    }];

    programs.home-manager = {
        enable = true;
        path = "…";
    };
}
```

I am almost sure this is because of my variable up there :man_facepalming:

**Comment by sboosali** [comment]
(i only skimmed it, but) make sure you're calling `toString` on path
literals if you want to convert them into the "same" string. that is,

```
> p = ./dir

> ''${p}/subdir"
"/nix/store/abcdef.../dir/subdir"

> ''${builtins.toString p}/subdir"
"./dir/subdir"
```

**Comment by sboosali** [comment]
(i only skimmed it, but) make sure you're calling `toString` on path
literals if you want to convert them into the "same" string. that is,

    > p = ./dir
    
    > ''${p}/subdir"
     "/nix/store/abcdef.../dir/subdir"
    
    > ''${builtins.toString p}/subdir"
    "./dir/subdir"

**Comment by rycee** [comment]
@seqizz Instead of

    source = "${dotfiles_folder}/yubikey";

try

    source = ~/syncfolder/dotfiles/yubikey;

**Comment by seqizz** [comment]
Aaaaah :jack_o_lantern: of course, because of the type. When it's string, it links the parent folder (weird, but ok).

After a bit of playing, it even works with the variable:

```
let
    dotfiles_folder = /home/gurkan/syncfolder/dotfiles;
in
    home.file = [
    {
      target = ".";
      source = dotfiles_folder + /yubikey;
      recursive = true;
    }
    {
      target = ".";
      source = dotfiles_folder + /firefox;
      recursive = true;
    }]
```

Thank you very much. Time to ditch stow :tada:

**Comment by rycee** [comment]
Glad it works 🙂

Note, you can literally put `~` in the path to indicate your home directory. Then you don't have to explicitly mention the user name. I.e.
```
dotfiles_folder = ~/syncfolder/dotfiles;
```
should work (assuming `gurkan` is your username).

**Comment by seqizz** [comment]
Yep. I am using like it now. Also with mapping:

```
    home.file = map (source: { inherit source; target = "."; recursive = true; }) [
        ~/syncfolder/dotfiles/firefox
      ... a lot of similar lines here ...
        ~/syncfolder/dotfiles/zsh
    ];
```

As a bonus question if you have time:

I tried to append `~/syncfolder/dotfiles` while I am defining inheritance (instead of prefixing every folder with it) but couldn't manage. Is there a way to do it? :slightly_smiling_face:

**Comment by sboosali** [comment]
Gurkan, can you give an example hypothetical expression that does what you
want?

if you want a helper that prefixes paths, maybe

*mkPath = path: ''${toString ~/syncfolder/dotfiles}/${toString path}''*


*home.file."${mkPath "firefox"}".source = ...*

**Comment by seqizz** [comment]
I will try :slightly_smiling_face: You see my example on my last post, which works. I only wanted to eliminate the repeating base path (something something dotfiles).
My brain, coming from a non functional background, urges me to try stuff like:

```
    home.file = map (source: { ~/syncfolder/dotfiles + { inherit source }; target = "."; recursive = true; }) [
        /firefox
        /zsh
    ];
```
Thanks for bearing :slightly_smiling_face:

**Comment by seqizz** [comment]
Sorry for very long chain of issues under single topic, but I realized the recursive solution is not usable for me since it's not linking. It's copying the actual files to the nix folder.

Any way to force the symlink to the actual `dotfiles` folder to make it writable?

**Comment by sboosali** [comment]
for your first question, something like the following?

```
let

syncDir = ~/syncfolder/dotfiles;

mkSyncPath = path: 
  ''${toString syncDir}/${toString path}''

# e.g. « home.file."${mkSyncPath "firefox"}".source = ... »

mkSyncFile = source:
  { source = mkSyncPath source;
    target = "."; 
    recursive = true; 
  };

mkSyncAttr = source:
  { name = source;
    value = mkSyncFile source;
  };

mkSyncHome = sources:
  builtins.listToAttrs (builtins.map mkSyncAttr sources);

in

{

  home.file = mkSyncHome [
        "firefox"
        "zsh"
    ]);

}



```

**Comment by seqizz** [comment]
Not exactly, it decodes to string at last step apparently.
This causes home.file to /home/gurkan/firefox (like [here](https://github.com/rycee/home-manager/issues/492#issuecomment-446399169)).

It is really not that important. Syntax-wise current solution is OK for now, I can dig after I learn better about the types.

But making the configuration files read only is a no-go. I'll revert to stow for now I guess. I don't want to define every file one by one to make them symlinks.

Thank you very much anyway. Nix has the most helpful community so far :slightly_smiling_face:

**Comment by rycee** [comment]
> It's copying the actual files to the nix folder.

This an intended feature. That it works to specify a string as a source and it being linked to by Home Manager is something that mostly is accidental, in a few cases it is convenient but generally I would strongly advice against using `home.file` that way. I may in the future make this stricter and not at all allow such cases. The main concern is reproducibility and allowing proper rollbacks.

To perform linking to files outside the Nix store I would instead recommend adding your own activation script block that performs this. You could, for example, run stow in the activation block.

**Comment by seqizz** [comment]
After sleeping on the idea, I think you're right. Now I've separated the "configuration" files and content files. For example I don't need reproducibility for, let's say the `.password-store` directory.

Thanks again for the help. :tada:
