### ISSUE TITLE
'nixos-config' was not found in the Nix search path

### ISSUE THREAD

**Issue by tbenst** [rycee/home-manager#499]
I originally had the same issue as #487, and fixed it by: `NIX_PATH=/home/$USER/.nix-defexpr/channels:$NIX_PATH`. However, I now have a new problem when attempting a fresh install on Ubuntu 16.04:

```
Creating initial Home Manager generation...

/nix/store/az8gqspcfqr3fdhkscz60qhjnxdh5ggs-bash-4.4-p23/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
error: file 'nixos-config' was not found in the Nix search path (add it using $NIX_PATH or -I), at /home/tbenst/.nix-defexpr/channels/nixpkgs/nixos/default.nix:1:60
(use '--show-trace' to show detailed location information)
```

Perhaps something was modified to rely on nixOS? Would love to keep using home-manager across platforms!

**Comment by smaximov** [comment]
It may have something to do with your nix/nixpkgs/home-managers config. I have been able to successfully install nix & home-manager on Mac OS from scratch. I didn't have any previous configuration of nix & home-manager (apart from adding `$HOME/.nix-defexpr/channels` to `NIX-PATH`)

**Comment by tbenst** [comment]
Thanks, @smaximov! You are right, I had a call to `nixos.config....` in my config file. Do you happen to know if there's a nix expression to tell if I'm on NixOS? I'm trying to use the same home configuration on both Ubuntu and NixOS. Thanks for the debugging insight!

**Comment by smaximov** [comment]
> Do you happen to know if there's a nix expression to tell if I'm on NixOS?

Sorry, I don't know (I'm still a Nix/NixOS newbie). The closest is `pkgs.system` which can let you differentiate between Unix variants (Mac OS/Linux).

**Comment by tbenst** [comment]
@smaximov much appreciated I’ll look into it
