### ISSUE TITLE
[Feature Request] Symlink source trees into homedir

### ISSUE THREAD

**Issue by elitak** [rycee/home-manager#5]
I'd like to be able to do something like the following:

    home.file.".tmux/plugins/tmux-resurrect".source = fetchFromGitHub {
        owner = "tmux-plugins";
        repo = "tmux-resurrect";
        rev = "b8cc90a7f4db209d6c25d4156f8f236eec3b1dca";
        sha256 = "0bhgwg5za4mga11fd7wnr8zikcnrdaahaficfylfmggb46mxnbhs";
      };

But the invocation of `install` chokes on directories. What's the best way to add support for linking repo checkouts into the home directory tree? I naively tried changing `install` to `ln -sf`, but then the activate script didn't copy them into the homedir.

**Comment by rycee** [comment]
Please give the fix/5 branch a try. The code in your description should work with that branch.

**Comment by elitak** [comment]
error: value is a string while a set was expected
    (use ‘--show-trace’ to show detailed location information)

(show-trace can't be passed via `home-manager build`, AFAICT)

**Comment by rycee** [comment]
The `--show-trace` argument is given to nix-build when enabling verbose output. So try `home-manager -v -f {yourconfig} build`.

I'm not sure how that error message could come up, maybe it could be due to some other problem? Could you share your configuration?

**Comment by elitak** [comment]
It's a regression that's causing an older line to no longer work. The assertion or something is checking the `source` attr when none is present and a `text` is being used.

**Comment by elitak** [comment]
error: while evaluating the attribute ‘activation-script’ at /home/keb/.nixpkgs/home-manager/modules/default.nix:76:3:
    while evaluating ‘showWarnings’ at /home/keb/.nixpkgs/home-manager/modules/default.nix:45:18, called from /home/keb/.nixpkgs/home-manager/modules/default.nix:56:12:
    while evaluating ‘fold’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/lists.nix:29:19, called from /home/keb/.nixpkgs/home-manager/modules/default.nix:49:7:
    while evaluating ‘fold'’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/lists.nix:32:15, called from /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/lists.nix:36:8:
    while evaluating ‘collectFailed’ at /home/keb/.nixpkgs/home-manager/modules/default.nix:42:19, called from /home/keb/.nixpkgs/home-manager/modules/default.nix:62:16:
    while evaluating anonymous function at /home/keb/.nixpkgs/home-manager/modules/default.nix:43:33, called from undefined position:
    while evaluating the attribute ‘assertion’ at /home/keb/.nixpkgs/home-manager/modules/home-environment.nix:224:11:
    while evaluating anonymous function at /home/keb/.nixpkgs/home-manager/modules/home-environment.nix:218:19, called from undefined position:
    while evaluating ‘hasPrefix’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/strings.nix:148:21, called from /home/keb/.nixpkgs/home-manager/modules/home-environment.nix:218:22:
    while evaluating anonymous function at /home/keb/.nixpkgs/home-manager/modules/home-environment.nix:219:17, called from undefined position:
    while evaluating the attribute ‘source’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/attrsets.nix:199:44:
    while evaluating anonymous function at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:75:45, called from /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/attrsets.nix:199:52:
    while evaluating the attribute ‘value’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:300:9:
    while evaluating the option `home.file..xsession.source':
    while evaluating the attribute ‘isDefined’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:332:5:
    while evaluating ‘filterOverrides’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:407:21, called from /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:316:18:
    while evaluating ‘concatMap’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/lists.nix:79:18, called from /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:413:8:
    while evaluating ‘concatMap’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/lists.nix:79:18, called from /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:311:17:
    while evaluating anonymous function at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:311:28, called from undefined position:
    while evaluating ‘dischargeProperties’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:374:25, called from /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:312:62:
    while evaluating the attribute ‘condition’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:455:14:
    while evaluating the attribute ‘text’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/attrsets.nix:199:44:
    while evaluating anonymous function at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:75:45, called from /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/attrsets.nix:199:52:
    while evaluating the attribute ‘value’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:300:9:
    while evaluating the option `home.file..xsession.text':
    while evaluating the attribute ‘isDefined’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:332:5:
    while evaluating ‘filterOverrides’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:407:21, called from /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:316:18:
    while evaluating ‘concatMap’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/lists.nix:79:18, called from /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:413:8:
    while evaluating ‘concatMap’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/lists.nix:79:18, called from /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:311:17:
    while evaluating anonymous function at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:311:28, called from undefined position:
    while evaluating ‘dischargeProperties’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:374:25, called from /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:312:62:
    while evaluating the attribute ‘value’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/modules.nix:204:48:
    while evaluating the attribute ‘config.text’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/attrsets.nix:199:44:
    while evaluating ‘mkAttrOverridable’ at /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/customisation.nix:111:33, called from /nix/store/k4rhrg843kphq7kj3n8m6pcz3zr96i8h-nixos-17.03pre96925.1c50bdd/nixos/lib/attrsets.nix:199:52:
    value is a string while a set was expected


where ~/.nixpkgs/home.xsession.nix is

    { pkgs, stdenv, ... }: { text = "bar"; }


and the line in home.nix is

    home.file.".xsession" = callPackages ./home.xsession.nix { };


This line worked in the master branch.

**Comment by elitak** [comment]
I realize using callPackages is hacky since the file contains an attrset of things other than derivations, but I prefer it to using `import ./home.xsession.nix` and passing in the scope explicitly.

**Comment by elitak** [comment]
Also, I get this when trying to switch from one gen to the next:

    /nix/store/f00bpslbxg73mhc7pglg0b0i7nwwjypp-home-manager-generation
    Starting home manager activation
    Activating installPackages
    replacing old ‘home-manager-path’
    installing ‘home-manager-path’
    Activating linkGeneration
    ln: cannot remove '/home/keb/.tmux/plugins/tpm/tpm': Read-only file system
    ln: failed to create symbolic link '/home/keb/.tmux/plugins/tmux-resurrect/tmux-resurrect': Read-only file system
    ln: failed to create symbolic link '/home/keb/.tmux/plugins/tmux-continuum/tmux-continuum': Read-only file system
    ln: failed to create symbolic link '/home/keb/.tmux/plugins/tmux-sensible/tmux-sensible': Read-only file system
    Cleaning up orphan links from /home/keb
    Activating reloadSystemD

Plus, the `ln` won't clobber existing directories on first installation, which is maybe intended.

**Comment by rycee** [comment]
Yeah, haven't considered `callPackages` being used like this and I'm actually a bit surprised it worked before. In any case, the error seems to be due to the `callPackages` implementation changing between 16.09 and 17.03. I assume you recently switched to 17.03?

In any case, I won't attempt to support `callPackages` (or `callPackage`) being used in this way since those functions are intended for a different purpose. Instead I would strongly recommend you to use the module system's built-in import functionality.

Try something like the following:
```
# In home.nix
{
  imports = [ ./home.xsession.nix ];
}
```
and
```
# In home.xsession.nix
{ pkgs, stdenv, ... }:

{
  home.file.".xsession".text = "bar";
}
```

About the
```
ln: cannot remove '/home/keb/.tmux/plugins/tpm/tpm': Read-only file system
```
error. You are absolutely right it needs a `-n` option to `ln`. I've added a commit that fixes this issue.

I'm inclined to say that ln refusing to overwrite an existing path is a feature, not a bug. I would like to implement this behavior for regular files as well. I.e., when trying to switch to a configuration that would destroy an existing file it would exit with an error message telling you about it. Then you can move the file manually and redo the home-manager switch. The way it does it at the moment is kind of unpleasantly dangerous.

**Comment by elitak** [comment]
Ah, importing that way seems fine. Thanks for the fix.

**Comment by rycee** [comment]
Yeah, that is a pretty powerful method of importing so in most cases it should work well.

I've merged the fixes into master and will delete the `fix/5` branch now. Many thanks for your feedback!
