### ISSUE TITLE
Services not starting

### ISSUE THREAD

**Issue by Ralith** [rycee/home-manager#512]
After a recent update, home-manager is no longer starting user services, though `systemd.user.startServices = true;`. This includes compton, gpg-agent, nm-applet, blueman, redshift, and others.

**Comment by rycee** [comment]
Do you know the revision you updated from and which one you updated to? Did you seen any error messages? Any output when running with the `-v` flag?

**Comment by rycee** [comment]
Oh, and do you have either the gtk or gnome-manager modules enabled?

**Comment by rycee** [comment]
Hmm, the `Process org.freedesktop.systemd1 exited with status 1` is a classic in NixOS. It is very easy to provoke this error on NixOS, e.g., by using the `--wait` option.

For a daemon-reload to produce this error I suspect something more fundamental has gone wrong and the issue is somewhere in Nixpkgs. Is the `XDG_RUNTIME_DIR` environment variable set?

**Comment by Ralith** [comment]
> Is the `XDG_RUNTIME_DIR` environment variable set?

Seems not. The top of .xsession-errors is full of similar errors, which I'm guessing arise from home-manager's initialization attempts.

**Comment by rycee** [comment]
If `XDG_RUNTIME_DIR` is missing then it might be some issue arising early in the user login. This variable is typically set by [`pam_systemd`](https://www.freedesktop.org/software/systemd/man/pam_systemd.html#Environment) which happens well before anything Home Manager touches.

Might be worth checking out the Nixpkgs issues for similar errors?

You could also try seeing if `XDG_RUNTIME_DIR` shows up in a console login. The issue might be limited to the display manager login.

**Comment by Ralith** [comment]
`XDG_RUNTIME_DIR` is set in `ssh localhost`, yeah. I'll see what I can dig up and report back if I find something, thanks.

**Comment by rycee** [comment]
Hope you find the solution! Maybe the systemd system or user journal contains something helpful?

**Comment by Ralith** [comment]
The problem mysteriously evaporated after a reboot. The issue originally arose when I was on home-manager master and I switched to 18.09 in my early attempts to fix it; possibly related? Anyway, no longer affects me for the moment.
