### ISSUE TITLE
News module

### ISSUE THREAD

**Issue by rycee** [rycee/home-manager#52]
When updating Home Manager and its modules then it would be nice to be informed about any changes that affect my configuration, e.g., deprecation of options, change in behavior, upcoming breaking changes, etc.

This can be accomplished by having the `home-manager` command hook into a _news_ module. This news module declares an option `news.entries` that holds a list of news entries. A news may optionally have a _condition_ that will determine whether the entry is relevant to the user.

When performing a `home-manager build` or `home-manager switch` one can then notify the user of any unread news. The user can then run `home-manager news` to see the actual news entries. Alternatively, with `news.display = "show";` in the configuration, the news will be shown immediately on build or switch.

**Comment by rycee** [comment]
Let's consider this a success and go on with life 👍

**Comment by BenBals** [comment]
I love the news feature. It helped me discover things I could transform from symlinked dotfiles to home manager config.

**Comment by rycee** [comment]
@BenBals Thanks, that's nice to hear!
