### ISSUE TITLE
Update fonts cache

### ISSUE THREAD

**Issue by wedens** [rycee/home-manager#520]
When `fonts.fonts = [ ];` list is modified in nixos, it causes fonts cache update. It'd be handy to have such option for fonts installed via home-manager so that you don't need to execute `fc-cache -f` manually.

**Comment by Jomik** [comment]
This looks like a good idea to me :+1: 
Why `fonts.fonts` though? Maybe just a rootlevel `fonts` or do `home.fonts`?
I realize that NixOS uses `fonts.fonts`, i find the name weird though.

**Comment by wedens** [comment]
> Why fonts.fonts though?  Maybe just a rootlevel fonts or do home.fonts?

There is already `fonts.fontconfig`, so it can't be just `fonts`. `fonts.fonts` is at least known from nixos.

**Comment by Jomik** [comment]
Oh, there is. Makes sense to follow NixOS then. I'd probably have chosen `fonts.packages`, but yours makes sense :smiley:

**Comment by leotaku** [comment]
@rycee, @wedens are you still interested in having this added to home-manager?

**Comment by rycee** [comment]
If anybody is able to try it out then please have a look at #682, which I believe will resolve this issue.
