### ISSUE TITLE
Do not install fish if set to login shell

### ISSUE THREAD

**Issue by stellarhoof** [rycee/home-manager#530]
Currently I've got `users.users.<name>.shell = pkgs.fish` under `configuration.nix`. I'm also managing fish config through `home-manager`. However, the fish installed by `home-manager` shadows my login shell installed through nix.

I guess this goes further than just fish and login shells. In general wouldn't we want to have an option to not install a package if already present?

**Comment by teto** [comment]
home-manager version should take precedence as it's your own. You could use home-manager as a nixpkgs module so that the fish version remain the same.

**Comment by rycee** [comment]
I don't quite understand. Does the Home Manager installation of fish cause some particular problem? It would be pretty tricky for Home Manager to automatically determine whether it is necessary to install it…

One possibility would be to add a `programs.fish.package` option and then you can set this to an empty package if you don't want to install fish to your user profile.

**Comment by stellarhoof** [comment]
> One possibility would be to add a programs.fish.package option and then you can set this to an empty package if you don't want to install fish to your user profile.

Yes after I thought about it more my original proposal doesn't reallly make sense to me anymore. I cannot think of a case apart from the login shell where I'd not want to use the home-manager installed program. `programs.fish.package` is perfect actually.

The only issue I've found is that colors for the my login fish shell didn't carry on to the one from home-manager. I didn't care to investigate more.
