### ISSUE TITLE
`home.file.<name>.source` is evaluated too early

### ISSUE THREAD

**Issue by Nadrieril** [rycee/home-manager#538]
The fix for https://github.com/rycee/home-manager/issues/4 implemented in commit https://github.com/rycee/home-manager/commit/a3900340e4823fa317972b7380da9aefd5615e1f causes `home.file.<name>.source` (and then `home.file.<name>.text`) to be evaluated while the assertions are checked. This means that a failure in evaluating `home.file.<name>.source` will crash before assertions have finished being checked and displayed. So computation of `home.file.<name>.source` cannot rely on the fact that the assertions have been checked. The code that does the unwanted evaluation is there: https://github.com/rycee/home-manager/blob/5770dc58b9/modules/files.nix#L39-L51.

For example, the following crashes when `cfg.whatever` is `null`, instead of displaying the list of failed assertions:
```
{
  assertions = [
    { assertion = cfg.whatever != null; message = "whatever cannot be null !"; }
  ];
  home.file."filename".text = ''
    # contents of some config file
    ${cfg.whatever.contents}
  '';
}
```

This is in particular present in the `programs.mbsync` module, where the test https://github.com/rycee/home-manager/blob/5770dc5/modules/programs/mbsync.nix#L52 shouldn't need to exist since the conditions tested should be enforced by the assertions defined later on https://github.com/rycee/home-manager/blob/5770dc5/modules/programs/mbsync.nix#L147.

This is not a blocking issue per se, but the behavior is quite surprising when developing modules.
I tried to implement the fix mentioned in https://github.com/rycee/home-manager/issues/4#issuecomment-412245522 but couldn't make it work.

**Comment by rycee** [comment]
Good catch! I had a look at your PR and it seemed quite fair to me but I pondered a bit and figured that maybe this limitation could be sidestepped entirely. I made #541 which should allow things like
```
home.file.".hidden".source = ./.hidden;
```
which was taken from the test case I added to the PR.

**Comment by Nadrieril** [comment]
Ohh, `builtins.hasContext` is exactly what I was missing to make it work ! I didn't know about it, it's not documented anywhere. That's great !

**Comment by Nadrieril** [comment]
Resolved by https://github.com/rycee/home-manager/pull/541
