### ISSUE TITLE
Support git lfs

### ISSUE THREAD

**Issue by turion** [rycee/home-manager#542]
Git LFS (large file support) is usually installed by running `git lfs install` which tries to modify `~/.gitconfig`. This is incompatible with home manager if `programs.git.enable = true;`.

If I understand it correctly, LFS just needs to set the following config:

```
[filter "lfs"]
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
	clean = git-lfs clean -- %f
```

So there should maybe be an option `programs.git.lfs.enable = true;` that sets this config and installs `git-lfs`?

**Comment by rycee** [comment]
That sounds like a fine idea to me! I don't have time to implement this myself and I don't use git-lfs anyway so I wouldn't be able to tell if it works OK.

But if anybody does a rough implementation and opens a PR then I'd be happy to assist in getting it merged.

**Comment by worldofpeace** [comment]
For those who want at least the git configuration now they can add
```nix
programs.git.extraConfig = {
  "filter \"lfs\"" = {
     clean = "${pkgs.git-lfs}/bin/git-lfs clean -- %f";
     smudge = "${pkgs.git-lfs}/bin/git-lfs smudge --skip -- %f";
     process = "${pkgs.git-lfs}/bin/git-lfs filter-process --skip";
     required = true;
  };
};

**Comment by rycee** [comment]
Added a `programs.git.lfs.enable` option which adds the options I got when doing `git lfs install` as well as installing `nixpkgs.git-lfs`. Please give it a try.

**Comment by teto** [comment]
alternatively, we could also save the generated git config  in an alternative file .config/git/config.generated so that all the `git config --global` keep working and the user would just include the generated config. I hear the argument that it's against the spirit of declarative system but not everything needs to be declarative.

**Comment by turion** [comment]
@rycee Awesome, will test soon!
@teto Sounds like an interesting idea, but not specific to git lfs, right?
