### ISSUE TITLE
xmodmap changes get reset after a switch

### ISSUE THREAD

**Issue by stellarhoof** [rycee/home-manager#543]
Read `.Xmodmap` on `xsession.initExtra` and whenever `home-manager switch` is invoked, changes are reset to their defaults.

**Comment by rycee** [comment]
Yeah, this is probably due to the `setxkbmap` service that Home Manager adds when `xsession.enable` is true. The easiest way to override this is probably to add something like
```
systemd.user.services.setxkbmap.Service.ExecStart = "${pkgs.coreutils}/bin/true";
```
to your configuration.

**Comment by stellarhoof** [comment]
I did a switch and then `sudo systemctl restart display-manager` after changing it and no dice.

**Comment by rycee** [comment]
I tried the same configuration line and it seemed to work for me, `~/.config/systemd/user/setxkbmap.service` became
```ini
[Install]
WantedBy=graphical-session.target

[Service]
ExecStart=/nix/store/dm20hrdk6s4jzfmk1197p2nya0p8fy3a-coreutils-8.29/bin/true
Type=oneshot

[Unit]
After=graphical-session-pre.target
Description=Set up keyboard in X
PartOf=graphical-session.target
```

Perhaps there is something else causing the resetting? I've noticed this happening sometimes when I do a NixOS system switch and then I manually run `systemctl --user start setxkbmap.service`.

**Comment by stellarhoof** [comment]
You're right. The unit does get updated under `~/.config/systemd/user`. I think the problem is that I had a faulty service during my testing and `systemctl --quiet --user is-system-running` returns `> 0` because of this, which causes home-manager to skip the reload. I fixed it with:
```
systemctl --user disable setxkbmap
systemctl --user daemon-reload
systemctl --user reset-failed
home-manager switch
```

**Comment by stellarhoof** [comment]
Should it be home-manager's responsibility to do the steps above to ensure failed units get reloaded?

**Comment by stellarhoof** [comment]
I got it to work also with a clean `home.nix`:
```
{ config, pkgs, ... }:

with pkgs.lib;

{
  systemd.user = {
    startServices = true;

    services = {
      setxkbmap.Service.ExecStart = "${pkgs.coreutils}/bin/true";
    };
  };
}
```
I'll investigate more.

**Comment by stellarhoof** [comment]
Ok so here's a minimum, reproducible non-working case in my environment:

`home.nix`:
```
{ config, pkgs, ... }:

with pkgs.lib;

{
  imports = [
    ./i3.nix
  ];
}
```

`i3.nix`:
```
{ config, pkgs, ... }:

with pkgs.lib;

{
  imports = [
    ./i3.nix
  ];
}
```

**Comment by stellarhoof** [comment]
@rycee Ping. Any idea why changes don't get picked up when I set that option in a separate module? Can you reproduce my last comment?

**Comment by rycee** [comment]
@stellarhoof Sorry about the long delay! Yeah, this issue is due to the very primitive type used for the systemd unit options. Basically they offer no control over the order of option merging and it is therefore quite possible for the default value to override whatever you set. It just depends on the order the modules happen to get loaded 🙁

In any case, I made a PR to use better typing. With this change you should be able to have
```
  systemd.user = {
    services = {
      setxkbmap.Service.ExecStart = lib.mkForce "${pkgs.coreutils}/bin/true";
    };
  };
```
and it should work regardless where you put the code.

If you have the chance, please try the PR out.

**Comment by stellarhoof** [comment]
It works perfectly now! Thank you.
