### ISSUE TITLE
[nixos] taffybar + flameshot: No system tray found

### ISSUE THREAD

**Issue by stites** [rycee/home-manager#544]
I keep seeing this error on boot, "No system tray found." I believe the problem is that the service files which depend on a system tray, like flameshot, expect to have the tray already loaded. If you manage xmonad+taffybar with home-manager, however, things get out-of-order (at least for me), this error pops up, and flameshot fails to load into the system tray. Is anyone else experiencing this or can someone reproduce? I'm going to overwrite the service files for a fix on my side, but I'm not sure if this is something worth committing or some quirk with my overkill configuration.

**Comment by rycee** [comment]
This seems like a systemd service setup issue. Would you mind adding
```nix
systemd.user.services.flameshot.Unit.After = [
  "graphical-session-pre.target"
  "polybar.service"
  "taffybar.service"
  "stalonetray.service"
];
```
to your configuration and see if that solves the issue?

**Comment by stites** [comment]
![](https://i.imgur.com/LpB6B8M.png)

worked like a charm! It also looked like it was breaking the tray somehow, since I wasn't seeing any of the other tray items before this!

**Comment by rycee** [comment]
Cool! I'll make a commit to add the change.

I think stalonetray refers to this one: http://stalonetray.sourceforge.net/
