### ISSUE TITLE
Polybar module causes compilation

### ISSUE THREAD

**Issue by asymmetric** [rycee/home-manager#546]
On 18.09 for both NIxOS and Home Manager, using the `polybar` module with no configuration causes polybar to be compiled, which makes me think that some arguments passed to the package must be different from their default in nixpkgs?

**Comment by rycee** [comment]
I tried on my 18.09 system to add
```
services.polybar = {
  enable = true;
  script = "polybar bar &";
};
```
to my configuration and it downloaded the polybar package from the binary cache.

Do you still have this issue?

**Comment by asymmetric** [comment]
> Could it be that you were using an old nixos channel, or the binary cache was not available?

Either of those is very possible, and this is not such a big problem anyway, so closing, thanks for the help :)
