### ISSUE TITLE
zsh: plugins

### ISSUE THREAD

**Issue by dermetfan** [rycee/home-manager#55]
I recently extended the zsh module by a `plugins` option in my [dotfiles](https://bitbucket.org/dermetfan/dotfiles/src/51ce139c9fd77ce689b239f16a06a851bfe23e0a/.config/nixpkgs/home/programs/zsh.nix?at=default&fileviewer=file-view-default):

```nix
programs.zsh.plugins = [
  {
    file = "zsh-256color.plugin.zsh";
    src = pkgs.fetchFromGitHub {
      owner = "chrissicool";
      repo = "zsh-256color";
      rev = "ae40a49ccfc7520d2d7b575aaea160ff876fe3dc";
      sha256 = "0c2yzbd4y0fyn9yycrxh32am27r0df0x3r526gf1pmyqiv49rg5z";
    };
  }
  {
    file = "fast-syntax-highlighting.plugin.zsh";
    src = pkgs.fetchFromGitHub {
      owner = "zdharma";
      repo = "fast-syntax-highlighting";
      rev = "5fab542516579bdea5cc8b94137d9d85a0c3fda5";
      sha256 = "1ff1z2snbl9rx3mrcjbamlvc21fh9l32zi2hh9vcgcwbjwn5kikg";
    };
  }
];
```

The result looks like this in `.zshrc`:

```shell
autoload -Uz compinit; compinit -iCd $HOME/.zcompdump
path+="/nix/store/w8jv67h8l60dj6fzm35q5sxdimi62bps-zsh-256color-ae40a49ccfc7520d2d7b575aaea160ff876fe3dc-src"
fpath+="/nix/store/w8jv67h8l60dj6fzm35q5sxdimi62bps-zsh-256color-ae40a49ccfc7520d2d7b575aaea160ff876fe3dc-src"
source "/nix/store/w8jv67h8l60dj6fzm35q5sxdimi62bps-zsh-256color-ae40a49ccfc7520d2d7b575aaea160ff876fe3dc-src/zsh-256color.plugin.zsh"
path+="/nix/store/13r11ycprwslr6851qr13pl6ms73906m-fast-syntax-highlighting-5fab542516579bdea5cc8b94137d9d85a0c3fda5-src"
fpath+="/nix/store/13r11ycprwslr6851qr13pl6ms73906m-fast-syntax-highlighting-5fab542516579bdea5cc8b94137d9d85a0c3fda5-src"
source "/nix/store/13r11ycprwslr6851qr13pl6ms73906m-fast-syntax-highlighting-5fab542516579bdea5cc8b94137d9d85a0c3fda5-src/fast-syntax-highlighting.plugin.zsh"
```

I also tried this syntax but the order is not preserved. Maybe when toposort is implemented in #50 we can use it here:

```nix
programs.zsh.plugins = with pkgs; {
  "zsh-256color".src = fetchFromGitHub {
    owner = "chrissicool";
    repo = "zsh-256color";
    rev = "ae40a49ccfc7520d2d7b575aaea160ff876fe3dc";
    sha256 = "0c2yzbd4y0fyn9yycrxh32am27r0df0x3r526gf1pmyqiv49rg5z";
  };

  "fast-syntax-highlighting".src = fetchFromGitHub {
    owner = "zdharma";
    repo = "fast-syntax-highlighting";
    rev = "5fab542516579bdea5cc8b94137d9d85a0c3fda5";
    sha256 = "1ff1z2snbl9rx3mrcjbamlvc21fh9l32zi2hh9vcgcwbjwn5kikg";
  };
};
```

In an attempt to reduce my zsh startup time I switched from oh-my-zsh to antigen to [zr](https://github.com/jedahan/zr) but I could not bring it below ~0.95 sec. Using the `plugins` option I get a consistent 0.05 sec with the same plugins loaded. I'm not sure what the cause is (may be related to #54) but I like the simple approach.

Would this be a desirable feature for home-manager?

**Comment by rycee** [comment]
I think this is separate from #50 but certainly related to topological sorting. Maybe could have a `dependsOn` field that can be used to produce a DAG that can be sorted using `dagTopoSort`? In any case, it seems to me like a neat idea but I don't use zsh so I don't have a strong opinion. Maybe @uvNikita has input to give?

**Comment by uvNikita** [comment]
With the changes from #54, startup time for me dropped from 1.3s to 0.13s. And with disabling `programs.zsh` in the system (which will remove another unnecessary pollution of `fpath`) it dropped down to 0.066. So after PR will be merged, startup time with `programs.zsh.oh-my-zsh` enabled should be fast again.

But I also like the idea of being able to use vanilla zsh and extending it with plugins directly, so it I think your changes would be a very useful extension of the current module.

**Comment by dermetfan** [comment]
Closing with #56.
