### ISSUE TITLE
problems with PATH order, when using as nixos-module.

### ISSUE THREAD

**Issue by maralorn** [rycee/home-manager#550]
Since I upgraded my nixos to 18-09 I have the following problem:
My PATH contains the following 3 entries in this order:

    ... /home/maralorn/.nix-profile/bin: ... :/run/current-system/sw/bin:/etc/profiles/per-user/maralorn/bin

So when using `home-manager` manually user installed packages take precedence over system packages because they land in `.nix-profile`. But when using home-manager as a system module, the system binaries take precedence.
There are of course easy workarounds for this. (Manually changing the PATH.)
But I am not sure what the best solution to this problem is and how to fix it in home-manager. Is this maybe a sign that we shouldn't install the user-environment to  `/etc/profiles/per-user/`?

I'd be glad for input. Thanks for home-manager. It's awesome!

**Comment by Shados** [comment]
@rycee "merge order" for list options is not arbitrary; you can manipulate it with `mkOrder` (or the simple wrappers `mkBefore` and `mkAfter`, none of which are really documented, so see [<nixpkgs/lib/modules.nix>](https://github.com/NixOS/nixpkgs/tree/master/lib/modules.nix) for details).

You could PR a nixpkgs change to do something like make the `users-groups.nix` line `environment.profiles = mkBefore [ "$HOME/.nix-profile" "/etc/profiles/per-user/$USER" ];` and remove the first from `environment.nix`. This would seem reasonable to me (it is surprising to have more-specific per-user packages overriden by generic system-wide packages!).

You could also add that same definition in home-manager's nixos module. Which would work fine, but would mean those two directories would appear in `$PATH` twice :). That could slightly increase the time taken for shells to resolve binaries, I guess, but two paths are unlikely to have much impact, and I suspect some shells may be both deduplicating `$PATH` entries and building an internal hash of `name -> binary path` entries anyway.

**Comment by Gerschtli** [comment]
As far as I can tell, this issue will be resolved as soon as my PR in nixpkgs gets merged into the release channel. So I think we can close this issue, as there is nothing more to do then waiting.

**Comment by Gerschtli** [comment]
The fix is now available in nixos-19.03 channel. Issue can be closed.

**Comment by Gerschtli** [comment]
@rycee @maralorn This issue can be closed :)

**Comment by maralorn** [comment]
I don‘t have this problem anymore. But I changed my setup anyways.
