### ISSUE TITLE
Symlink to gnupg doesn't work

### ISSUE THREAD

**Issue by ivegotasthma** [rycee/home-manager#551]
Hello,

I have this line in my home.nix

```
  home.file.".gnupg".source = ~/.dotfiles/gnupg;
```

Afterwards, when I try to sign a commit I get an error, when git tries to sign the commit.

```
[asthma@dev:~/.dotfiles]$ git commit -m 'fix'
error: gpg failed to sign the data
fatal: failed to write commit object
```

If I set recursive to true, a folder with symlinks to all the files is created. This makes gnupg work, I get asked for my passphrase and everything works. Any idea how I can fix this?

My goal is to symlink .gnupg to my .dotfiles/gnupg, whenever I generate a new key, it should be generated inside .dotfiles/gnupg. Is this possible?

**Comment by rycee** [comment]
If I understood the situation correctly then perhaps something like
```
home.activation.createGnupgDir =
  config.lib.dag.entryBetween
    [ "linkGeneration" ]
    [ "writeBoundary" ]
    ''
      if [[ ! -L ~/.gnupg ]]; then
        $DRY_RUN_CMD ln $VERBOSE_ARG -s ~/.dotfiles/gnupg ~/.gnupg
      fi
    '';
```
might work. It would create a symbolic link from `~/.gnupg` to `~/.dotfiles/gnupg`. So any file created inside `~/.gnupg` would show up inside `~/.dotfiles/gnupg`.

**Comment by ivegotasthma** [comment]
I tried it, still signing commits failed. I'll manually manage those two folders. Thanks for the help!
