### ISSUE TITLE
Support shared home-manager configurations between all users

### ISSUE THREAD

**Issue by vlaci** [rycee/home-manager#594]
https://github.com/rycee/home-manager/issues/549 is broke my configuration. I have created a [NixOS module](https://github.com/vlaci/blox/blob/master/modules/nixos/home-manager.nix#L64) where I can declare a "shared" home manager configuration which is applied to all users managed by nix. I use this approach to generate homogeneous user environments. 

The above mentioned change introduces infinite recursion because now home-manager writes the `users.users` attribute.

I can work around this problem but I thought that it worth to mention this use case [1]

---
[1] Upon writing the issue description I remembered this xkcd comic https://xkcd.com/1172/

**Comment by kalbasit** [comment]
I use something very similar to you, by assigning one home-manager config to multiple users, and this has not broken my setup. Perhaps it's something specific to you? Can you point out how it's setup on your side?

Here's how it's setup on my side:
- I added a NixOS option called [`mine.home-manager.config`](https://github.com/kalbasit/shabka/blob/c20d47b73784b1a5a5495f42e7c09a40dc7e51b7/modules/nixos/general/home-manager.nix#L21-L26)
- [NixOS configuration](https://github.com/kalbasit/shabka/blob/c20d47b73784b1a5a5495f42e7c09a40dc7e51b7/hosts/hades/configuration.nix#L44) imports [home.nix that sets the above option](https://github.com/kalbasit/shabka/blob/c20d47b73784b1a5a5495f42e7c09a40dc7e51b7/hosts/hades/home.nix)
- [home-manager.users](https://github.com/kalbasit/shabka/blob/c20d47b73784b1a5a5495f42e7c09a40dc7e51b7/modules/nixos/general/users.nix#L83) gets set by [calling the above config option](https://github.com/kalbasit/shabka/blob/c20d47b73784b1a5a5495f42e7c09a40dc7e51b7/modules/nixos/general/users.nix#L35-L38).

> [1] Upon writing the issue description I remembered this xkcd comic https://xkcd.com/1172/

I love it :rofl:!

**Comment by vlaci** [comment]
Your configuration gave me the original inspiration for my version. The difference is that [I use `users.users`](https://github.com/vlaci/blox/blob/master/modules/nixos/home-manager.nix#L64) directly instead of a separate users attribute set hence the recursion.

**Comment by kalbasit** [comment]
@vlaci oh I see, makes sense. @rycee thoughts on how to avoid the infinite loop here?

**Comment by rycee** [comment]
Ah, this was unfortunate! I think to fix it one would have to change
https://github.com/rycee/home-manager/blob/f07510e2b63075a5e334e603f666c5c5838563ce/nixos/default.nix#L47
to be completely inside a `mkIf`. I guess using `mkMerge`. I'll see if I get an opportunity to fix it tomorrow. Thanks for reporting the bug!

**Comment by vlaci** [comment]
I have fixed this issue on my side. I have already created my own `users.users` wrapper where I can set all the attributes I need and use that as a single source of truth to assign both `home-manager.users` and `users.users` in a similar fassion @kalbasit does. 

Thank you for the effort you have put in investigating this. 
Cheers!

**Comment by AkechiShiro** [comment]
Is there any recommended way to do this nowadays

**Comment by hraban** [comment]
Thanks for fixing, @rycee -- I use this and it's a nice feature

**Comment by Bert-Proesmans** [comment]
This recursion can be solved by pulling config from within `users.users.<name>` eg, 

```nix
options.users.users = mkOption {
    type = types.attrsOf (types.submodule ({name, config, ...}: {
      config = mkIf (config.enable && cfg.useUserPackages && (lib.hasAttr name cfg.users)) {
        packages = [cfg.users.${name}.home.path];
      };
    }));
  };
```

this allows doing funky stuff with users.users like intersecting with home-manager modules eg,

```nix
{lib, /* custom arg */ flake, config, ...}: {
    home-manager.useUserPackages = true;
    home-manager.users = builtins.intersectAttrs (lib.filterAttrs (_: v: v.isNormalUser) config.users.users) (flake.outputs.homeModules.users);
}
```

I can do a PR with this change

**Comment by bmrips** [comment]
> Is there any recommended way to do this nowadays? Using perhaps, only home-manager ?

There is a [`home-manager.sharedModules` option](https://github.com/nix-community/home-manager/blob/ca2ab1d877a24d5a437dad62f56b8b2c02e964e9/nixos/common.nix#L108) with which you can add shared modules.
