### ISSUE TITLE
Installing `fzf` doesn't install vim plugin

### ISSUE THREAD

**Issue by mwillsey** [rycee/home-manager#596]
To install `fzf` in Vim, one needs to add a [directory to the runtime path](https://github.com/junegunn/fzf#as-vim-plugin). This is required even for the use of the [`fzf.vim`](https://github.com/junegunn/fzf.vim) plugin.

The problem is that `fzf` [is a split package](https://github.com/NixOS/nixpkgs/blob/release-18.09/pkgs/tools/misc/fzf/default.nix), and so it doesn't install the needed vim plugin by default, and nothing gets added to the runtime path.

Somewhere in home-manager, this could get fixed by adding the following to `packages.vim.extraConfig`:
```
set rtp+=${pkgs.fzf.out}/share/vim-plugins/${pkgs.fzf.name}
```

Not sure where this could go, so I just did it manually in my config. 

Thanks!

**Comment by kalbasit** [comment]
There's a fzf-vim and a fzfWrapper plugins that you could use for this. See https://github.com/kalbasit/shabka/blob/cb72625ed2f39bc3922c63c4e2b8e8695c2ef482/modules/neovim/default.nix#L56-L57

**Comment by teto** [comment]
Fzfwrapper looks like a solution

**Comment by teto** [comment]
closing as solutions have been proposed, feel free to reopen if that's not the case.
