### ISSUE TITLE
Activation should fail if it needs to overwrite a user file

### ISSUE THREAD

**Issue by rycee** [rycee/home-manager#6]
When switching to a new configuration, the activation should halt and print a helpful message if a non-managed file needs to be overwritten. For example, this should be triggered if a user adds `home.file.hello.text = "foo";` and the `~/hello` path exists as anything other than a link into the Nix store.

**Comment by rycee** [comment]
The activation script is now generated through a new DAG data structure that can force an entry to be before another. I have also added a dummy DAG node called `writeBoundary`.

The intention is to have mutation happen _after_ this node and sanity checks happen _before_ this node. This should allow the sanity checks to exit the script if they find an issue without risking an inconsistent state.

**Comment by shadowrylander** [comment]
Is there a way to overwrite the target file if we want to?

**Comment by rycee** [comment]
@shadowrylander There is a `force` option but it should be considered unofficial and unsupported:
https://github.com/nix-community/home-manager/blob/472ca211cac604efdf621337067a237be9df389e/modules/lib/file-type.nix#L88-L98

**Comment by shadowrylander** [comment]
Ah; warning noted! Thank you kindly!
