### ISSUE TITLE
How are nixos/nixpkgs upgrade handled?

### ISSUE THREAD

**Issue by Mic92** [rycee/home-manager#60]
I see, why you focused on 17.03 in the beginning.
But how do you plan to upgrade to 17.09 and forth?
In other words, I would volunteer to contribute to an unstable branch to provide better upgrade experience.

**Comment by rycee** [comment]
Some time ago I changed the master branch to target unstable NixOS. The "official" Home Manager branch for NixOS 17.03 is release-17.03. The master branch is mostly 17.03 compatible, though, if you avoid some features, like the browserpass module.

So for 17.09 it should just be a matter of branching off release-17.09 from master.

**Comment by Mic92** [comment]
Sounds good to me. The README probably should reflect that.

**Comment by rycee** [comment]
Hmm, I thought I had updated README to mention both NixOS unstable and 17.03. Turned out I had done that change only in the `release-17.03` branch. Cherry-picked the change into master so hopefully it should be a bit clearer now. Thanks for noticing this :-)
