### ISSUE TITLE
Support disabledModules

### ISSUE THREAD

**Issue by Jomik** [rycee/home-manager#602]
We should support something like NixOS's `disabledModules`: https://nixos.org/nixos/manual/index.html#sec-replace-modules
This is quite useful if you want to replace part of a module that you want to improve on or have work differently.
I stumbled upon this while trying to configure polybar.

**Comment by Jomik** [comment]
I figured that this is on my end... I ended up having to set `home-manager` to use a channel, and then I could disable the module using `disabledModules = [ <home-manager/modules/services/polybar.nix> ];`
How would I go about disabling it using a relative path?

**Comment by kalbasit** [comment]
@Jomik are you using a submodule of your git repository? If you're using a fetcher, such as `builtins.fetchTarball`, you can just use the `$out` of that fetcher.

**Comment by Jomik** [comment]
I was using it through `home-manager.path`
So I could have prefixed it with that I guess :o

**Comment by rycee** [comment]
With the above commit it should be possible to use
```
disabledModules = [ "services/polybar.nix" ];
```

**Comment by Jomik** [comment]
Oh awesome
