### ISSUE TITLE
How to install fonts?

### ISSUE THREAD

**Issue by srid** [rycee/home-manager#605]
I use home-manager on a non-NixOS machine (Chromebook). Is there a way to specify installing of third party fonts?

I have the following but that does not seem to work:

```patch
--- a/nix/home.nix
+++ b/nix/home.nix
@@ -19,8 +19,12 @@ in
 {
   programs.home-manager.enable = true;
 
+  fonts.fontconfig.enableProfileFonts = true;
+
   home.packages = with pkgs; [
     (callPackage (import ./nvim/default.nix) {})
+    dejavu_fonts
+    source-serif-pro
     emacs
     # termtosvg -- fails on unstable
     aria
```

**Comment by wedens** [comment]
Have you tried running `fc-cache -f`? home-manager doesn't do it automatically (https://github.com/rycee/home-manager/issues/520).

**Comment by rycee** [comment]
Yeah, I've been meaning to come up with something nice for including the `fc-cache` but have been short of time.

**Comment by kalbasit** [comment]
The solution [given there](https://github.com/rycee/home-manager/issues/520#issuecomment-451759097) looks pretty good to me. Maybe @wedens can submit a pull request that closes both issues?

**Comment by srid** [comment]
Okay. Yea, definitely +1 for automatically updating the font cache. This is one of the appeals of using Nix; declaratively specify stuff and everything is automagically taken care of without manual intervention.

**Comment by pinpox** [comment]
Was this implemented/added or do I need to take care of updating the cache myself? My font's are not working, font this when searching for previous font issues

**Comment by rycee** [comment]
@pinpox Yes, it should now update the cache for any font installed through `home.package`, but only if `fonts.fontconfig.enable` is `true`. See #682.

**Comment by masaeedu** [comment]
Would it make sense to add some documentation that explains to how to add fonts to a home-manager config? There is `fonts.fontconfig.enable = true`. Where does the list of fonts (and if necessary, other configuration) go?

**Comment by sevillaarvin** [comment]
> Would it make sense to add some documentation that explains to how to add fonts to a home-manager config? There is `fonts.fontconfig.enable = true`. Where does the list of fonts (and if necessary, other configuration) go?

I placed them in `home.packages`.

```nix
    home.packages = with pkgs;
      [ # ...various
        dejavu_fonts
        powerline-fonts
      ];

    fonts.fontconfig.enable = true;

```

After which home-manager installed the fonts in `$HOME/Library/Fonts/HomeManager/*` (macos)

**Comment by srid** [comment]
As a note to self, I added the instructions here:

https://nixos.asia/en/tips/hm-fonts
