### ISSUE TITLE
programs.ssh.matchBlocks.<name?>.identityFIle should be a list

### ISSUE THREAD

**Issue by bemeurer** [rycee/home-manager#625]
The ssh config format allows for multiple identity files to be specified for a host block, like such
```
Host * !github.com
    ForwardAgent yes
    IdentityFile ~/.ssh/bemeurer_rsa
    IdentityFile ~/.ssh/standard_rsa
    IdentitiesOnly yes
```
The current implementation in `programs.ssh.matchBlocks` doesn't allow for this, since repeating the `identityFile` attribute is illegal.

**Comment by rycee** [comment]
Good point! I've made it so you can assign a list to `identityFile`. For example
```
identityFile = ["~/.ssh/bemeurer_rsa" "~/.ssh/standard_rsa"];
```

**Comment by bemeurer** [comment]
@rycee Awesome! Take a look at #627 as well if you can! Loving home-manager!
