### ISSUE TITLE
Feature Request: Swaywm support

### ISSUE THREAD

**Issue by cvoges12** [rycee/home-manager#629]
Currently there is no option to configure swaywm. There is some development already for sway in nixpkgs but nothing exists for actually configuring the window manager. Despite that, it would be more sensible to configure it at the user level which seems more fit for home-manager.

Also, one of the highlighting features of swaywm is that it has almost identical configurations to i3wm. Most i3 configs can be ported to sway as a simple drop in place with the change of a few function / command names. 

So this would be an almost identical configuration of `xsession.windowManager.i3` for a `xsession.windowManager.sway`. Some parts from `programs.sway` in nixpkgs could be borrowed as well. Such configurations would enable wayland and wlroots if needed.

I'm not too familiar with nix lang but this seems to fit like a glove and to be within the scope of home-manager. If anyone would like to tackle this along side me, that would be great.

**Comment by rycee** [comment]
@gnidorah started a bit of work on supporting sway in #572 but that ticket got closed in favor of creating a proper sway module. It would certainly be nice to have 🙂

**Comment by cvoges12** [comment]
@rycee Is there any progress on the module?

**Comment by cvoges12** [comment]
I would be more than happy to pick up from where anyone else left off.

**Comment by uvNikita** [comment]
@cvoges12 Thanks for your interest! I haven't started to work on it, but the basic idea is to have one common module for `xsession.windowManager.sway` and `xsession.windowManager.i3` that would change a couple of options depending on which one is used.

Another thing to figure out is how to start a wayland window manager via home-manager. My guess is that the regular `xsession.windowManager.command` way will not work. I guess @rycee will probably have some ideas around that :)

Btw, does `xsession.windowManager.sway` name even makes sense considering that there is no xsession involved? :)

**Comment by cvoges12** [comment]
@uvNikita I'd prefer to have a separate `wayland.windowManager.sway` than including it in `xsession` tbh. You're right in that it does not make much sense to include it in as it has little to nothing to do with the X window system.

For starting it, there's already an expression for that in nixpkgs which we could "borrow" to complete this. There's another for wlroots as well. I suppose if we go far enough to make a sway module then we should include a wlroots module too.

**Comment by cvoges12** [comment]
Here are the mentioned nixpkgs:
* [Sway](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/sway.nix)
* [Wlroots](https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/libraries/wlroots)

Also, I found this. It is an overlay for sway and wlroots:
* [nix-wayland](https://github.com/colemickens/nixpkgs-wayland)

**Comment by rycee** [comment]
I still have to read up on Wayland but it certainly seems like it would make sense to have it outside the xsession "namespace" 🙂

**Comment by bbigras** [comment]
This issue can be closed.

**Comment by dermetfan** [comment]
Closing as #829 got merged.
