### ISSUE TITLE
programs.tmux.secureSocket unused

### ISSUE THREAD

**Issue by arcnmx** [rycee/home-manager#631]
This option doesn't seem to be used anywhere?

**Comment by rycee** [comment]
@kalbasit Perhaps you could help a bit with this? I know very little about tmux.

**Comment by kalbasit** [comment]
I believe I copied the option over, but not the [actual implementation](https://github.com/NixOS/nixpkgs/blob/7bff7389c4c141f175412ef9b47c652d8d645a03/nixos/modules/programs/tmux.nix#L179-L181). I'll file a PR to copy the implementation over.

**Comment by rycee** [comment]
@kalbasit Thanks for the fix!
