### ISSUE TITLE
Invalid package attribute when installing home-manager as a nixos module

### ISSUE THREAD

**Issue by WhosCounting** [rycee/home-manager#646]
Hi, thank you very much for home-manager, I love using it. 

So, I've been using home-manager as a nixos module for a while now and everything was working smoothly until today, when at some point I tried running `sudo nixos-rebuild switch`. This resulted in an error:

```
building Nix...
unpacking 'https://github.com/rycee/home-manager/archive/master.tar.gz'...
building the system configuration...
error: Invalid package attribute path `qgnomeplatform'
(use '--show-trace' to show detailed location information)
```

Relevant part of my `configuration.nix`:
 ```
  imports =
     [ # Include the results of the hardware scan.
       ./hardware-configuration.nix
       "${builtins.fetchTarball https://github.com/rycee/home-manager/archive/master.tar.gz/nixos"
       ./users.nix
       ...
     ];
```

`users.nix` contains a lot of stuff but nothing fancy really.
When I moved the whole thing to `home-manager` program everything worked fine again. Do you know what could be the issue here?

[Output of `sudo nixos-rebuild build --show-trace`](https://pastebin.com/uqA5k3ag)

**Comment by MichaelBergquistSuarez** [comment]
I'm having this problem aswell.

I suppose this commit might be related
https://github.com/rycee/home-manager/commit/995fa3af36a6555dcf302117b71edbee0d7542f5

**Comment by MichaelBergquistSuarez** [comment]
I tested using 03162970cd6dadfac58f169cd50aed5a5aeec14f instead of master. That one builds. So yeah, it is 995fa3af36a6555dcf302117b71edbee0d7542f5 that's the culprit

**Comment by rycee** [comment]
You are most likely using the master branch of Home Manager together with the 18.09 version of Nixpkgs. You should use the release-18.09 branch of Home Manager. That is, https://github.com/rycee/home-manager/archive/release-18.09.tar.gz instead of https://github.com/rycee/home-manager/archive/master.tar.gz.

**Comment by WhosCounting** [comment]
Yes, this helped, thanks! I'm closing this then (hope this helps @MichaelBergquistSuarez too).

**Comment by MichaelBergquistSuarez** [comment]
Yeah, you are correct @rycee! That's how I was using it. @WhosCounting, it works for me too

Thanks for the fast response as usual

**Comment by fricklerhandwerk** [comment]
The same problem applies to 19.03, as the commit is in there as well.

**Comment by rycee** [comment]
@fricklerhandwerk Hmm, the `qgnomeplatform` package is in the release-19.03 branch so it should work fine. Are you certain you don't accidentally have some 18.09 lingering around?

**Comment by fricklerhandwerk** [comment]
Ah yes, my bad. I was switching between 18.09 and 19.03 installations for testing and in this case I ran a 19.03 `home-manager` on 19.03 NixOS.
