### ISSUE TITLE
Broken on 18.09

### ISSUE THREAD

**Issue by arcnmx** [rycee/home-manager#647]
As of 995fa3af36a6555dcf302117b71edbee0d7542f5:

nix build -f test.nix
error: Invalid package attribute path `qgnomeplatform'

```nix
import <nixpkgs/nixos> {
  configuration = {
    imports = [<home-manager/nixos>];

    boot.isContainer = true;
    home-manager.users = {
      root = _: {
      };
    };
  };
}
```

**Comment by rycee** [comment]
You need to use the release-18.09 branch of Home Manager. See https://github.com/rycee/home-manager/issues/646#issuecomment-480044610.

**Comment by arcnmx** [comment]
Sorry, I didn't read far enough down in the README.
