### ISSUE TITLE
Feature Request: Activating Numlock on Bootup

### ISSUE THREAD

**Issue by LinArcX** [rycee/home-manager#651]
Right now only if you have sddm, [you can enable numlock](https://github.com/NixOS/nixpkgs/pull/12619). But what happend if somebody like to use startx and also want numlock to be turn on?
https://wiki.archlinux.org/index.php/Activating_Numlock_on_Bootup#startx

**Comment by evanjs** [comment]
Got bored and realized I'd like this, too.
Can make a PR if there's a need.
Haven't contributed to home-manager before, though, so I'm sure there's stuff I'm missing in my [implementation](https://github.com/evanjs/home-manager/commit/91172849bf0d230c932ee0bd6ed88d2dc2201608).
