### ISSUE TITLE
home-manager switch forcibly restarts emacs service

### ISSUE THREAD

**Issue by Ralith** [rycee/home-manager#668]
With `services.emacs.enable = true`, updating your environment kills emacs, which causes all your open buffers to be lost. This is not ideal. It should probably be blacklisted from restarts the same way e.g. X is in NixOS.

**Comment by rycee** [comment]
Yeah, that's quite annoying I can imagine 😟

If you have the chance, please give the branch in #670 a try, hopefully it will fix the issue.

**Comment by Ralith** [comment]
> Not restarting: emacs.service
Seems to work, thanks!
