### ISSUE TITLE
Invalid package attribute path `qgnomeplatform`

### ISSUE THREAD

**Issue by willbasky** [rycee/home-manager#678]
I tried to install `home-manager` on NixOS 19.03 following the README and got next error:

```
$ nix-shell '<home-manager>' -A install 

Creating initial Home Manager generation...

error: Invalid package attribute path `qgnomeplatform'
(use '--show-trace' to show detailed location information)

There are 70 unread and relevant news items.
Read them by running the command 'home-manager news'.


Uh oh, the installation failed! Please create an issue at

    https://github.com/rycee/home-manager/issues

if the error seems to be the fault of Home Manager.
```
What should I do?

**Comment by rycee** [comment]
Not by my computer but it looks like you still have some traces of 18.09. The qgnomeplatform package is new in 19.03.

On April 15, 2019 10:32:04 AM GMT+02:00, Vladislav Sabanov <notifications@github.com> wrote:
>I tried to install `home-manager` on NixOS 19.03 following the README
>and got next error:
>
>```
>$ nix-shell '<home-manager>' -A install 
>
>Creating initial Home Manager generation...
>
>error: Invalid package attribute path `qgnomeplatform'
>(use '--show-trace' to show detailed location information)
>
>There are 70 unread and relevant news items.
>Read them by running the command 'home-manager news'.
>
>
>Uh oh, the installation failed! Please create an issue at
>
>    https://github.com/rycee/home-manager/issues
>
>if the error seems to be the fault of Home Manager.
>```
>What should I do?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rycee/home-manager/issues/678

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by willbasky** [comment]
@rycee thank you for the reply.
After your comment, I checked and found NixOS version was 18.09. Now I rebuild with upgrade flag to 19.03 channel, but a `home-manager` installation got the same error.
How to eliminate 18.09's traces?

**Comment by rycee** [comment]
Hmm, what do you mean by upgrade flag? You mean `system.stateVersion`?

What does
```console
$ nix-channel --list
```
say? Note, you may have to run it as root.

**Comment by willbasky** [comment]
> Hmm, what do you mean by upgrade flag? 

I meant `nixos-rebuild --upgrade switch`

`$ nix-channel --list` shows 
```
home-manager https://github.com/rycee/home-manager/archive/master.tar.gz
nixos https://nixos.org/channels/nixos-19.03
```

**Comment by MasseRelex** [comment]
AFAIK you need to set up your roots nixos channel. In my experience none of the nix commands can understand the user specific channels.

**Comment by willbasky** [comment]
@MasseRelex I guess, i got what you mean
```
$ sudo nix-channel --list
nixos https://nixos.org/channels/nixos-18.09
```
right?

**Comment by MasseRelex** [comment]
Exactly

**Comment by willbasky** [comment]
Cool, thank you! Works.
