### ISSUE TITLE
vim: handling multiple boolean options with `listOf`

### ISSUE THREAD

**Issue by paluh** [rycee/home-manager#69]
Hi,

I'm new to Nix (I've installed it yesterday) and I don't know much about coding conventions and best practices, so maybe this is stupid question.

Do you think that we can handle simple boolean options values using `listOf` - I mean adding `setOptions` to configure simple "on/off" options:
   ``` nix
   {
     programs.vim = { 
       enable = true;
       setOptions = ["expandtab" "relativenumber" "nonumber" "list"];
     };
   }  
   ```
I think that advantages of this approach are that we can quickly add massive amount of options (selectively coping them from `:set all`) and prevent simple typo bugs etc.

On the other hand there will be inconsistency between this approach and other options handling like for example no docs/descriptions. This approach introduces possibility of other kinds of bugs - for example duplication (e.g. `setOptions = ["expandtab", "expandtab"]`), inconsistencies (e.g. `setOptions = ["expandtab", "noexpandtab"];`) and probably others ;-)

[Here](https://github.com/paluh/home-manager/commit/16e45187f8b9c3b67603842d197ce8d142d0ed48) really simple and quick prototype.

**Comment by rycee** [comment]
Hmm, in principle I think this would work but realistically it seems difficult to do in a nice way that allows "massive amounts of options". Of course, the way it is currently done would not scale to many options either. My main concern in both cases is documentation (I'd prefer not to have the man page be 90% vim options 😃) and possibly performance.

Perhaps with a custom submodule that acts much like `types.enum` but checks for duplicates and inconsistent options (`[ "xyz" "noxyz" ]`) and documents it as simply "boolean VIM option" instead of a huge "one of …".

Very tricky to find a balance here. Maybe the 80/20 rule would work? Like supporting 20% of the most common VIM options would be sufficient for 80% of users? The rest would have to use the extra configuration. But maybe 20% of VIM options still is a large number?

To complicate things further, here is another possible method in example form:
```nix
{
  programs.vim = {
    enable = true;
    plugins = [ "YankRing" ];
    settings = {
      expandtab = true;
      number = false;
      history = 1000;
      background = "dark";
    };
    extraConfig = ''
      hi cursorline guibg=\#333333
    '';
  };
}
```
where the type of `programs.vim.settings` is basically `types.attrs`.

**Comment by paluh** [comment]
I like your `settings` API much better then mine `listOf` based. I wonder if with `types.attrs` we don't have to add additional validation layer (like checking types, attrs names etc.). Does option with type `types.attrs` accept any set of values?
In general I think that If this "shortcuts" would introduce a lot of "magic" or additional logic or inconsistencies maybe we should stick with proper option handling (like it is done right now) and add only most commonly used  as you suggested.

**Comment by rycee** [comment]
An option with `types.attrs` will indeed accept any value and any field name. If one would like extra validation (and documentation) then this would be done by creating a new type that acts much like `types.attrs` but which does these tasks.

This `types.attrs` trick is used elsewhere in Home Manager (and also NixOS). For example in [xresources.nix](https://github.com/rycee/home-manager/blob/master/modules/xresources.nix).

**Comment by paluh** [comment]
I've just finished simple validation experiment on a branch:

https://github.com/paluh/home-manager/commit/fe8f3831497b35b97dd282260f467e6aeb08a1b8

Do you think that this approach - separate declaration of `booleanSettings = [ "expandtab" "number" ]`  and its usage in type `check` as well as fin inal config generation is acceptable?

**Comment by paluh** [comment]
I'm not sure if with `settings` approach we can handle error reporting nicely and easily - I've tried it on my naive implementation and it seems that any error inside `settings` configuration would be reported without any details. [On this branch](https://github.com/paluh/home-manager/commit/aa6df87ec2a63dc1ed85ee0ebcc15161ff2cef77) in case of any type error inside `settings` value I'm getting:

    error: The option value `programs.vim.settings' in `<unknown-file>' is not a null or vim settings.

I'm not sure if you would like another approach as it would add more docs for sure, but [on this branch](https://github.com/paluh/home-manager/commit/a3a5224b691c523d830b8822bf89d632ee7dab5f) I'm just building dynamically proper boolean options with really simple description ("set [no]${option}") and I'm using convention there that option name is just final vim setting name.

**Comment by paluh** [comment]
I've [added](https://github.com/rycee/home-manager/commit/3d8503e4b6433991db902d1c947f3a86d3ed11e3) also some common integer options on this branch...

**Comment by rycee** [comment]
Yeah, that is a bit closer to what I was thinking of but it seems a bit too complicated. Maybe something like
```patch
diff --git a/modules/programs/vim.nix b/modules/programs/vim.nix
index e246c21..8355bee 100644
--- a/modules/programs/vim.nix
+++ b/modules/programs/vim.nix
@@ -7,6 +7,34 @@ let
   cfg = config.programs.vim;
   defaultPlugins = [ "sensible" ];
 
+  vimKnownSettings = {
+    background = types.str;
+    expandtab = types.bool;
+    history = types.int;
+    number = types.bool;
+    relativenumber = types.bool;
+  };
+
+  vimSettingsType = types.submodule {
+    options =
+      let
+        opt = name: type: mkOption {
+          type = types.nullOr type;
+          default = null;
+          visible = false;
+        };
+      in
+        mapAttrs opt vimKnownSettings;
+  };
+
+  setExpr = name: value:
+    let
+      v =
+        if isBool value then (if value then "" else "no") + name
+        else name + "=" + toString (traceShowVal value);
+    in
+      optionalString (value != null) ("set " + v);
+
 in
 
 {
@@ -37,6 +65,19 @@ in
         '';
       };
 
+      settings = mkOption {
+        type = vimSettingsType;
+        default = {};
+        example = literalExample ''
+          {
+            expandtab = true;
+            history = 1000;
+            background = "dark";
+          }
+        '';
+        description = "Basic Vim settings.";
+      };
+
       extraConfig = mkOption {
         type = types.lines;
         default = "";
@@ -64,6 +105,10 @@ in
         ${optionalInteger "tabstop" cfg.tabSize}
         ${optionalInteger "shiftwidth" cfg.tabSize}
 
+        ${concatStringsSep "\n" (
+          mapAttrsToList setExpr (
+          builtins.intersectAttrs vimKnownSettings cfg.settings))}
+
         ${cfg.extraConfig}
       '';
```

**Comment by paluh** [comment]
Cool!

I think that I can close my pull request as your proposition incorporates my minor fixes. I would open another one just with more options when you push your changes!

Thanks a lot for this nix lesson!

**Comment by rycee** [comment]
@uvNikita Mind having a look at the diff I included in https://github.com/rycee/home-manager/issues/69#issuecomment-330880613. Does the basic idea seem reasonable to you? If so it needs some cleanups, e.g., the description of `settings` would need to be expanded quite a lot.

**Comment by uvNikita** [comment]
From all suggestions, I like your version the most @rycee. If we could implement it that way, it would be a super good extension of the module! @paluh thank you for taking the initiative :)
