### ISSUE TITLE
vscode.haskell: attribute 'justusadam' missing

### ISSUE THREAD

**Issue by srid** [rycee/home-manager#691]
To reproduce:

```nix
  programs.vscode = {
    enable = true;
    haskell.enable = true;
  };
```

Expect to see:

```
error: attribute 'justusadam' missing, at /home/srid/code/home-manager/modules/programs/vscode/haskell.nix:61:9
```

**Comment by rycee** [comment]
Are you using Nixpkgs 19.03? It seems the `vscode-extensions.justusadam.language-haskell` package is only available in Nixpkgs master.

**Comment by rycee** [comment]
@roberth Would it be safe to backport the [2864f5a9676f1b6bcaa7b337d5f229cab4210052](https://github.com/NixOS/nixpkgs/commit/2864f5a9676f1b6bcaa7b337d5f229cab4210052) commit to Nixpkgs 19.03?

**Comment by roberth** [comment]
@rycee That is safe afaict. Note that it is not built by Hydra, so it requires manual testing. You may want to include https://github.com/NixOS/nixpkgs/pull/57829/commits/340e21473f20ca32492bf24613d5d3c1cf46df89 as well.

**Comment by rycee** [comment]
Closing since they are in 19.03 now.
