### ISSUE TITLE
Install fails with `tput: unknown terminal "rxvt-unicode"`

### ISSUE THREAD

**Issue by dzanot** [rycee/home-manager#706]
Hello, new to nix and using home-manager to learn. 
Stepping through the readme and running `nix-shell '<home-manager>' -A install` fails at the end with a tput error `tput: unknown terminal "rxvt-unicode"`. Looking at a related issue https://github.com/rycee/home-manager/issues/423 I changed `TERM=rxvt`  and it worked, but this feels "dirty" and I'd like to not lie here.  
I installed from the release-19.03 channel
I am on an Ubuntu 16.04 xfce variety (GalliumOS 2.1) and manually calling `tput -T "rxvt-unicode"` does not error.

**Comment by dzanot** [comment]
Re-reading @rycee s comment here https://github.com/rycee/home-manager/issues/423#issuecomment-431185028 I just set `TERMINFO_DIRS=/lib/terminfo` and that did the trick. I suppose this isn't much of an issue anymore so I will close, hopefully this will help others. Thanks for your project Robert :)

**Comment by rycee** [comment]
Glad it worked out for you! 👍
