### ISSUE TITLE
systemd.user.startServices should start sockets

### ISSUE THREAD

**Issue by leo60228** [rycee/home-manager#708]
Socket-activated services should be started automatically as well.

**Comment by rycee** [comment]
Hmm, won't they get started automatically when there is incoming traffic on the socket?

**Comment by leo60228** [comment]
@rycee The socket doesn't get created, meaning that it can't be connected to.

**Comment by Gerschtli** [comment]
I would like to see this feature too. Maybe I can dig around an provide a PR for this
