### ISSUE TITLE
firefox, preinstalled certificates

### ISSUE THREAD

**Issue by tfc** [rycee/home-manager#728]
Hi there,

does anybody have a home manager nix expression that installs certain HTTPS certificates into firefox?

For chrome and other clients, this works pretty well with the following stuff in my `/etc/nixos/configuration.nix`:

```nix
{
  environment.variables = let
    ca-bundle = "/etc/ssl/certs/ca-bundle.crt";
  in {
    CURL_CA_BUNDLE = ca-bundle;
    GIT_SSL_CAINFO = ca-bundle;
    SSL_CERT_FILE  = ca-bundle;
    NIX_SSL_CERT_FILE = ca-bundle;
  };
  security.pki.certificates = [ " ...certificates... " ];
}
```

...for Firefox this never worked. Now that i am managing my browsers from `home.nix` anyway and would like to ditch chrome, i wonder if there is a way that works for Firefox?

**Comment by Mic92** [comment]
Firefox uses its own certificates and ignores anything installed on the machine.
You can however import certificates into your firefox profile: https://askubuntu.com/questions/244582/add-certificate-authorities-system-wide-on-firefox

**Comment by tfc** [comment]
So... one could write a Firefox wrapper script that checks if the certificate is installed and installs it as needed, and that's the only possibility?

**Comment by Mic92** [comment]
Either that or some sort of activation script. It might be also possible to use p11-kit in the way described here: https://askubuntu.com/a/1036637

**Comment by tfc** [comment]
That looks very interesting. Is my naive intuition right that this can be done in 2 steps like the following:

1. create a derivation of `p11-kit` that contains a symbolic link with the `.so` name that firefox assumes that leads to the p11 kit lib
1. override the firefox derivation with this [`replace-dependency`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/replace-dependency.nix) so it uses that library

Would it be done this way, or am i misdirected here?

**Comment by Mic92** [comment]
LD_PRELOAD or prepending the library in RPATH of the firefox binary with patchelf might also work.

**Comment by tfc** [comment]
thank you for all the suggestions. I tried multiple things but i did not come to a satisfactory solution. Posted this here: https://discourse.nixos.org/t/getting-firefox-to-work-with-p11-kit-to-use-system-wide-installed-certificates/3175 becasue i think this is not a `home-manager` problem but a general nix thing and hence i am closing this ticket here.
