### ISSUE TITLE
Template services breaks reloadSystemD 

### ISSUE THREAD

**Issue by nyarly** [rycee/home-manager#730]
I haven't dug too deeply into this yet, but having set up a template service to run lorri for various project workspaces, I've started to get this error on switch:

```
Activating reloadSystemD
Failed to get properties: Unit name lorri@.service is neither a valid invocation ID nor unit name.
```

It seems like the reloadSystemD module is too sensitive about bad state in systemD? I know that any broken service unit seems to prevent it working as well.

**Comment by Shados** [comment]
I have the same problem.

**Comment by RoGryza** [comment]
I'm having the same problem. Any workarounds?

**Comment by rycee** [comment]
This might be fixed now, please update and try again.

**Comment by Shados** [comment]
@rycee nope. I'm still getting the `Failed to get properties: Unit name ...` message.

**Comment by rycee** [comment]
@Shados Hmm, are you using the master or release-19.09 branch?

**Comment by Shados** [comment]
I'm using master.

**Comment by rycee** [comment]
@Shados Hmm, curious. Have you found anything relevant in the journal? And can you confirm that it really was a version of `systemd-activate.rb` containing https://github.com/rycee/home-manager/commit/28401ddd913d046ec77ce00d67d845e33bb9f075 that was run?

**Comment by Shados** [comment]
@rycee After some digging, it looks like I was using the "legacy" `systemd-activate.sh`, which still has this issue. After toggling `systemd.user.startServices` to `true`, the ruby version does appear to work. That said... why is the bash version the "legacy" option if it is enabled by default...?

**Comment by rycee** [comment]
@Shados Cool, glad it worked out. The Ruby script can't be default since we it would force a large dependency on people just for one script. The switching will be done by a binary program at some point in the future.
