### ISSUE TITLE
useUserPackages doesn't symlink hm-session-vars.sh below /etc/profiles

### ISSUE THREAD

**Issue by ua74e3dqka** [rycee/home-manager#735]
I am using hm as a nixos module on nixos-unstable. As I do not let it manage my X session I source hm-session-vars.sh manually:
```
programs.home-manager.programs.bash = {
      enable = true;
      initExtra = ''
        source ~/.nix-profile/etc/profile.d/hm-session-vars.sh
     ''
```
Unfortunately as the title states there is no link below `/etc/profiles/per-user/<user>/`

**Comment by rycee** [comment]
The `hm-session-vars.sh` file is sourced by the bash module and only need to be sourced if you don't want HM to manage your bash configuration. In your case it should be safe to simply remove
```
      initExtra = ''
        source ~/.nix-profile/etc/profile.d/hm-session-vars.sh
     ''
```
and it should automatically source the right file. See
https://github.com/rycee/home-manager/blob/cf0aad391c10473fa7613dcc41b1f6a366d03148/modules/programs/bash.nix#L182-L190

Did it say somewhere that this file needs to be sourced if HM doesn't manage X? If so, please let me know so I can fix that.

**Comment by ua74e3dqka** [comment]
Ah, I guess it's my bad, the real issue lies within SDDM ignoring .profile. 

>Did it say somewhere that this file needs to be sourced if HM doesn't manage X? If so, please >let me know so I can fix that.

Nope you didn't, my brain _thought_ you did :smile:

**Comment by rycee** [comment]
Cool, then I'll close this 🙂
