### ISSUE TITLE
Support VSCode configuration for OS X

### ISSUE THREAD

**Issue by macalinao** [rycee/home-manager#737]
Here's what I use:

```
  home.file."Library/Application Support/Code/User/settings.json".source =
    "${config.home.homeDirectory}/.config/Code/User/settings.json";
```

It would be cool if home-manager supported this natively.

**Comment by rycee** [comment]
Hmm, doesn't vscode honor the XDG config dir in macOS?

In any case, I guess it would be possible to use that path instead if the platform is darwin?

**Comment by macalinao** [comment]
I don't think so. At least, not on my machine. I think that seems like a good solution.
