### ISSUE TITLE
Cannot set multiple environment variables for systemd service

### ISSUE THREAD

**Issue by znewman01** [rycee/home-manager#745]
systemd.user.services.<service>.Service.Environment expects a string of the form "ENV_VAR=value", but the systemd service INI file can handle multiple "Environment" lines:

```
...
[service]
Environment=FOO=bar
Environment=BAZ=qux
...
```

Nix, of course, doesn't like it when you try to provide two values for `Environment`.

Right now I'm working around this by sticking a "\nEnvironment=" in the middle, which is pretty gross. I assume that either we'd want to change the type of value allowed for "Environment" or there's some other trick I'm missing.

If you want a copy-paste-able example (adapted from https://nixos.wiki/wiki/Dropbox):

```
 systemd.user.services.dropbox = {
    Unit = {
      Description = "Dropbox";
    };

    Install = {
      WantedBy = [ "graphical-session.target" ];
    };

    Service = {
      # Hack!
      Environment = "QT_PLUGIN_PATH=/run/current-system/sw/${pkgs.qt5.qtbase.qtPluginPrefix}\nEnvironment=QML2_
IMPORT_PATH/run/current-system/sw/${pkgs.qt5.qtbase.qtQmlPrefix}";
      ExecStart = "${pkgs.dropbox.out}/bin/dropbox";
      ExecReload = "${pkgs.coreutils.out}/bin/kill -HUP $MAINPID";
      KillMode = "control-group"; # upstream recommends process
      Restart = "on-failure";
      PrivateTmp = true;
      ProtectSystem = "full";
      Nice = 10;
    };
  };
```

**Comment by rycee** [comment]
It should work to assign a list to the `Environment` variable. In the example you gave can try to replace
```
Environment = "QT_PLUGIN_PATH=/run/current-system/sw/${pkgs.qt5.qtbase.qtPluginPrefix}\nEnvironment=QML2_IMPORT_PATH/run/current-system/sw/${pkgs.qt5.qtbase.qtQmlPrefix}";
```
by
```
Environment = [
  "QT_PLUGIN_PATH=/run/current-system/sw/${pkgs.qt5.qtbase.qtPluginPrefix}"
  "QML2_IMPORT_PATH/run/current-system/sw/${pkgs.qt5.qtbase.qtQmlPrefix}"
];
```

**Comment by znewman01** [comment]
Oh wow, I totally missed that. Works great, thanks :)

It puts everything on one "Environment" line, but that seems allowed per the [systemd manual](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines).
