### ISSUE TITLE
mbsync: extra config goes at end of .mbsyncrc, should go at beginning

### ISSUE THREAD

**Issue by znewman01** [rycee/home-manager#748]
Cause [here](https://github.com/rycee/home-manager/blob/master/modules/programs/mbsync.nix#L178).

The issue is that the .mbsyncrc format is section-based; if you have any accounts/channels/etc., the given configuration will *not* be global, but rather happen to go in the last account/channel defined.

**Comment by rycee** [comment]
Good point, I have tried sorting this out in the above commit.

**Comment by znewman01** [comment]
Looks perfect, will verify that the change works but assume it did if you don't hear from me!
