### ISSUE TITLE
fzf bash integration is prepended before initExtra

### ISSUE THREAD

**Issue by diegs** [rycee/home-manager#755]
When enabling fzf, the bash scripts it sources are *prepended* to `initExtra`.

Unfortunately, that means the fzf config is loaded assuming emacs keybindings and becomes invalidated when I `set -o vi` in `initExtra`. If I remove `set -o vi` the fzf shortcuts (`C-c` etc) work great. The solution would be to have `set -o vi` run before the fzf scripts are sourced.

Relevant home-manager configuration snippets:

```
programs.fzf = {
  enable = true;
  enableBashIntegration = true;  # the default
};

programs.bash = {
  enable = true;
  initExtra = "set -o vi"; 
};
```

Generally, I don't understand the nix magic that merges the two configs (i.e. the behavior of this expression: https://github.com/rycee/home-manager/blob/master/modules/programs/fzf.nix#L124). If we could make that append instead of prepend that would be lovely.

FWIW as a workaround I can just set the `fzf.enableBashIntegration = false` and just copy those lines into my own `initExtra`, but it's a little hacky.

**Comment by rycee** [comment]
Does
```
programs.bash = {
  enable = true;
  initExtra = mkBefore "set -o vi"; 
};
```
work?

**Comment by diegs** [comment]
Thanks so much, that does work. I suppose there could be a world where you would want some stuff prepended and some postpended, but likely overkill.
