### ISSUE TITLE
ccache

### ISSUE THREAD

**Issue by matthuszagh** [rycee/home-manager#760]
Is there any special setup that needs to be done to get ccache working with packages declared with `home.packages`? I've set `programs.ccache.enable = true` and `programs.ccache.packageNames` in `configuration.nix`. However, packages declared in `home.packages` in `configuration.nix` aren't using ccache.

**Comment by rycee** [comment]
I'm not certain since I've never used ccache with Nixpkgs before. It might be possible to override the pkgs attribute of the Home Manager modules to use the system one. Something like
```
{ pkgs, ... }:

{
  # …

  home-manager.users.matthuszagh =
    let
      systemPkgs = pkgs;
    in
      { ... }: {
        _module.args.pkgs = lib.mkForce systemPkgs;
      };
}
```
But unfortunately you'll likely lose the possibility of having user specific overlays and nixpkgs options.

**Comment by matthuszagh** [comment]
hm yeah that would probably be a no-go for me since i use options and overlays.

**Comment by rycee** [comment]
You might be able to do
```
{ pkgs, ... }:

{
  # …

  home-manager.users.matthuszagh =
    let
      systemPkgs = pkgs;
    in
      { ... }: {
        home.packages = [ systemPkgs.hello ];
      };
}
```
to use the `pkgs` from the system configuration for specific packages. Then user overlays and options would be disabled just for those packages.

**Comment by matthuszagh** [comment]
That does indeed work, or at least it tries to work. However, I'm not
actually sure it makes sense to attempt this anyway. I chatted with
some people on the IRC and it sounds like the only way to use ccache
is through nix-shell. I had been under the mistaken impression that
ccache could be used with declarative nix package management.
