### ISSUE TITLE
zsh: cache directory not created or populated

### ISSUE THREAD

**Issue by madhukar93** [rycee/home-manager#761]
Here's my `oh-my-zsh` attrset -
```
      oh-my-zsh = {
        enable = true;
        theme = "robbyrussell";
        plugins=["git" "tmux" "docker" "python" "vi-mode" "systemd" "z" "kubectl"];
      };

```
the zsh `kubectl` plugin tries to look for completion sources in `ZSH_CACHE_DIR`

`kubectl.plugin.zsh`
 
```
if (( $+commands[kubectl] )); then
    __KUBECTL_COMPLETION_FILE="${ZSH_CACHE_DIR}/kubectl_completion"

    if [[ ! -f $__KUBECTL_COMPLETION_FILE ]]; then
        kubectl completion zsh >! $__KUBECTL_COMPLETION_FILE

```

So it should be set as -
https://github.com/rycee/home-manager/blob/7d68c46feb845c572ef335f824062f90fdebf655/modules/programs/zsh.nix#L302-L307

This is what I get - 
```
/nix/store/zd18w66wch41pz4chj8ainwc4hmik5fr-oh-my-zsh-2019-07-01/share/oh-my-zsh/plugins/kubectl/kubectl.plugin.zsh:5: no such file or directory: /home/madhukar/.cache/oh-my-zsh/kubectl_completion
```

`~/.cache/oh-my-zsh` doesn't even exist

I'm managing home in `configuration.nix` if that makes a difference

**Comment by madhukar93** [comment]
*bump*

**Comment by rycee** [comment]
Does it work if you create `~/.cache/oh-my-zsh`?

**Comment by madhukar93** [comment]
Thank you, this worked.
I should've read the snippet of the plugin that I myself linked. This should have run now -
```
    if [[ ! -f $__KUBECTL_COMPLETION_FILE ]]; then
        kubectl completion zsh >! $__KUBECTL_COMPLETION_FILE
```
Is the creation of the directory something that the zsh module should do if it doesn't exist?

**Comment by teto** [comment]
is ZSH_CACHE_DIR a oh-my-zsh variable or a zsh one ? if the latter, I would think zsh tend not to create folders so the module should.

**Comment by madhukar93** [comment]
based on [searching through zsh repo](https://github.com/zsh-users/zsh/search?q=ZSH_CACHE_DIR&unscoped_q=ZSH_CACHE_DIR) and [oh-my-zsh repo](https://github.com/robbyrussell/oh-my-zsh/search?q=ZSH_CACHE_DIR&unscoped_q=ZSH_CACHE_DIR) it seems to be a oh-my-zsh specific construct

**Comment by teto** [comment]
seems like the oh-my-zsh isnot creating the folder so home-manager should create it.

As for coc.nvim, you could open another issue but I don't think there is any specific issue. My install is hybrid. I just install coc.nvim via nix. The rest of the extensions, I install via vim-plug.

**Comment by uvNikita** [comment]
I'm using oh-my-zsh `docker` plugin which is also utilizing `~/.cache/oh-my-zsh`. However, when I delete the cache folder, `docker` plugin recreates it on the first run, so I guess `kubectl` should originally do the same.

That said, we could probably create this folder automatically as @teto suggested.

**Comment by rycee** [comment]
Can add
```
home.file."${config.xdg.cacheHome}/oh-my-zsh/.keep".text = "";
```
if oh-my-zsh is enabled?

**Comment by uvNikita** [comment]
@rycee neat trick! Created a pull request.

**Comment by madhukar93** [comment]
what's the `.keep` bit for?

**Comment by uvNikita** [comment]
@madhukar93 the `home.file` module can only manage files, not directories, so the `.keep` part tells home-manager to create an empty file called `.keep` in oh-my-zsh cache directory which will result in the parent directory being created as well if it doesn't exist.

Hope this helps :)
