### ISSUE TITLE
dconf fails to infer value of an empty list

### ISSUE THREAD

**Issue by liff** [rycee/home-manager#769]
Given configuration like:

```nix
{
  dconf.settings = {
    "org/gnome/shell/keybindings" = {
      switch-to-application-1 = [];
    };
  };
}
```

home-manager’s invocation of `dconf load` fails with:

    error: [org/gnome/shell/keybindings]: switch-to-application-1: invalid value: []: 0-2:unable to infer type

The generated dconf dump file for this setting looks like:

```
[org/gnome/shell/keybindings]
switch-to-application-1=[]
```

And since the list is empty, `dconf load` doesn’t know what the type of the elements in that list is.

It is possible to specify the type of the empty list explicitly with an annotation like `@as` in this case, and this would fix the problem:

```
[org/gnome/shell/keybindings]
switch-to-application-1=@as []
```

But home-manager doesn’t and cannot generate that annotation because it currently doesn’t know the type of the list elements any better than dconf.

I wonder what would be a good way of adding support for type annotations in `dconf.settings`? I would imagine they are actually only ever needed when the value is an empty list. Perhaps something like `switch-to-application-1 = emptyListOf types.string;` which becomes something like `{ type-annotation = "@as"; value = []; }`, which would then be handled by [`mkIniKeyValue`](https://github.com/rycee/home-manager/blob/c5f35b7ff942d7f5875c0b772b7551c03b431c91/modules/misc/dconf.nix#L12)?

**Comment by rycee** [comment]
Yeah, this is a bit tricky. I think in general one would need a `GVariant` type to be able to represent all possible values, like tuples and such.

I wonder if it would be sufficient for the time being to assume that empty lists are of type "string list"? I had a look at my own dconf database and the vast majority of lists have string elements.

**Comment by liff** [comment]
Sounds good to me, opened a PR for doing exactly that.
