### ISSUE TITLE
Way to not generate nixpkgs/home.nix on install?

### ISSUE THREAD

**Issue by rpearce** [rycee/home-manager#770]
Hi! Thanks for this awesome tool.

Is there a way to disable auto-generating `nixpkgs/home.nix` when installing this? It looks like it comes from here:
https://github.com/rycee/home-manager/blob/2c07829be2bcae55e04997b19719ff902a44016d/home-manager/install.nix#L10-L17

Thanks for any help!

**Comment by rycee** [comment]
Yeah, that's the code that does it. The idea is that the file is generated if it does not already exist. So to avoid the auto-generation you can copy (or symlink) a prepared file to that location before running the installation command.

**Comment by rpearce** [comment]
Gotcha. That makes sense for 99% of people. I'll do one of those things! Thanks for getting back so quick.
