### ISSUE TITLE
nixos, nix completions not working with zsh

### ISSUE THREAD

**Issue by madhukar93** [rycee/home-manager#771]
https://github.com/spwhitt/nix-zsh-completions
Completions should 'just work' I'm assuming. 
<img width="131" alt="nix-zsh" src="https://user-images.githubusercontent.com/7714050/61937355-4c3fdc00-afac-11e9-810d-f28ece062e71.png">

relevant bits from my config:
```
   # this is within home manager
    programs.zsh = {
      enable = true;
      autocd = true;
      enableAutosuggestions = true;

      oh-my-zsh = {
        enable = true;
        theme = "robbyrussell";
        plugins=["git" "tmux" "docker" "python" "vi-mode" "systemd" "z" "kubectl"];
      };
  };
```
Had aslo added this, don't remember because of which doc
```
environment.pathsToLink = [ "/libexec" "/share/zsh" ];
```

works for bash
<img width="115" alt="nix-bash" src="https://user-images.githubusercontent.com/7714050/61936487-7bede480-afaa-11e9-8feb-220d3ae0a6fc.png">

system:

```
➜  ~ nixos-version
19.09pre186408.3d84cffe955 (Loris)
➜  ~ nix --version
nix (Nix) 2.2.2
# nix-channel --list
home-manager https://github.com/rycee/home-manager/archive/master.tar.gz
nixos https://nixos.org/channels/nixos-unstable
nixos-hardware https://github.com/NixOS/nixos-hardware/archive/master.tar.gz
```

**Comment by evanjs** [comment]
So I ran into this the other day, and was able to fix it by enabling ohMyZsh [system-wide](https://github.com/evanjs/nixos_cfg/commit/42828f5a484b277cc244a1a474fe2319c01984b3).

It seems like simply running `compinit` also solves this issue, at least on my end.

**Comment by uvNikita** [comment]
Have you installed nix-zsh-completions? Here is an example configuration:

```
{
  home.packages = [ pkgs.nix-zsh-completions ];
  programs.zsh.enable = true;
}
```

This should enable completion for nix commands.

Let me know if it still doesn't work for you.

**Comment by evanjs** [comment]
> Have you installed nix-zsh-completions? Here is an example configuration:
> 
> ```
> {
>   home.packages = [ pkgs.nix-zsh-completions ];
>   programs.zsh.enable = true;
> }
> ```
> 
> This should enable completion for nix commands.
> 
> Let me know if it still doesn't work for you.

Should that really be necessary, though? 
They're installed when you [enable zsh](https://github.com/spwhitt/nix-zsh-completions#nixos).

**Comment by uvNikita** [comment]
@evanjs good point, completely forgot about it! `nix-zsh-completions` package is added automatically if `zsh.enableCompletion` option is set to true:
https://github.com/rycee/home-manager/blob/bce63e4dff4f770879359d7e61791ba03c6bd89f/modules/programs/zsh.nix#L325

However, as you mentioned, it seems we change it to false when oh-my-zsh is enabled:

https://github.com/rycee/home-manager/blob/bce63e4dff4f770879359d7e61791ba03c6bd89f/modules/programs/zsh.nix#L398-L403

So I think adding the package manually should actually "solve" the issue, but we should fix the module as well so that this workaround is not required.

**Comment by uvNikita** [comment]
@madhukar93 forgot to mention, for zsh completions to start to work you should also add `zsh.enableCompletion = true` to your configuration.

**Comment by madhukar93** [comment]
I didn't add it since I thought `oh-my-zsh` implicitly calls `compinit`. Will try this.
