### ISSUE TITLE
screen-locker does not lock screen

### ISSUE THREAD

**Issue by Gerschtli** [rycee/home-manager#773]
Hello!

Maybe I am not getting the hang of it, but I added the following in my `home.nix`:
```nix
{
  services.screen-locker = {
    enable = true;
    lockCmd = "${pkgs.i3lock}/bin/i3lock -n";
    inactiveInterval = 1;
  };
}
```

I now expect two things to work:
1. After one minute of inactivity the screen gets locked
2. Running `loginctl lock-session` locks the screen

In both cases nothing happens. The only thing I could observe were following messages which got logged in `journalctl` after running `loginctl lock-session`:
```
Jul 27 12:18:03 argon polkitd[985]: Registered Authentication Agent for unix-process:22086:325888 (system bus name :1.132 [/run/current-system/sw/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Jul 27 12:18:03 argon polkitd[985]: Unregistered Authentication Agent for unix-process:22086:325888 (system bus name :1.132, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
```

Did I forget some config options or is this a bug? In case of a bug, I would love to create a PR if anyone can give me a hint on whats the error here.

**Comment by uvNikita** [comment]
Have you tried to log out from your session or even reboot? As far as I remember, `xss-lock` can't be started as a systemd service, so we had to put it in `~/.xsession` file which is read only when new X session starts. `xss-lock` provides integration with systemd (loginctl), so it would explain this behavior.

**Comment by Gerschtli** [comment]
Ah, you are completely right, I forgot to logout.. Thank you!
