### ISSUE TITLE
Feature request: Add "--option" as a supported argument passed to nix-build

### ISSUE THREAD

**Issue by leotaku** [rycee/home-manager#784]
I think the title pretty much explains the feature I would like to request.

My personal usecase for this is specifying the `builders` that will be used, however I imagine this should be useful for a multitude of other things.

**Comment by rycee** [comment]
I'm not certain I understand what you are looking for. Please update the title to include information about where you would like to have `--option`, what you would expect it to do, and ideally also a could of examples.

**Comment by leotaku** [comment]
Right,I  hope the following explains what I would like to see:

## What
Most, nix commands (eg. nix-build, nix-env, nix) support a `--option` argument. Using it many lower-level nix-related options like which builders to use, whether to build in the sandbox, ..., can be configured.

Full reference [in the nix manual](https://nixos.org/nix/manual/#description-41)

## Where
Nix allows this flag before and after positional arguments, so I think it would make sense to mimic that behavior.

## Examples
```sh
home-manager --option builders '' switch # build everything locally
home-manager --option cores 1 switch # use only one core for building
```

**Comment by rycee** [comment]
Thanks for the clarification! I think this should be fixed now.
