### ISSUE TITLE
Q: conditional configuration per host type

### ISSUE THREAD

**Issue by league** [rycee/home-manager#8]
First, thanks so much for home-manager — even in its “early development” state, it's really quite useful, and exactly what I had hoped to find when I first started using NixOS.

Do you have any recommendations for making a `home.nix` that can conditionally configure systems based on whether they are headless vs. GUI or laptop vs. desktop or Linux vs. Mac? This may be a general question about the Nix language itself, but I feel the need for it more acutely in home-manager. (I think maybe the OS type is a variable one can access in Nix, but I can't find one for the hostname or similar.)

Right now my workaround is something like this: the conditionalized `home.nix` has an extra parameter set with Boolean flags, like:

```nix
# home.nix
{headless, laptop, ...}:   # Flags
{pkgs, lib, ...}:
# settings go here
```

and then I write separate files per host that import this with the right arguments, like:

```nix
# home-HOST-A.nix
import ./home.nix {headless=true; laptop=false;}
```

and

```nix
# home-HOST-B.nix
import ./home.nix {headless=false; laptop=false;}
```

etc. and then symlink the correct `home-HOST` file as `~/.nixpkgs/home.nix`. This works okay, but I'm just uncomfortable with the tiny proliferating host files.

Sorry for opening this question as an issue, but I thought home-manager users might have ideas here that I haven't found on the larger Nix boards yet. Thanks.

**Comment by dermetfan** [comment]
In my `home.nix` I import a `profile.nix` containing just a string which I use as attribute name to select a "profile" from an attribute set of profiles containing various settings. This profile's contents are then passed to home-manager config options. Maybe that helps to inspire you:

https://bitbucket.org/dermetfan/dotfiles/src/227f339abf65e1604a32c02fe8df749373f0401b/.nixpkgs/?at=default

**Comment by rycee** [comment]
Awesome! Thanks for the feedback.

I use something like a hierarchical setup. The first level is in `common.nix` and it has very basic stuff that should be available for all logins. On my servers I use this directly to set up a simple home environment: `home-manager -f .nixpkgs/common.nix switch`

The `common.nix` file also includes a bunch of disabled configurations (using `enable = lib.mkDefault false;`) that I can enable in login-specific files. For example
```
  programs.eclipse = {
    enable = lib.mkDefault false;
    jvmArgs = [ "-Xmx1024m" ];
    plugins = with pkgs.eclipses.plugins; [
      acejump
      …
      yedit
    ];
  };
```
and I then I can use this in the next level:
```
{ pkgs, ... }:

{
  imports = [ ./common.nix ];
  programs.eclipse.enable = true;
}
```

The `imports` field is quite useful, I have some other files I use inside `imports` such as `extra-packages.nix` which just contains a `home.packages` with a bunch of packages I want available for both my home and work environments.

**Comment by league** [comment]
Interesting ideas, thanks.

**Comment by Mic92** [comment]
I adopted a similar approach.
Since I deploy my basic dotfiles indepent from home-manager.
I use my zshrc to set the home-manager profile based on the `$HOST` variable.
The same function also bootstraps home-manager if it is not yet installed:


https://github.com/Mic92/dotfiles/blob/master/home/.zshrc#L133

**Comment by bsima** [comment]
Linking https://github.com/rycee/home-manager/issues/394

**Comment by Mic92** [comment]
Indeed the function could be extended to also take `uname -o` into account to apply configuration based on the operating system.

**Comment by Mic92** [comment]
Could someone add this to the FAQ? https://github.com/rycee/home-manager/wiki :)
