### ISSUE TITLE
warnings not printed when used nixos module

### ISSUE THREAD

**Issue by Gerschtli** [rycee/home-manager#804]
`warnings` in defined in modules like https://nixos.org/nixos/manual/index.html#sec-assertions-warnings are not shown to users when used as nixos module.

I can't test if it works correctly if used with the `home-manager` binary..

**Comment by rycee** [comment]
Should be sorted now. Thanks for the report!

**Comment by Gerschtli** [comment]
Awesome, works like a charm!
