### ISSUE TITLE
Dependency on nmd prevents to switch while offline

### ISSUE THREAD

**Issue by ejpcmac** [rycee/home-manager#819]
## Steps to reproduce

1. Run `home-manager switch`
2. Run `nix-collect-garbage`
3. Run `home-manager switch`

## Actual behaviour

The second `home-manager switch` fetches https://gitlab.com/api/v4/projects/rycee%2Fnmd/repository/archive.tar.gz?sha=b57fc6657b6645086a286e62a05a1795f258daa6, which prevents to switch while offline.

## Expected behaviour

Consequent builds with a garbage collection between them and without new packages to install should not fail without the network.

**Comment by rycee** [comment]
Fair point! I think this should be sorted now.

**Comment by ejpcmac** [comment]
Just tested: seems to be good :) Thank you!
