### ISSUE TITLE
Example of systemd.user.services is wrong

### ISSUE THREAD

**Issue by lucas8** [rycee/home-manager#823]
The example display one possible service unit, while `systemd.user.services` expect a set of units. The actual example is :

```nix
{
  Unit = {
    Description = "Example description";
    Documentation = [ "man:example(1)" "man:example(5)" ];
  };

  Service = {
    …
  };
}
```

while it should be : 
```nix
{
  service = {
    Unit = {
      Description = "Example description";
      Documentation = [ "man:example(1)" "man:example(5)" ];
    };

    Service = {
      …
    };
  };
}
```

To fix it a quick edit of `unitExample` in `modules/systemd.nix` should be enough.

**Comment by rycee** [comment]
Thanks for the report! The examples should be fixed now.
