### ISSUE TITLE
Enabling postgresql on macOS

### ISSUE THREAD

**Issue by rpearce** [rycee/home-manager#826]
Hi! I don't know if this question belongs in `home-manager`, but it's worth a shot. _Disclaimer: still relatively noob at nix._

I've successfully installed `postgresql_11` via this project, but I am not sure how to enable the postgresql service. Am I just doing this wrong? Here's what I'm working with:

<details>
<summary><code>home.nix</code></summary>

```nix
{ pkgs, ... }:

let
  nixpkgsConfig = import ./nixpkgs/config.nix;
  user = import ./user.nix;
  xdg = import ./xdg.nix;

in {
  nixpkgs = {
    config = nixpkgsConfig;
  };

  xdg = xdg;

  home.packages = with pkgs; [
    postgresql_11
    # ...other packages
  ];

  programs.home-manager = (import ./programs/home-manager.nix { });
  # ...other programs

  home.file.".psqlrc".source = ../conf/.psqlrc;
  # ...other dotfiles
}
```

</details>

<details>
<summary><code>nixpkgs/config.nix</code></summary>

```nix
{
  allowBroken = true;
  allowUnfree = true;

  packageOverrides = pkgs: rec {
    # ...package overrides
  };

  services.postgresql = pkgs: rec {
    enable = true;
    package = pkgs.postgresql_11;
    port = 5432;
  };
}
```

</details>

I have all of the CLI tools, but it doesn't seem like it's getting enabled, and I can't find any of the relevant files/services that should be created as per https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/databases/postgresql.nix.

```
λ psql
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

* * *

Any help or guidance would be super helpful!

**Comment by rycee** [comment]
The modules in Home Manager are separate from the ones in NixOS and unfortunately they are incompatible with each other. Second, NixOS modules are only for NixOS, i.e., would not work under macOS. All services in HM and NixOS are run through systemd so they will not work under macOS.

Fortunately, the [nix-darwin](https://github.com/LnL7/nix-darwin) project seems to have a [postgresql](https://lnl7.github.io/nix-darwin/manual/index.html#opt-services.postgresql.enable) module that you could try.

**Comment by rpearce** [comment]
Okay, thanks for looking at it and explaining!
