### ISSUE TITLE
Bashisms in .xsession

### ISSUE THREAD

**Issue by lukasstevens** [rycee/home-manager#836]
Hi, I am using home-manager on Debian and want it to manage by xsession. On Debian, `/bin/sh` is used to execute `/etc/X11/Xsession`, which sources `.xsession` to start the session. The problem is that the `.xsession` file generated by home-manager uses the bashishm `[[ ... ]]`. Is there a way to circumvent this or does home-manager need to be changed?

P.S: I already tried to change the shebang of `/etc/X11/Xsession` to `/bin/bash` but to no avail.

**Comment by rycee** [comment]
Good point. These scripts were made with NixOS in mind, which does use Bash to execute them. Could you give the changes in #840 a try to see if it improves things?

**Comment by lukasstevens** [comment]
Thank you, now it works!

**Comment by rycee** [comment]
Nice, I've merged the PR to master.
