### ISSUE TITLE
Support nix-on-droid

### ISSUE THREAD

**Issue by Gerschtli** [rycee/home-manager#848]
Hello,

I currently diving deep into `home-manager` and [`nix-on-droid`](https://github.com/t184256/nix-on-droid-bootstrap). To improve the workflow and maintainability I suggested in issue https://github.com/t184256/nix-on-droid-bootstrap/issues/10 to create a separate `home-manager` module for managing some static files and symlinks all over the place.

Just a brief overview of the file structure (`$PREFIX/usr` is available under `/` via `proot`):
* `$PREFIX/home` is the home directory of the user (managed via `home-manager` without issues)
* `$PREFIX/usr/bin` contains some `nix-on-droid` specific scripts and a link to bash (`/bin/sh`)
* `$PREFIX/usr/etc` contains some config files
* `$PREFIX/usr/usr/bin/env` is a symlink to `env` of `coreutils`

I would like to augment the functionality of the `files` module to be able to manage the files in `$PREFIX/usr` via `home-manager`. What do you think? Is this a way to go or do you have other ideas?

I'm not sure if I should set the new extended API of the `files` module to public as this could easily misused. On the other hand this could come in handy for more configurations needed for `nix-on-droid`..

**Comment by t184256** [comment]
> $PREFIX/usr is available under / via proot

For correctness sake, this is not entirely true. `/nix`, `/bin`, `/etc`, `/tmp` and `/usr` are proot-pseudo-mounted from `/data/data/com.termux.nix/files/usr`, but the rest of `/` comes as-is from the outer Android, notably `/sdcard`.

**Comment by rycee** [comment]
Well, currently HM is semi-artificially limited to managing files in `$HOME`. I believe it could relatively easily be made to manage files anywhere using `home.file."/absolute/path/to/file".(source|text)` assuming the HM user is having write permission for the target paths.
