### ISSUE TITLE
Confusing error message including --show-trace

### ISSUE THREAD

**Issue by turion** [rycee/home-manager#850]
If I have an incorrect `home.nix` file, I'll get an error message like this:

```
$ home-manager switch
error: The option value `programs.vim.plugins.[definition 1-entry 1]' in `/home/turion/enigmanix/home.nix' is not of type `string'.
(use '--show-trace' to show detailed location information)
```

I want to focus on the last line here. If I use `--show-trace`, it doesn't have any effect:

```
$ home-manager switch --show-trace
error: The option value `programs.vim.plugins.[definition 1-entry 1]' in `/home/turion/enigmanix/home.nix' is not of type `string'.
(use '--show-trace' to show detailed location information)
```

Also, `man home-manager` doesn't give me any hint on how to activate this option.

**Comment by rycee** [comment]
Are you using the 19.03 branch of HM? The master one should handle this situation better.

On 19.03 you can use `-v` to enable `--show-trace`.

**Comment by turion** [comment]
Yes, that was the issue. Thanks!
