### ISSUE TITLE
notmuch config location

### ISSUE THREAD

**Issue by alexarice** [rycee/home-manager#851]
the notmuch module writes its config to ~/.config/notmuch/notmuchrc but notmuch looks for it's config in ~/.notmuch-config 

Not sure if this has been changed by a recent version or if I'm missing something

**Comment by teto** [comment]
the module does export NOTMUCH_CONFIG in sessionVariables so you might have to login again for it to work. I plead guilty. I try to make everything follow xdg and upstreaming this might not have been my best idea :s

**Comment by alexarice** [comment]
might be overriden because I'm using fish

**Comment by alexarice** [comment]
ah no, it was just a login that was needed, I hadn't realised because I had symlinked the file

**Comment by alexarice** [comment]
My emacs however can't find it, maybe having a symlink would be a better idea?

**Comment by bsima** [comment]
Alex Rice <notifications@github.com> writes:

> My emacs however can't find it, maybe having a symlink would be a better idea?

I just made my own symlink: https://git.sr.ht/~ben/cfg/tree/master/install.sh#L16-23
