### ISSUE TITLE
Newsboat URLs should support title

### ISSUE THREAD

**Issue by lovesegfault** [rycee/home-manager#861]
Newsboat allows you to set a custom title to a URL entry, it looks like this:
```
# URL                             LABEL   TAG
https://lwn.net/headlines/newrss  "~LWN"  news
```
It should be supported in the config.

**Comment by rycee** [comment]
I gave it a try in #863. Please have a look and see if it'll work (I don't use newsboat myself).

**Comment by lovesegfault** [comment]
Thanks @rycee!
