### ISSUE TITLE
xsession with displayManager failure in 19.09

### ISSUE THREAD

**Issue by PierreR** [rycee/home-manager#862]
When I tried to use 19.09 (still in beta), I have got the following error:

```
Failed assertions:
- LightDM auto-login requires that services.xserver.desktopManager.default and
services.xserver.windowManager.default are set to valid values. The current
default session: none is not valid.
```
I am defining `.xserver.windowManager` inside `home.nix`.

How is this supposed to work ? I have tried to set `xsession.displayManager` in home.nix but this is failing too. Do I need to copy some of my xsession home-manager setting into configuration.nix ?

I am using the master channel of the home-manager.

Thanks.

**Comment by PierreR** [comment]
I guess this issue is more related to a change in 19.09 than anything. I could not find where the documentation for 19.09 so it is a bit difficult to look at it further.

Setting a windowManager in configuration.nix seems to make some sense (though providing a sane default would be better).

Following that lead I have tried to add  `services.xserver.windowManager.default = "xmonad"`  in configuration.nix.  Well no luck,  it gives me an error saying `xmonad` is not a valid windowManager ...

I then went with  `services.xserver.windowManager.default= "xterm";` and got the following warning:
```
trace: Default desktop manager (xterm) not found at evaluation time.
These are the known valid session names:
  services.xserver.desktopManager.default = "none";
```

I will just keep this open for now in case someone has an idea. Will have another try whenever 19.09 and its documentation is available.

Feel free to close this issue as it might be irrelevant for home-manager.

**Comment by PierreR** [comment]
I will close this because it is probably related to a change that has been recently reverted. I will re-open it if necessary.

**Comment by wedens** [comment]
my workaround:
```nix
    windowManager.default = "dummy";
    windowManager.session = [{
      name = "dummy";
      start = "${pkgs.coreutils}/bin/true";
    }];
```

**Comment by PierreR** [comment]
I am pretty sure this is related to this https://github.com/NixOS/nixpkgs/pull/70185

The revert will probably fix it and hopefully a better solution will come up for 20.03.

**Comment by rycee** [comment]
The https://github.com/NixOS/nixpkgs/pull/68371 PR seems like a good option. With that you'd choose the "xsession" desktop for HM and still be able to choose other desktop managers if you like.

It's already possible by configuring HM to use a different file name than `.xsession` and then manually adding a desktop manager in the NixOS configuration but it would be nice if it worked out of the box.

**Comment by IvanMalison** [comment]
> The [NixOS/nixpkgs#68371](https://github.com/NixOS/nixpkgs/pull/68371) PR seems like a good option. With that you'd choose the "xsession" desktop for HM and still be able to choose other desktop managers if you like.

@rycee I know that this is probably not super relevant to this issue, but I am wondering how to do exactly this with home-manager.

Basically I would still like to be able to select the desktopManager/desktopEnvironment from my displayManager, but I'd also like to be able to use home-manager's xsesssion/graphical session. Is this possible?
