### ISSUE TITLE
kakoune: first line of extraConfig gets merged with last defined hook

### ISSUE THREAD

**Issue by tripokey** [rycee/home-manager#869]
Scenario:
A kakoune configuration is defined with both extraConfig and hooks set.

Outcome:
The first line of the extraConfig gets merged with the last hook.

Expected:
A new line to be inserted between the hook and the extraConfig.

Workaround:
Start the extraConfig with a blank line.

**Comment by rycee** [comment]
Thanks for the report. I made a PR that hopefully fixes the issue, please have a look.
