### ISSUE TITLE
Redshift service broken after nix-env --uninstall

### ISSUE THREAD

**Issue by codygman** [rycee/home-manager#874]
I was having problems with the redshift service not updating its parameters. I uninstalled it with `nix-env --uninstall redshift`. I then set `service.redshift.enable = false`, `home-manager switch`, set it back to true, and switched again.

I got back the error:

```
Failed to start redshift.service: Unit redshift.service not found.
```

It looks like home-manager doesn't know about the uninstall so it doesn't reinstall? How can I fix this?

**Comment by codygman** [comment]
It looks like the answer can be found [here](https://logs.nix.samueldr.com/home-manager/2019-08-26) and that systemd is "degraded"?

I'm not quite sure what that means, but my output is:

```
~/.config/nixpkgs $ systemctl --user --failed
  UNIT             LOAD      ACTIVE SUB    DESCRIPTION                              
● redshift.service not-found failed failed redshift.service                         

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

1 loaded units listed
```

Maybe that means a reboot will fix it because nix will start without trying to start redshift? Idk.

**Comment by spinus** [comment]
Is it still an issue?

**Comment by codygman** [comment]
I haven't had this issue happen again, but I had some failed state errors from systemd which require manual intervention. It's possible home-manager could give better errors on what to do for those, but I'll close this for now.
