### ISSUE TITLE
Conditional home.file's?

### ISSUE THREAD

**Issue by cmacrae** [rycee/home-manager#877]
Hey @rycee :wave: Thanks very much for home-manager, it's great! :tada: 

I've been leveraging it across all my desktop systems for quite some time.  
One collection of configs I deploy go to darwin systems. I'm trying to do a conditional `home.file` declaration like so:
```nix
    home.file."Library/SomeDir/SomeFile.txt".text = lib.mkIf isDarwin ''
      some stuff here
    '';
```

This works fine on darwin systems, but when evaluated on NixOS I get the following:
```
error: The option `home-manager.users.cmacrae.home.file.Library/SomeDir/SomeFile.txt.source' is used but not defined.
```

Is there a nice way to do this?
Thanks in advance for any help :pray:

**Comment by cmacrae** [comment]
Sorry, fumbled about with my keyboard and opened the issue sooner than intended :roll_eyes:

**Comment by shanesveller** [comment]
You can get pretty far with `mkMerge` and `mkIf` used together - here's an example from the existing codebase where some content is conditional while others are applied universally:

https://github.com/rycee/home-manager/blob/54de0e1d79a1370e57a8f23bef89f99f9b92ab67/modules/misc/xdg.nix#L75-L103

**Comment by rycee** [comment]
@cmacrae Instead of
```
    home.file."Library/SomeDir/SomeFile.txt".text = lib.mkIf isDarwin ''
      some stuff here
    '';
```
try
```
    home.file."Library/SomeDir/SomeFile.txt" = lib.mkIf isDarwin {
      text = ''
        some stuff here
      '';
    };
```
I think that should work. Unfortunately `mkIf` is a bit sensitive about where it's placed 😕

**Comment by cmacrae** [comment]
Argh! Sorry guys, not sure how I missed the notifications on this. I just now solved it using `mkMerge` and `mkIf`: https://github.com/cmacrae/nix/commit/db126efc047b06245e738c86cde6436ff2666a89  

Which of course reminded me that I opened this issue! So, figured I'd come close it.  
Thanks for your suggestions!
