### ISSUE TITLE
Compton configuration should be updated

### ISSUE THREAD

**Issue by wedens** [rycee/home-manager#878]
At some point compton removed, changed and deprecated some options. For instance, `vsync` is now boolean value, doc/dnd/etc opacity setting were moved to `wintypes`, and other changes.

compton module in nixpkgs seems to be already up to date with those changes.

**Comment by PierreR** [comment]
FWIW compton is eating a lot of memory with the home-manager (nixos-19.09):

![2019-10-22_16-53-58-compton](https://user-images.githubusercontent.com/93115/67301222-69267580-f4ef-11e9-9f1f-eb9bd5e50922.png)

Could be related ?

**Comment by PierreR** [comment]
I can confirm this is an issue with the home-manager. If I enable compton on the system instead I have got:
![2019-10-22_17-24-39-compton](https://user-images.githubusercontent.com/93115/67302357-1352cd00-f4f1-11e9-82bc-9b40990e3d1e.png)

**Comment by wedens** [comment]
HM and NixOS have different default settings. the most important is backend. in HM it is `glx` by default, in NixOS it is `xrender`.

**Comment by PierreR** [comment]
@wedens Indeed the `xrender` backend seems to work better for me. I am within a virtualbox so maybe `glx` is not such a good idea ?

**Comment by wedens** [comment]
Yes. `glx` requires hardware acceleration. If you don't have that available in a VM, you're better of with non-accelerated `xrender`.

**Comment by PierreR** [comment]
Great. Thanks for your help !

**Comment by dtzWill** [comment]
FWIW compton (yshui's compton fork, what nixpkgs has been using for some
time) just went ahead with a rename!  Now it's "picom".

At least for now there are compat fallbacks to help migration
(installs a 'compton' symlink, reads compton.conf if no picom.conf...)
but that's not something to rely on long-term of course.

Just mentioning because if we're sitting down and rewriting this
(possibly breaking/fixing/changing people's configs as a result)
it might be good to rename at the same time?

Just a thought :).

**Comment by dtzWill** [comment]
On Thu, 24 Oct 2019 12:08:29 -0500, Will Dietz <w@wdtz.org> wrote:
> FWIW compton (yshui's compton fork, what nixpkgs has been using for some
> time) just went ahead with a rename!  Now it's "picom".
> 
> At least for now there are compat fallbacks to help migration
> (installs a 'compton' symlink, reads compton.conf if no picom.conf...)
> but that's not something to rely on long-term of course.
> 
> Just mentioning because if we're sitting down and rewriting this
> (possibly breaking/fixing/changing people's configs as a result)
> it might be good to rename at the same time?
> 
> Just a thought :).

First release with new name has been tagged!

https://github.com/yshui/picom/releases/tag/v7.5

\o/


>

**Comment by sondr3** [comment]
Any news/ideas on how to transition this? The `compton` package is getting old and picom is moving ahead at a great pace. Should we transition the existing `compton` configuration to `picom` or create a new service for `picom` and mark `compton` as deprecated/outdated?

**Comment by sondr3** [comment]
I just noticed when I enabled the `compton` service that it is using the `picom` package. The `compton` binary has been made to an alias of `picom` in [`nixpkgs`](https://github.com/NixOS/nixpkgs/blob/8de09faad16428b16ed2dff64cbfa6db82d31857/pkgs/top-level/aliases.nix#L74). This might be something to make a note of for `home-manager` as starting the service now gives a bunch of deprecation warnings due to the default configuration:

```text
Feb 15 16:58:31 neptune compton[8246]: [ 02/15/2020 16:58:31.005 parse_config_libconfig WARN ] Option `menu-opacity` is deprecated, and will be removed.Please use the wintype option `opacity` of `popup_menu` and `dropdown_menu` instead.
Feb 15 16:58:31 neptune compton[8246]: [ 02/15/2020 16:58:31.005 parse_config_libconfig WARN ] vsync option will take a boolean from now on. "none" is interpreted as "false" for compatibility, but this will stop working soon
Feb 15 16:58:31 neptune compton[8246]: [ 02/15/2020 16:58:31.005 session_init WARN ] This compositor has been renamed to "picom", the "compton" binary will not be installed in the future.
```

@rycee

**Comment by rycee** [comment]
I'll defer to @uvNikita since I've never used compton and have no particular opinion about the module 🙂

Alternatively, if somebody produces a PR to deprecate/rename/etc. options as necessary I can have a look at it.

**Comment by uvNikita** [comment]
Since compton is now an alias in nixpkgs, I guess we should do the same here: rename compton service to picom and create alias. After this, we can deprecate/add new options to the service.

**Comment by rycee** [comment]
I think that plan sounds good. It would be good to have available for the 20.03 release.

**Comment by uvNikita** [comment]
@rycee I'm not using compton/picom at the moment, but can try to find time to do some trivial fixes. Do we have some way of declaring that module has been renamed so that people can be notified that they should change `services.compton` to `services.picom` in configuration file?

**Comment by sondr3** [comment]
I think I'd also prefer to do something like how the VSCode configuration, write nix and convert it to the format used by Picom/Compton and don't enable any default things, right now I can't use the correct type for the `vsync` option. If you want to I can give it a go this weekend @uvNikita?

**Comment by uvNikita** [comment]
@sondr3 of course, sounds good, thanks! 👍

**Comment by deifactor** [comment]
Another thing that needs to happen is that there should be some way of passing `--experimental-backends` via the systemd service, since this option can't be passed via config file.
