### ISSUE TITLE
Declarative management of nssdb

### ISSUE THREAD

**Issue by cprussin** [rycee/home-manager#883]
Hi!

I have some custom root certificates that I install in nixos using `security.pki.certificates`.  However, this only updates `/etc/ssl/certs/ca-certificates.crt`, which does not apply to chromium/firefox/etc which use nssdb instead.  As far as I know, the only way to get those root certs into those browsers is to update `~/.pki/nssdb` using `certutil` or similar.  I'd love for this to be managed declaratively using my `home-manager` config.

Any thoughts about adding some mechanism for this?

**Comment by rycee** [comment]
I'm not sure how to do it in a general way but you could always create your own activation blocks that perform the right certutil commands. Something like
```
home.activation.installNssDbCerts = dag.entryAfter ["writeBoundary"] ''
  ${pkgs.nss.tools}/bin/certutils …
'';
```

**Comment by cprussin** [comment]
Nice, that should do it, thanks!

**Comment by cprussin** [comment]
@rycee actually one question, I can't seem to find any way to do the inverse of an activation script. That is, something I can use to clean up my mutations when activating a new config that no longer has a particular config (a cert in this case). Am I missing something or does this not exist?

**Comment by AshleyYakeley** [comment]
Reopen this? I think it would be useful to have a proper HM option for doing this.
