### ISSUE TITLE
Collisions when configuring Neovim

### ISSUE THREAD

**Issue by earksiinni** [rycee/home-manager#884]
I have a `home.nix` that looks something like this:

```
{
  home.packages = [
    pkgs.neovim
  ];

  programs.home-manager.enable = true;

  programs.neovim = {
    enable = true;
    # withNodeJs = true;
    # plugins = [
    #   pkgs.vimPlugins.vim-startify
    # ];
  };
}
```

When I uncomment `withNodeJs` or `plugins` and run `home-manager switch`, I get the following error:

```
[user@nixos:~]$ home-manager switch
these derivations will be built:
  /nix/store/2f62g1wkb5ll95c7s0hjrqaplpbyy4md-neovim-0.3.8.drv
  /nix/store/3pw2ir8cbrv7bkr7wxhsgjpwyp73nvz2-home-manager-path.drv
  /nix/store/7v7six32qnz6ly5c4588c1qm1k7q8gxs-activation-script.drv
  /nix/store/jhc6m8zr3zkadia1ghg9v5mhlgww5b4x-home-manager-generation.drv
building '/nix/store/2f62g1wkb5ll95c7s0hjrqaplpbyy4md-neovim-0.3.8.drv'...
Generating remote plugin manifest
building '/nix/store/3pw2ir8cbrv7bkr7wxhsgjpwyp73nvz2-home-manager-path.drv'...
collision between `/nix/store/mi7gidvsby5m18w1ibkbla4yajshria1-neovim-0.3.8/share/applications/nvim.desktop' and `/nix/store/330rhb2v9yqk7qs32cl39ii1bmzgcpq5-neovim-0.3.8/share/applications/nvim.desktop'
builder for '/nix/store/3pw2ir8cbrv7bkr7wxhsgjpwyp73nvz2-home-manager-path.drv' failed with exit code 255
cannot build derivation '/nix/store/jhc6m8zr3zkadia1ghg9v5mhlgww5b4x-home-manager-generation.drv': 1 dependencies couldn't be built
error: build of '/nix/store/jhc6m8zr3zkadia1ghg9v5mhlgww5b4x-home-manager-generation.drv' failed
```

When I leave those lines commented, `home-manager switch` works fine.

Any ideas?

**Comment by teto** [comment]
remove neovim from home.packages, the module will install its own configured version

**Comment by earksiinni** [comment]
@teto thank you, that worked.

What exactly is the purpose then of `home.packages`? Is it for packages with no configuration in `home.nix`? The manual simply says that it's `The set of packages to appear in the user environment.`

**Comment by teto** [comment]
you can use `man home-configuration.nix` to (hopefully) understand what an option does.
The neovim module adds its own version in home.packages which can be surprising as you noticed. We could increase the priority of the package added by the module but it could be surprising in another way (plus you would end up with 2 neovim in the closure).

**Comment by earksiinni** [comment]
@teto, thank you for clarifying.

As for using `man home-configuration.nix`, I was quoting from the manual in my comment above 😄. I think that the current behavior makes sense when it's explained, but the manual and/or the README.md could use some clarification, especially for new users like myself. I will create a separate PR to update the docs.

As a general rule, do all of the modules corresponding to packages add their own versions of that package? For example, I'm also configuring Git with `programs.git`, and it appears that it installed its own version without me adding `pkgs.git` to `home.packages`.
