### ISSUE TITLE
programs.zsh.history.path allows invalid paths

### ISSUE THREAD

**Issue by lovesegfault** [rycee/home-manager#886]
If you set it to a non-existent dir, home-manager will not create the directory, nor fail, causing zsh to silently fail later on when it tries to read/store history.

**Comment by rycee** [comment]
@uvNikita Not sure if this is worth trying to fix. But perhaps putting a `mkdir -p "$HOME/${dirOf cfg.history.path}"` in `.zprofile` or something (i.e., a file run once per login)?

**Comment by lovesegfault** [comment]
Can't it be done on `home-manager switch`?

**Comment by rycee** [comment]
Yeah, it would be possible to add, e.g., `home.file."${dirOf cfg.history.path}/.keep".text = "";` or something similar. Not sure which would be most elegant.

**Comment by uvNikita** [comment]
Create a PR based on the second suggestion, let me know what you think :)

**Comment by lovesegfault** [comment]
You guys rock!
