### ISSUE TITLE
Dunst not installed

### ISSUE THREAD

**Issue by lhindir** [rycee/home-manager#898]
Hello,

I'm using home-manager as a NixOS module. Things are working great for the most part, but `services.dunst.enable = true;` doesn't seem to work. I also have the `compton`, `unclutter`, and `polybar` services working fine, so it's not something with `xsession`. Typing `dunst` at a terminal returns the usual Nix message about the program not being installed.

I took a look at `dunst.nix` and I couldn't seem to find a line that properly installed `dunst`. The closest I found was the `systemd` service which references the package, but nothing seems to actually install it. Is this a problem, or am I misunderstanding how things work here?

Thanks!

**Comment by gmarmstrong** [comment]
Since dunst is being used as a service, it's not added to the PATH, because it should operate correctly by just enabling it, and optionally configuring it through home.nix.

**Comment by lhindir** [comment]
Oh, so applications can only access it through the Freedesktop interface? That makes sense. I'll have to add it to home.packages for some scripts then. Thanks for the info.
