### ISSUE TITLE
Allow for bash & zsh specific .programs.zsh.

### ISSUE THREAD

**Issue by teto** [rycee/home-manager#90]
Recently I seem to have trouble with the value of HISTFILE being the same for zsh/bash while the format of zsh history seems to have changed (not sure if it's because of my configuration or a zsh update, now it seems to prepend a timestamp):
`: 1507686477:0;git fetch -a channels && git rebase channels/nixpkgs-unstable`
but even without that I prefer to have bash and zsh use different HISTFILE(s).

WOuld you be ok with a "variables" options specific to zsh or bash that write into .zshenv for instance. I can contribute.

**Comment by uvNikita** [comment]
I think it would be nice to have something like `programs.zsh.sessionVariables`, `programs.bash.sessionVariables` to put there variables specific to this shells and to use `home.sessionVariables` for more general stuff. My understanding is that if for example `home.sesssionVariablesSetter == "zsh"`, then everything from `home.sessionVariables` will be merged into `programs.zsh.sessionVariables` and added to `.zshenv` file.

@rycee do you agree with that?

**Comment by rycee** [comment]
@uvNikita Yes, I think that is a good solution. I'm happy to add such an option for the bash module, I'll leave the zsh one for you :-)

**Comment by rycee** [comment]
That said. I don't see why the Zsh and Bash history files end up being the same. The bash module doesn't set HISTFILE so it should end up being the default `~/.bash_history`. The zsh module seem to set HISTFILE to `$dotDir/.zsh_history`. So they should by definition keep separate histories… @teto Did you set HISTFILE yourself anywhere?

**Comment by rycee** [comment]
I also added the `sessionVariables` option in Bash so now it should be straightforward to set them independently. I still don't understand how Bash and Zsh ended up writing history to the same file in the first place, though.

@teto Please close this issue if you feel it has been resolved, if not please add a comment. I'll close the issue in a few days if nothing further is added to it.

**Comment by teto** [comment]
Thanks for the job  uvNikita !
Sorry I was unclear the problem with HISTFILE didn't lie with home-manager in the first place, I had it as a sessionVariables in my configuration.nix and this was part of the reason of why I wanted to move some aliases to home-manager (it would also create problems when logged as root).

I have a bonus question/suggestion. I have ZDOTDIR set in my configuration.nix. Is there any way home-manager could pick it up ? I don't think it could run zsh and echo $ZDOTDIR as that might bring impurity but maybe it could pick it up from environment.sessionVariables ?

**Comment by uvNikita** [comment]
There is `programs.zsh.dotDir` configuration option in home-manager which might be suitable for your case:
https://github.com/rycee/home-manager/blob/12ebf21be523eaf6db1f19b5a6b9304e99540961/modules/programs/zsh.nix#L136

It sets ZDOTDIR variable for you and places all relevant to zsh configurations inside the specified directory. I don't think it is possible to reference values from the system configuration in home-manager at this point, but @rycee know better about this.

**Comment by teto** [comment]
I know that one but it should be possible to bypass it. Also if one sets $XDG_CONFIG_HOME, there must be way for home-manager to get it otherwise it will generate files in unused locations. This is a problem I hit when I tried creating a notmuch module.

**Comment by rycee** [comment]
To access your system configuration you can use `(import <nixpkgs/nixos> {}).config`. For example,
```
home.file."nixoscodename".text = (import <nixpkgs/nixos> {}).config.system.nixosCodeName;
```
Also, right now Home Manager mostly assumes that your XDG variables are set to their default. E.g., that `XDG_CONFIG_HOME` is set to `~/.config`.

**Comment by teto** [comment]
I close this since the problem at hand is more generic.  Thanks for the interesting snippet.
