### ISSUE TITLE
Multiple xsessions?

### ISSUE THREAD

**Issue by MrInkling** [rycee/home-manager#902]
Is there a way to have more than one window manager managed by home-manager? The closest thing I could find is #391, which still doesn't let me have multiple sessions in home-manager configuration.
I realize that it's not a common usecase, and if I correctly understand how it all works now, it seems complex and pointless to implement as a part of home-manager, so I'm just asking if there's a relatively sane hack that would allow me to do this in my particular config.

**Comment by rycee** [comment]
Sorry about the delay. Unfortunately, no there is no easy way to do this and I think it is unlikely to be made simpler in the foreseeable future.

The closest I can think of is to simply have multiple window managers configured in your `home.nix` but only having one of their `enable` option set to `true` at any time. When you want to switch window managers you'd have to do `home-manager switch` and logging back in. Not very convenient, but depending on your use case it might be workable…

**Comment by MrInkling** [comment]
Thanks for the reply and all the work you're doing on home-manager. Don't mind the delay, you aren't getting paid answer newbie questions on github, after all :)
