### ISSUE TITLE
memory leak when using home-manager tool

### ISSUE THREAD

**Issue by nek0** [rycee/home-manager#907]
Hi there,

After installing the home-manager tool like described in the readme (which works fine) I encounter strange memory leaks when using either `home-manager switch` or `home-manager build`, where the CPU does nearly nothing, but the memory consumption goes up and given time my system will run out of memory (which is 32GB at the moment). The only output I get is

```
warning: dumping very large path (> 256 MiB); this may run out of memory
```

I am running a freshly installed NixOS 19.09 system.

The only workaround I found out is running

```
nix-shell '<home-manager>' -A install
```

every time I update my home.nix.

Thanks for your time.

**Comment by rycee** [comment]
You most likely reference a very large file or directory inside your configuration. For example like
```
home.file.foo.source = ./path/to/very.large.file;
```
or
```
home.file.foo.text = "foo = ${./path/to/very.large.file}";
```
In these cases Nix will attempt to place the large file in the Nix store, which due to technical limitations doesn't work very well.

If you can share your configuration it might be possible to pinpoint the issue.

**Comment by nek0** [comment]
As far as I can tell my configuration is not out of the ordinary:

```
{ pkgs, ... }:

{
  home.packages = with pkgs; [
    gajim
    hexchat
    arandr
    networkmanagerapplet
    krita
    gmic_krita_qt
    ghc
    cabal-install
    cabal2nix
    cantata
    tdesktop
    git
  ];
  
  #programs.home-manager.enable = true;
  
  programs.firefox.enable = true;
  
  programs.gpg.enable = true;

  programs.mpv.enable = true;

  services.syncthing.enable = true;
  services.syncthing.tray = true;

  services.udiskie = {
    enable = true;
  };

  services.mpd = {
    enable = true;
    dataDir = ~/.mpd;
    dbFile = "~/.mpd/tag_cache";
    playlistDirectory = ~/.mpd/playlists;
    musicDirectory = ~/Musik;
    network = {
      listenAddress = "127.0.0.1";
      port = 6600;
    };
  };

  services.mpdris2 = {
    enable = true;
    multimediaKeys = true;
    notifications = true;
  };

  services.kdeconnect = {
    enable = true;
    indicator = true;
  };
}
```

**Comment by rycee** [comment]
You'll want to change
```
    dataDir = ~/.mpd;
    dbFile = "~/.mpd/tag_cache";
    playlistDirectory = ~/.mpd/playlists;
    musicDirectory = ~/Musik;
```
to
```
    dataDir = "~/.mpd";
    dbFile = "~/.mpd/tag_cache";
    playlistDirectory = "~/.mpd/playlists";
    musicDirectory = "~/Musik";
```
since the first one will copy the unquoted paths to the Nix store.

**Comment by nek0** [comment]
ok. after changing it to

```
    dataDir = "/home/nek0/.mpd";
    dbFile = "/home/nek0/.mpd/tag_cache";
    playlistDirectory = "/home/nek0/.mpd/playlists";
    musicDirectory = "/home/nek0/Musik"
```

all works well. Thanks again for your time.
