### ISSUE TITLE
User systemd service units aren't restarted after linking a generation when there were failing units

### ISSUE THREAD

**Issue by sgraf812** [rycee/home-manager#909]
This line

https://github.com/rycee/home-manager/blob/450571056552c9311fcb2894328696b535265593/modules/systemd.nix#L247

means that when there's a failed service unit, the user systemd services aren't restarted after linking a new generation. `$ systemctl --user is-system-running` will print `degraded` in that case and exit with code >0. In order to actually start the new service units, I have to `$ ssytemctl --user reset-failed` before I switch and afterwards restart the failed services manually. Is that intended? If so, it's not at all obvious to me.

**Comment by rycee** [comment]
If you have the opportunity, please give the #916 changes a try.

**Comment by Shados** [comment]
@rycee please re-open -- #916 changes only fixed #355 and #798, not this. Units that failed prior to the current home-manager activation still won't be (re)started by it (only their unit files will be reloaded), and still need to be manually started (either individually, or by something like `systemctl --user start default.target`).
