### ISSUE TITLE
Conflicts in xdg.configFIle should error

### ISSUE THREAD

**Issue by lovesegfault** [rycee/home-manager#914]
Currently you can do something like this:

```
xdg.configFile.foo  = {
   target = "foo.conf"; 
   text = "foo";
   source = "../foo.txt"
};
```

IME this will cause `source` to end up as the file, but I believe this should be a hard error.

**Comment by rycee** [comment]
This is unlikely to be possible without either complicating the code significantly or sacrificing the possibility to specify either the `text` or `source` attribute. Unless you have a specific implementation in mind I would suggest closing this issue as a wontfix.

Feel free to reopen if you have strong opinions about this.
