### ISSUE TITLE
Configuration paths for plasma

### ISSUE THREAD

**Issue by seqizz** [rycee/home-manager#928]
Hi,

Sorry for the mixed-up issue, didn't know where to ask in the first place :confused: 

I've recently packaged a kwin script that I've been using for a while: https://github.com/NixOS/nixpkgs/pull/74262

Problem is: There is a [known issue](https://github.com/kwin-scripts/kwin-tiling/issues/79#issuecomment-311465357) about enabling configurations of kwin scripts, apparently plasma searches them in some specific directories.

I've installed this new package via home-manager and even though I can see the required file under `~/.nix-profile/share/kservices5` folder, the plugin still can't be configured.

My question is: How can I provide paths for `/usr/share/kservices5` in the sense of conventional FS hierarchy via HM?

**Comment by rycee** [comment]
Hmm, `/usr/share/kservices5` is quite impossible for HM to do but perhaps
```
xdg.dataFile.kservices5.source = "${config.home.path}/share/kservices5";
```
would work?

**Comment by seqizz** [comment]
Yup, definitely worked, thanks as always :)
This should be in some documentation :+1:
