### ISSUE TITLE
feature-request: vs-code server

### ISSUE THREAD

**Issue by tbenst** [rycee/home-manager#939]
VScode integration is awesome and super useful. I'd love to be able to configure extensions when in remote ssh server mode, too. Right now [this workaround is good](https://github.com/microsoft/vscode-remote-release/issues/648#issuecomment-503148523) for getting it working in general,  using `nodejs-12_x` instead due to updates, but still have to manually install each extension & then restart. Not very hard, but would be super slick to customize the remote, too! Let me know if I should put this in `nixpkgs` instead, although figured it had to live in userspace.

**Comment by Mic92** [comment]
I think home-manager would be a perfect place for that since this module needs to fix files in $HOME. (Not a vscode user, but a colleague would need it).

**Comment by tbenst** [comment]
@xfix wanted to see if you had any thoughts? from https://github.com/shanalikhan/code-settings-sync/issues/1052#issuecomment-536456497, looks like its as simple as duplicating the `extension/*` symlinks that are currently done in `~/.vscode/` to  `~/.vscode-server` The server will have extra dirs like `.vscode-server/bin` and `.vscode-server/data` so we don't want to do `ln -s ~/.vscode ~/.vscode-server`.

Currently, I do `ln -s ~/.vscode/extensions ~/.vscode-server/` and this works perfectly so far.

**Comment by xfix** [comment]
@tbenst I don't use Visual Studio Code myself, so I won't be much of help here. I believe this functionality is proprietary and due to that unavailable in VSCodium I use.

**Comment by tbenst** [comment]
@xfix no worries, yes I believe you're correct.

Here's a one-liner that fixes the node issue. I'm not sure how to do this in nix / home-manager
```
for f (~/.vscode-server/bin/*/node); do echo $f; done
```

**Comment by Mic92** [comment]
There are activation scripts: https://github.com/rycee/home-manager/blob/a144c723a11cafbb01f01b5d581be453d2947aa8/nix-darwin/default.nix#L65

However the question is: how to make sure that `~/.vscode-server` exists before?

**Comment by tbenst** [comment]
maybe just:
```
if test -f "~/.vscode/extensions"; then
  if ! test -L "~/.vscode-server/extensions"; then
    ln -s ~/.vscode/extensions ~/.vscode-server/
  fi
fi

if test -f "~/vscode-server/bin"; then
  for f (~/.vscode-server/bin/*/node); do
    if ! test -L $f; then
      rm $f
      ln -s ${nodejs-12_x}/bin/node $f
    fi
  done
fi
```

The first time, this requires a user to
1. (on host) home-manager switch 
2. (from client) connect to host with remote-ssh
3. (on host) home-manager switch

This is perhaps unavoidable as I'm not sure how VSCode comes up with the file path for `/home/tyler/.vscode-server/bin/8795a9889db74563ddd43eb0a897a2384129a619/`, and it seems to make a new path for each VSCode update. So not ideal in terms of declarative config, but better than broken!

**Comment by Mic92** [comment]
Maybe this could become part of the shell rc rather than at home-manager switch time.

**Comment by tbenst** [comment]
Seems unecessary to run that frequently, maybe should be added as wrapper to vscode? Or even better, we should patch the script used by https://github.com/microsoft/vscode-remote-release on initialization

**Comment by tbenst** [comment]
I made a patch for `remote-ssh`:

`sed -i 's/# Launch if needed/f="\/home\/$USER\/.vscode-server\/bin\/$COMMIT_ID\/node"; echo PATCH: replacing $f with $(which node); rm $f; ln -s $(which node) $f/' ~/.vscode/extensions/ms-vscode-remote.remote-ssh/out/extension.js`

**Comment by Mic92** [comment]
This can be closed than as well.
