### ISSUE TITLE
lorri exists in nixpkgs on nixos-19.09 but not home-manager release-19.09

### ISSUE THREAD

**Issue by cprussin** [rycee/home-manager#944]
Lorri [exists in the nixos-19.09 branch of nixpkgs](https://github.com/NixOS/nixpkgs/blob/nixos-19.09/pkgs/tools/misc/lorri/default.nix) but not in the release-19.09 branch of home-manager.  I'm not sure what your philosophy is on backporting such things, but I saw from https://github.com/rycee/home-manager/pull/799 that you wanted the service to only be in home-manager once the package had landed in nixpkgs.  Does that go the other way too?

**Comment by rycee** [comment]
Generally speaking we avoid introducing new modules in the stable branch but since you asked specifically for lorri I cherry-picked it.

**Comment by cprussin** [comment]
ahhh thanks so much @rycee !
