### ISSUE TITLE
Where should bashInteractive and bash-completion packages be added?

### ISSUE THREAD

**Issue by alexvorobiev** [rycee/home-manager#954]
I am currently adding them to home.packages since I couldn't find any options for them. Is that the proper way to add them or are they supposed to be installed differently (overlays, etc.)? Those packages seem to be common choices for bash users.

**Comment by rycee** [comment]
I'd say `home.packages` is a good choice. As long as the completion files ends up in `$NIX_PROFILE_DIR/.nix-profile/etc/bash_completion.d`…
