### ISSUE TITLE
How to set nix binary caches?

### ISSUE THREAD

**Issue by srid** [rycee/home-manager#961]
On NixOS I simply use `nix.binaryCaches` at the system config level ([see example](https://github.com/srid/nix-config/blob/master/nix/caches.nix)), but it is not clear to me how I would do this with home-manager, which is something I use on macOS as well.

**Comment by rycee** [comment]
On macOS I guess it should be done either directly in `/etc/nix/nix.conf` or through [nix-darwin](https://github.com/LnL7/nix-darwin). Managing this is a bit out of scope for Home Manager, I think.
