### ISSUE TITLE
programs.mpv.scripts is too restrictive

### ISSUE THREAD

**Issue by wedens** [rycee/home-manager#976]
`programs.mpv.scripts` has a type `package`, which is too restrictive as `scripts` attribute in mpv-with-scripts derivation accepts any strings.

This becomes a problem when you try to package some script and it ends up in the store without an extension (e.g. /nix/store/yyhwgflq1mmnmdz9lkdn81izxvgs7sj4-mpv-autosub). Mpv just ignores such path.

**Comment by rycee** [comment]
Fair enough, please have a look at https://github.com/rycee/home-manager/pull/983.
