### ISSUE TITLE
Cbatticon tray service ignores GTK theme

### ISSUE THREAD

**Issue by leotaku** [rycee/home-manager#988]
When using home-manager to configure systemd services for tray applications using GTK, the GTK theme sometimes is ignored and the default icons are shown instead. Currently, `cbatticon` seems to exhibit this behavior.

On the left we can see the `cbatticon` instance run from systemd, the one on the right has been run manually from the terminal. 
![cbat](https://user-images.githubusercontent.com/34915973/72350336-8f1e7900-36de-11ea-97f0-19d7c17254fa.png)

I suppose there would have to be some kind of environment variable or similar missing that would allow `cbatticon` to find the correct icons. Possibly this is also just an issue with my personal setup.

@pmiddend can you confirm this issue?

**Comment by pmiddend** [comment]
Mine looks like this:

![2020-01-15_10-19](https://user-images.githubusercontent.com/178496/72421302-7f577100-3780-11ea-92fc-75546f95e937.png)

Note that I'm using `iconType = "symbolic"`. Removing that, it looks like this (on the left):

![2020-01-15_10-20](https://user-images.githubusercontent.com/178496/72421369-a44be400-3780-11ea-8946-1da6989924de.png)

So there's something different in both our environments. Do you have a GTK theme set, or something?

**Comment by leotaku** [comment]
@pmiddend 

> So there's something different in both our environments. Do you have a GTK theme set, or something? Also, do you use the nixos-unstable channel? Could be a different package version of cbatticon

I don't think there is, apart from screen resolution. If you look at the `adwaita-icon-theme` under `legacy` icons, your icon (without "symbolic") is actually just a different resolution of mine (when run from systemd). If I set `iconType = "symbolic"` I also get the same icons as you.

> Edit: Running from the terminal gives the same result.

Do you have a GTK theme set? If so, is it Adwaita? Because Adwaita is the default GTK theme there would be no observable difference whether or not the application has picked up the theme.

**Comment by pmiddend** [comment]
I don't _remember_ setting a GTK theme. I looked for relevant settings under `~/.gtkrc-2.0`, `~/.config/gtk-2.0`, `~/.config/gtk-3.0` but found nothing. Do you know of any another location where the theme is set?

**Comment by leotaku** [comment]
I think it makes sense that you don't have a theme set because in this case, you of course wouldn't observe any difference between the instances run manually or by systems. 

Maybe you could try setting a GTK theme and test if you can then see the difference.

**Comment by rycee** [comment]
The [cbatticon](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/cbatticon/default.nix) derivation doesn't seem to use [wrapGAppsHook](https://nixos.org/nixpkgs/manual/#ssec-gnome-hooks). @leotaku Could you try
```patch
diff --git a/pkgs/applications/misc/cbatticon/default.nix b/pkgs/applications/misc/cbatticon/default.nix
index d6680c61eb9..ac2948c2d6e 100644
--- a/pkgs/applications/misc/cbatticon/default.nix
+++ b/pkgs/applications/misc/cbatticon/default.nix
@@ -1,4 +1,4 @@
-{ stdenv, fetchFromGitHub, pkgconfig, gettext, glib, gtk3, libnotify }:
+{ stdenv, fetchFromGitHub, pkgconfig, gettext, glib, gtk3, libnotify, wrapGAppsHook }:
 
 stdenv.mkDerivation rec {
   pname = "cbatticon";
@@ -11,7 +11,7 @@ stdenv.mkDerivation rec {
     sha256 = "0ivm2dzhsa9ir25ry418r2qg2llby9j7a6m3arbvq5c3kaj8m9jr";
   };
 
-  nativeBuildInputs = [ pkgconfig gettext ];
+  nativeBuildInputs = [ pkgconfig gettext wrapGAppsHook ];
 
   buildInputs =  [ glib gtk3 libnotify ];
```
and see if that makes a difference?

**Comment by leotaku** [comment]
@rycee This in fact fixes the problem. I will open a PR against nixpkgs when I have time and then close this issue.

**Comment by pmiddend** [comment]
Thanks for tracking this down @rycee and @leotaku!

**Comment by leotaku** [comment]
NixOS/nixpkgs#77947 closes this.
