### ISSUE TITLE
example of how to configure zsh?

### ISSUE THREAD

**Issue by MarkRBM** [rycee/home-manager#989]
I am new to Nixos but have it installed on my daily driver laptop and have home manager installed and working.  I am not having a huge amount of luck depending on my own .zshrc file and am getting no such file or directory errors.

I would like to migrate my config to the native home manager way of configuring zsh but I cant find any examples of the zsh module/program being used and am not familiar enough with nix to figure out how to configure it form your zsh/nix file in the programs directory of this repo

might there be a public nix file any of you know about that shows how to configure zsh natively in home manager?

thanks in advance

**Comment by Yumasi** [comment]
[Here](https://github.com/Yumasi/nixos-home/blob/master/zsh.nix) is my own zsh config with aliases, plugins, and a few init commands.

**Comment by kalbasit** [comment]
[Here](https://github.com/kalbasit/shabka/blob/master/modules/home/software/zsh/default.nix) is mine as well. It comes with custom functions installed as plugins with autiload support.

**Comment by MarkRBM** [comment]
thank you both, checking them out now

**Comment by rpearce** [comment]
Here's mine, as well: https://github.com/rpearce/.config/tree/master/nix/programs/zsh

**Comment by MarkRBM** [comment]
is there a specific way to make sure that something gets loaded at the start of th .zshrc file? the env var that sets terminal 256 color support specifically.  I dont think I see any of you doing it but I am getting the error from powerlevel9 that its needed

I tried in the initExtra section but it does not seem to put it at the start of the file

**Comment by rpearce** [comment]
@MarkRBM Not that I'm an expert, but my `$ echo $TERM` is `xterm-256color`, so do you need this?
```
[[ "$TERM" == "xterm" ]] && export TERM=xterm-256color
```
I know you said you need it at the _start_ of the file, but I can't speak to that as I don't know anything about powerlevel9.

Hope this helps...at all

**Comment by MarkRBM** [comment]
yes thank-you that is the export I need and my echo $TERM > xterm-256color also

I am getting the erro spoken about https://github.com/Powerlevel9k/powerlevel9k/issues/135 but I am going to try and move the export TERM=xterm-256color out of my zshrc and into zshenv and see if that does the trick.  just have to figure out how to set the env file with home-manager now to try it

**Comment by MarkRBM** [comment]
ah its a little easier to read the zsh.nix program in home-manager now that I have done a little configuring with it 

https://github.com/rycee/home-manager/blob/master/modules/programs/zsh.nix#L222

this works and no more error anymore

**Comment by Fransz** [comment]
@sukhmel you kan use oh-my-zsh.extraConfig :

    oh-my-zsh = {
         enable = true;
         custom = "$HOME/.config/zsh/omz-custom";
         extraConfig = "zstyle ':omz:alpha:lib:git' async-prompt no";
         plugins = [];
         theme = "my-theme";
     };

**Comment by sukhmel** [comment]
@Fransz, this indeed inserts the following into `.zshrc` before sourcing oh-my-zsh:

    # oh-my-zsh extra settings for plugins
    zstyle ':omz:alpha:lib:git' async-prompt no

I wasn't able to find that option in the [search](https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=zsh.ohMyZsh) and in the [source](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/programs/zsh/oh-my-zsh.nix), but it appears it's defined in [`ohMyZshModule`](https://github.com/nix-community/home-manager/blame/1395379a7a36e40f2a76e7b9936cc52950baa1be/modules/programs/zsh.nix#L201) in `zsh` module of `home-manager`. I guess that I was looking in the wrong place all along, and since my `oh-my-zsh` was managed by `home-manager` that was where I should have been looking for options. It feels like something that is hard to discover, thanks for your help.

**Comment by fn3x** [comment]
Can someone explain me why am I getting an error here? I've double checked the home manager module options for zsh and oh-my-zsh and there is an extraConfig option

`
  programs.zsh = {
    enable = true;
    oh-my-zsh = {
      enable = true;
      plugins = [ "git" "sudo" "ssh-agent" ];
      theme = "robbyrussell";
      extraConfig = ''
        zstyle :omz:plugins:ssh-agent quiet yes
        zstyle :omz:plugins:ssh-agent identities id_github id_bitbucket id_digitalocean id_aws.pem
      '';
    };
  };

  users.users.fn3x = {
    isNormalUser = true;
    description = "Art";
    extraGroups = [ "docker" "networkmanager" "wheel" ];
    shell = pkgs.zsh;
  };
`

`
        error: The option `programs.zsh.oh-my-zsh.extraConfig' does not exist. Definition values:
        - In `/nix/store/77ri4rk0vf3qzigx6nr22lpvvdsnn3j1-source/hosts/desktop/configuration.nix':
            ''
              zstyle :omz:plugins:ssh-agent quiet yes
              zstyle :omz:plugins:ssh-agent identities id_github id_bitbucket id_digitalocean id_aws.pem
            ''
`
