### ISSUE TITLE
Potential programs.nodejs or advice on how to postInstall or pkgs.runCommand?

### ISSUE THREAD

**Issue by rpearce** [rycee/home-manager#995]
Hi! Thank you for this tool.

I do a lot of nodejs at work, and I am trying to figure out if there's a way to do a sort of `postInstall` step, or if I should get guidance on how to add `programs.nodejs` to the `programs` and do it there, or if there's a way to run a `pkgs.runCommand` in a normal `home.nix` file. I'm somewhat new to nix and know enough to get my hands dirty but not enough to get this to work right.

Here's an example that @utdemir showed me, but I'm curious how I can make this work in home-manager:

```nix
let
  pkgs = import <nixpkgs> {};
  user = import ../../user.nix;
in
  pkgs.runCommand "npm-wrapped" {
    buildInputs = [ pkgs.nodejs-13_x pkgs.makeWrapper ];
  } ''
    mkdir -p $out/{bin,etc}
    HOME=$(mktemp -d)

    npm set init.author.name ${user.npm.initAuthorName}
    npm set init.author.email ${user.npm.initAuthorEmail}
    npm set init.author.url ${user.npm.initAuthorUrl}
    npm set init.license ${user.npm.initLicense}
    npm set init.version ${user.npm.initVersion}

    cp $HOME/.npmrc $out/etc/npmrc

    makeWrapper "${pkgs.nodejs-13_x}/bin/npm" "$out/bin/npm" \
      --set PREFIX "$out"
  ''
```

Thank you for any help!

**Comment by rycee** [comment]
Glad you like HM! What do you mean by post install? To add commands to run during `home-manager switch`? Or commands to edit the built HM generation before it is made immutable in the Nix store?

About the example. I think it should work just fine as-is inside `home.packages`, except the `pkgs = …` line can be removed:
```
home.packages = [
  (
    let
      user = import ../../user.nix;
    in
      pkgs.runCommand "npm-wrapped" {
        buildInputs = [ pkgs.nodejs-13_x pkgs.makeWrapper ];
      } ''
        mkdir -p $out/{bin,etc}
        HOME=$(mktemp -d)

        npm set init.author.name ${user.npm.initAuthorName}
        npm set init.author.email ${user.npm.initAuthorEmail}
        npm set init.author.url ${user.npm.initAuthorUrl}
        npm set init.license ${user.npm.initLicense}
        npm set init.version ${user.npm.initVersion}

        cp $HOME/.npmrc $out/etc/npmrc

        makeWrapper "${pkgs.nodejs-13_x}/bin/npm" "$out/bin/npm" \
          --set PREFIX "$out"
      ''
  )
];
```

**Comment by rpearce** [comment]
Thanks for the quick response, and I apologize for any wrong terminology.

As far as I can tell, NPM (installed with `nodejs`) unfortunately doesn't exactly expose the easiest `rc` file to interact with to set personal details to be used when using NPM, so they encourage you to use their `npm set ...` commands. This is an attempt to make it so that whenever `nodejs` is added or updated, or if there is new `user.npm.*` information during `home-manager switch`, `nodejs` and the `NPM` config get updated.

While this doesn't _quite_ do what I want it to, it _does_ build and do what it's told, so thank you for the 👀 !

**Comment by rycee** [comment]
Ah, right. If you want to change the actual rc file in your home directory when you run `home-manager switch` then the best way is to use an "activation block". Something like
```
home.activation.setNpmOptions =
  let
    user = import ../../user.nix;
    npmSet = "$DRY_RUN_CMD ${pkgs.nodejs-13_x}/bin/npm set";
  in
    config.dag.entryAfter ["writeBoundary"] ''
      ${npmSet} init.author.name ${user.npm.initAuthorName}
      ${npmSet} init.author.email ${user.npm.initAuthorEmail}
      ${npmSet} init.author.url ${user.npm.initAuthorUrl}
      ${npmSet} init.license ${user.npm.initLicense}
      ${npmSet} init.version ${user.npm.initVersion}
    '';
```
might work. This will run `npm set` as your user when you activate a HM generation (typically through `home-manager switch`). Perhaps this is closer to what you want?

That said, generally if you can get away with a wrapper that uses a pure configuration file inside the Nix store I would recommend that instead.

**Comment by rpearce** [comment]
Thank you! Only thing that needs changing is `config.dag` to `config.lib.dag`.

This will be great now now! I'll dig further into seeing if silly NPM can let me have a safe-to-use static file.

Keep rocking
