### ISSUE TITLE
attribute 'flavors' missing, at .../home-manager/modules/services/gpg-agent.nix:134:41

### ISSUE THREAD

**Issue by clacke** [rycee/home-manager#999]
```
$ nix-shell '<home-manager>' -A install
[ . . . ]
Creating initial Home Manager generation...

error: attribute 'flavors' missing, at /nix/store/m3pisjv096f4wy4nyfskk8z9mi35c0a7-home-manager/home-manager/modules/services/gpg-agent.nix:134:41
```

**Comment by clacke** [comment]
Ok, not happening on master, only with channel.

**Comment by clacke** [comment]
Hm, but that doesn't make any sense. The channel is just https://github.com/rycee/home-manager/archive/master.tar.gz !

**Comment by rycee** [comment]
It's because you are using the master branch of Home Manager with a stable branch of NixOS/Nixpkgs. You need to switch to the corresponding stable branch of Home Manager, currently [release-19.09](https://github.com/rycee/home-manager/tree/release-19.09).

**Comment by clacke** [comment]
Ah, thanks, never would have figured it out. I have `<nixos>` stable and `<nixpkgs>` unstable.
